import { readFile, writeFile } from "node:fs/promises"
import { resolve } from "node:path"
import { spawnSync } from "node:child_process"

const root = resolve(import.meta.dirname, "../..")
const candid = resolve(root, "canister/bridge-canister/bridge.did")
const destination = resolve(root, "ui/src/generated/bridge.did.ts")
const runtimeDestination = resolve(root, "ui/src/generated/bridge.idl.ts")
const result = spawnSync("didc", ["bind", candid, "-t", "ts"], { encoding: "utf8" })
const runtimeResult = spawnSync("didc", ["bind", candid, "-t", "js"], { encoding: "utf8" })
if (result.status !== 0 || runtimeResult.status !== 0) throw new Error(result.stderr || runtimeResult.stderr || "didc failed")
const generated = `/* Generated by didc 0.5.4 from canister/bridge-canister/bridge.did. Do not edit. */\n${result.stdout}`
const runtime = `/* Generated by didc 0.5.4 from canister/bridge-canister/bridge.did. Do not edit. */\n// @ts-nocheck\n${runtimeResult.stdout}`

if (process.argv.includes("--check")) {
  const existing = await readFile(destination, "utf8").catch(() => "")
  const existingRuntime = await readFile(runtimeDestination, "utf8").catch(() => "")
  if (existing !== generated || existingRuntime !== runtime) throw new Error(`Candid bindings are stale; run pnpm codegen:candid`)
} else {
  await writeFile(destination, generated)
  await writeFile(runtimeDestination, runtime)
}
