// @generated by scripts/generate_refinement_harness.py
// SPDX-License-Identifier: Apache-2.0
pragma solidity 0.8.36;

import {Bridge} from "../src/Bridge.sol";
import {IBSNS} from "../src/interfaces/IBSNS.sol";
import {IBridge} from "../src/interfaces/IBridge.sol";
import {MintAuthorizationPolicy} from "../src/libraries/MintAuthorizationPolicy.sol";
import {TestBase} from "./TestBase.sol";

contract GeneratedRefinementTest is TestBase {
    string private constant VECTORS = "../verification/generated/protocol-vectors.json";
    uint256 private constant BRIDGE_SIGNER_KEY = 0xA11CE;
    address private constant RUNTIME_ADMINISTRATOR = address(0x22);
    address private constant USER = address(0x44);

    function _deployBridge(uint256 serviceFee) private returns (Bridge bridge, IBSNS token) {
        address bridgeSigner = vm.addr(BRIDGE_SIGNER_KEY);
        address timelock = _deployTestTimelock(address(0x33));
        bridge = new Bridge(
            bridgeSigner,
            RUNTIME_ADMINISTRATOR,
            timelock,
            _timelockCodeHash(timelock),
            2_000,
            2_000,
            1 hours,
            1,
            100,
            serviceFee
        );
        token = bridge.bsns();
        vm.prank(timelock);
        bridge.unpauseDepositMints();
        vm.prank(timelock);
        bridge.unpauseWithdrawals();
        IBridge.MintAuthorization memory authorization = IBridge.MintAuthorization({
            depositId: keccak256(abi.encode(serviceFee)),
            recipient: USER,
            grossAmount: 1_100,
            maxServiceFee: serviceFee,
            chargedServiceFee: serviceFee,
            deadline: block.timestamp + 15 minutes,
            authorizationEpoch: bridge.mintAuthorizationEpoch()
        });
        _submitMintAuthorization(BRIDGE_SIGNER_KEY, bridge, authorization, address(this));
    }

    function _uint(string memory json, string memory base, string memory field) private pure returns (uint256) {
        return vm.parseUint(vm.parseJsonString(json, string.concat(base, field)));
    }

    function test_mint_transition_matches_lean_deposit_admission_cases() public view {
        string memory json = vm.readFile(VECTORS);
        uint256 count = vm.parseJsonUint(json, ".deposit_admission_count");
        assert(count > 0);
        for (uint256 index = 0; index < count; ++index) {
            string memory base = string.concat(".deposit_admission_cases[", vm.toString(index), "]");
            MintAuthorizationPolicy.MintTransitionInput memory input = MintAuthorizationPolicy.MintTransitionInput({
                timestamp: 0,
                deadline: 0,
                authorizationEpoch: 1,
                currentEpoch: 1,
                recipient: USER,
                bridge: address(2),
                token: address(3),
                grossAmount: _uint(json, base, ".gross"),
                maximumFee: _uint(json, base, ".maximum_service_fee"),
                chargedFee: _uint(json, base, ".service_fee"),
                protocolMaximumFee: _uint(json, base, ".maximum_service_fee"),
                perDepositLimit: _uint(json, base, ".per_deposit_limit"),
                consumedInWindow: _uint(json, base, ".minted_in_window"),
                windowLimit: _uint(json, base, ".mint_window_limit"),
                windowStartedAt: 0,
                windowDuration: 1,
                paused: false,
                processed: false
            });
            (MintAuthorizationPolicy.RejectReason reason, MintAuthorizationPolicy.MintEffects memory effects,) =
                MintAuthorizationPolicy.evaluateMint(input);
            bool accepted = vm.parseJsonBool(json, string.concat(base, ".accepted"));
            assert((reason == MintAuthorizationPolicy.RejectReason.None) == accepted);
            if (accepted) {
                uint256 expectedNet = _uint(json, base, ".net");
                assert(effects.mintAmount == expectedNet);
                assert(effects.supplyIncrease == expectedNet);
                assert(effects.eventMintedAmount == expectedNet);
            }
        }
    }

    function test_protocol_quote_cases_matches_production() public {
        string memory json = vm.readFile(VECTORS);
        uint256 count = vm.parseJsonUint(json, ".quote_count");
        assert(count > 0);
        for (uint256 index = 0; index < count; ++index) {
            string memory base = string.concat(".quote_cases[", vm.toString(index), "]");
            uint256 amount = vm.parseUint(vm.parseJsonString(json, string.concat(base, ".amount")));
            uint256 serviceFee = vm.parseUint(vm.parseJsonString(json, string.concat(base, ".service_fee")));
            bool accepted = vm.parseJsonBool(json, string.concat(base, ".accepted"));
            (Bridge bridge, IBSNS token) = _deployBridge(serviceFee);
            vm.prank(USER);
            token.approve(address(bridge), amount);
            if (!accepted) {
                vm.prank(USER);
                vm.expectRevert(abi.encodeWithSelector(IBridge.InvalidAmount.selector, amount));
                bridge.createWithdrawal(amount, serviceFee, hex"01", bytes32(0));
                continue;
            }
            uint256 expectedAmountOut = vm.parseUint(vm.parseJsonString(json, string.concat(base, ".amount_out")));
            vm.prank(USER);
            uint256 withdrawalId = bridge.createWithdrawal(amount, serviceFee, hex"01", bytes32(0));
            IBridge.Withdrawal memory withdrawal = bridge.getWithdrawal(withdrawalId);
            assert(withdrawal.amount == amount);
            assert(withdrawal.chargedServiceFee == serviceFee);
            assert(withdrawal.amountOut == expectedAmountOut);
            assert(withdrawal.status == IBridge.WithdrawalStatus.Committed);
        }
    }
}
