// @generated by scripts/generate_refinement_harness.py
use bridge_core::{
    canonical_probe_matches, committed_quote_matches, deposit_identity_decision,
    deposit_ledger_block_transition, deposit_nonterminal_indexed, fee_recipient_rotation_allowed,
    funding_attempt_decision, funding_reconciliation_decision, hold_retry_allowed,
    lease_lane_claim_decision, lease_outcome_is_current, manual_claim_allowed,
    notification_admission_allowed, notification_ingestion_allowed, outbound_settlement,
    payout_allowed, payout_debit, refund_request_identity_decision, release_transfer_matches,
    reserve_admission_preserves_requirement, service_fee_change_allowed,
    withdrawal_ledger_block_transition, Amount, BaseMintSnapshot, DepositIdentityDecision,
    FundingAttemptDecision, FundingReconciliationDecision, LeaseLaneClaimDecision,
    RefundRequestIdentityDecision,
};
use serde_json::Value;

fn document() -> Value {
    let document: Value = serde_json::from_str(include_str!(
        "../../../verification/generated/protocol-vectors.json"
    ))
    .expect("Lean protocol vectors must be valid JSON");
    assert_eq!(document["schema_version"].as_u64(), Some(3));
    document
}

fn cases(section: &str) -> Vec<Value> {
    document()[section]
        .as_array()
        .expect("registered vector section must be an array")
        .clone()
}

fn text<'a>(case: &'a Value, field: &str) -> &'a str {
    case[field].as_str().expect("vector field must be a string")
}

fn optional_text<'a>(case: &'a Value, field: &str) -> Option<&'a str> {
    case.get(field).and_then(Value::as_str)
}

fn boolean(case: &Value, field: &str) -> bool {
    case[field]
        .as_bool()
        .expect("vector field must be a boolean")
}

fn amount(value: &str) -> u128 {
    value.parse().expect("vector amount must be canonical u128")
}

fn block(value: &str) -> u64 {
    value.parse().expect("vector block must be canonical u64")
}

fn short(value: &str) -> u16 {
    value.parse().expect("vector counter must be canonical u16")
}

fn backed(state: (u128, u128, u128, u128)) -> bool {
    state
        .1
        .checked_add(state.2)
        .and_then(|value| value.checked_add(state.3))
        == Some(state.0)
}

#[test]
fn protocol_canonical_probe_cases_matches_production() {
    for case in cases("canonical_probe_cases") {
        assert_eq!(
            canonical_probe_matches(
                block(text(&case, "receipt_block")),
                block(text(&case, "snapshot_block")),
            ),
            boolean(&case, "accepted")
        );
    }
}

#[test]
fn protocol_deposit_admission_cases_matches_production() {
    for case in cases("deposit_admission_cases") {
        let maximum = amount(text(&case, "maximum_service_fee"));
        let snapshot = BaseMintSnapshot {
            finalized_head_block_number: 1,
            confirmed_block_timestamp: 0,
            service_fee: Amount::new(amount(text(&case, "service_fee"))),
            max_service_fee: Amount::new(maximum),
            per_deposit_limit: Amount::new(amount(text(&case, "per_deposit_limit"))),
            mint_window_limit: Amount::new(amount(text(&case, "mint_window_limit"))),
            mint_window_started_at: 0,
            mint_window_duration: u64::MAX,
            minted_in_window: Amount::new(amount(text(&case, "minted_in_window"))),
        };
        let actual = snapshot
            .quote(
                Amount::new(amount(text(&case, "gross"))),
                Amount::new(maximum),
            )
            .ok()
            .map(|value| value.get());
        assert_eq!(actual.is_some(), boolean(&case, "accepted"));
        assert_eq!(actual, optional_text(&case, "net").map(amount));
    }
}

#[test]
fn protocol_deposit_identity_cases_matches_production() {
    for case in cases("deposit_identity_cases") {
        let actual = match deposit_identity_decision(boolean(&case, "processed")) {
            DepositIdentityDecision::Allow => "Allow",
            DepositIdentityDecision::Conflict => "Conflict",
        };
        assert_eq!(actual, text(&case, "decision"));
    }
}

#[test]
fn protocol_deposit_nonterminal_index_cases_match_production() {
    for case in cases("deposit_nonterminal_index_cases") {
        assert_eq!(
            deposit_nonterminal_indexed(short(text(&case, "state")) as u8,),
            boolean(&case, "indexed")
        );
    }
}

#[test]
fn protocol_fee_payout_cases_matches_production() {
    for case in cases("fee_payout_cases") {
        let reserve = amount(text(&case, "reserve"));
        let pending = amount(text(&case, "pending"));
        let payout_amount = amount(text(&case, "amount"));
        let fee = amount(text(&case, "fee"));
        assert_eq!(
            payout_allowed(reserve, pending, payout_amount, fee),
            boolean(&case, "allowed")
        );
        assert_eq!(
            payout_debit(true, payout_amount, fee),
            Some(amount(text(&case, "first_debit")))
        );
        assert_eq!(
            payout_debit(false, payout_amount, fee),
            Some(amount(text(&case, "replay_debit")))
        );
    }
}

#[test]
fn protocol_fee_rotation_cases_matches_production() {
    for case in cases("fee_rotation_cases") {
        let accepted = fee_recipient_rotation_allowed(amount(text(&case, "pending")));
        assert_eq!(accepted, boolean(&case, "accepted"));
        if accepted {
            assert_eq!(text(&case, "before_reserve"), text(&case, "after_reserve"));
            assert_eq!(
                text(&case, "before_deposit_fees"),
                text(&case, "after_deposit_fees")
            );
            assert_eq!(
                text(&case, "before_withdrawal_fees"),
                text(&case, "after_withdrawal_fees")
            );
            assert_eq!(
                text(&case, "next_recipient"),
                text(&case, "after_recipient")
            );
        } else {
            assert_eq!(
                text(&case, "before_recipient"),
                text(&case, "after_recipient")
            );
        }
    }
}

#[test]
fn protocol_funding_attempt_cases_matches_production() {
    for case in cases("funding_attempt_cases") {
        let actual = funding_attempt_decision(
            block(text(&case, "outcome_kind"))
                .try_into()
                .expect("funding outcome kind fits u8"),
        );
        let expected = match text(&case, "decision") {
            "promote-success" => FundingAttemptDecision::PromoteSuccess,
            "promote-ambiguous" => FundingAttemptDecision::PromoteAmbiguous,
            "release" => FundingAttemptDecision::Release,
            "retain" => FundingAttemptDecision::Retain,
            value => panic!("unknown funding attempt decision: {value}"),
        };
        assert_eq!(actual, expected);
    }
}

#[test]
fn protocol_funding_reconciliation_cases_matches_production() {
    for case in cases("funding_reconciliation_cases") {
        let actual = funding_reconciliation_decision(
            boolean(&case, "complete_absence"),
            boolean(&case, "final_scan"),
            boolean(&case, "dedup_expired"),
        );
        let expected = match text(&case, "decision") {
            "wait" => FundingReconciliationDecision::Wait,
            "restart-fresh" => FundingReconciliationDecision::RestartFresh,
            "release" => FundingReconciliationDecision::Release,
            value => panic!("unknown funding reconciliation decision: {value}"),
        };
        assert_eq!(actual, expected);
    }
}

#[test]
fn protocol_hold_cases_matches_production() {
    for case in cases("hold_cases") {
        assert_eq!(
            hold_retry_allowed(boolean(&case, "success"), boolean(&case, "absence"),),
            boolean(&case, "allowed")
        );
    }
}

#[test]
fn protocol_lease_cases_matches_production() {
    for case in cases("lease_cases") {
        assert_eq!(
            lease_outcome_is_current(
                block(text(&case, "current")),
                block(text(&case, "outcome")),
                boolean(&case, "active"),
            ),
            boolean(&case, "accepted")
        );
    }
}

#[test]
fn protocol_lease_lane_cases_matches_production() {
    for case in cases("lease_lane_cases") {
        let actual = lease_lane_claim_decision(
            boolean(&case, "target_active"),
            boolean(&case, "target_automatic"),
            block(text(&case, "active_in_lane")),
            block(text(&case, "capacity")),
        );
        let expected = match text(&case, "decision") {
            "allow" => LeaseLaneClaimDecision::Allow,
            "automatic-progress-pending" => LeaseLaneClaimDecision::AutomaticProgressPending,
            "busy" => LeaseLaneClaimDecision::Busy,
            value => panic!("unknown lease lane decision: {value}"),
        };
        assert_eq!(actual, expected);
    }
}

#[test]
fn protocol_ledger_block_provenance_cases_match_production() {
    for case in cases("ledger_block_provenance_cases") {
        let funding = optional_text(&case, "funding").map(amount);
        let refund = optional_text(&case, "refund").map(amount);
        let release = optional_text(&case, "release").map(amount);
        let candidate = amount(text(&case, "block"));
        let accepted = boolean(&case, "accepted");
        match text(&case, "event") {
            "preserve" => {
                let deposit = deposit_ledger_block_transition(funding, refund, 0, candidate);
                assert_eq!(deposit.is_some(), accepted);
                assert_eq!(
                    deposit.and_then(|blocks| blocks.0),
                    optional_text(&case, "next_funding").map(amount)
                );
                assert_eq!(
                    deposit.and_then(|blocks| blocks.1),
                    optional_text(&case, "next_refund").map(amount)
                );
                let withdrawal = withdrawal_ledger_block_transition(release, 0, candidate);
                assert_eq!(withdrawal.is_some(), accepted);
                assert_eq!(
                    withdrawal.flatten(),
                    optional_text(&case, "next_release").map(amount)
                );
            }
            "funding" | "refund" => {
                let event = if text(&case, "event") == "funding" {
                    1
                } else {
                    2
                };
                let deposit = deposit_ledger_block_transition(funding, refund, event, candidate);
                assert_eq!(deposit.is_some(), accepted);
                assert_eq!(
                    deposit.and_then(|blocks| blocks.0),
                    optional_text(&case, "next_funding").map(amount)
                );
                assert_eq!(
                    deposit.and_then(|blocks| blocks.1),
                    optional_text(&case, "next_refund").map(amount)
                );
            }
            "release" => {
                let withdrawal = withdrawal_ledger_block_transition(release, 1, candidate);
                assert_eq!(withdrawal.is_some(), accepted);
                assert_eq!(
                    withdrawal.flatten(),
                    optional_text(&case, "next_release").map(amount)
                );
            }
            event => panic!("unknown ledger block event: {event}"),
        }
    }
}

#[test]
fn protocol_manual_claim_cases_matches_production() {
    for case in cases("manual_claim_cases") {
        assert_eq!(
            manual_claim_allowed(
                boolean(&case, "scheduled"),
                boolean(&case, "active"),
                boolean(&case, "stopped"),
                boolean(&case, "overdue"),
                boolean(&case, "expired"),
            ),
            boolean(&case, "allowed")
        );
    }
}

#[test]
fn protocol_notification_admission_cases_matches_production() {
    for case in cases("notification_admission_cases") {
        assert_eq!(
            notification_admission_allowed(
                short(text(&case, "global_count")),
                short(text(&case, "caller_count")),
                short(text(&case, "global_limit")),
                short(text(&case, "caller_limit")),
            ),
            boolean(&case, "allowed")
        );
        assert_eq!(
            notification_ingestion_allowed(
                short(text(&case, "ingestion_count")),
                short(text(&case, "ingestion_limit")),
            ),
            boolean(&case, "ingestion_allowed")
        );
    }
}

#[test]
fn protocol_payment_cases_matches_production() {
    for case in cases("payment_cases") {
        let accepted = !boolean(&case, "already_paid")
            && boolean(&case, "destination_matches")
            && amount(text(&case, "transfer_fee")) <= amount(text(&case, "charged_fee"))
            && release_transfer_matches(
                amount(text(&case, "transfer_amount")),
                amount(text(&case, "transfer_fee")),
                amount(text(&case, "amount_out")),
                amount(text(&case, "transfer_fee")),
            );
        assert_eq!(accepted, boolean(&case, "accepted"));
    }
}

#[test]
fn protocol_quote_cases_matches_production() {
    for case in cases("quote_cases") {
        let amount_value = amount(text(&case, "amount"));
        let service_fee = amount(text(&case, "service_fee"));
        let actual = optional_text(&case, "amount_out")
            .map(amount)
            .is_some_and(|amount_out| {
                committed_quote_matches(amount_value, amount_out, service_fee)
            });
        assert_eq!(actual, boolean(&case, "accepted"));
    }
}

#[test]
fn protocol_refund_request_identity_cases_matches_production() {
    for case in cases("refund_request_identity_cases") {
        let actual = refund_request_identity_decision(boolean(&case, "authenticated"));
        let expected = match text(&case, "decision") {
            "allow" => RefundRequestIdentityDecision::Allow,
            "anonymous-caller" => RefundRequestIdentityDecision::AnonymousCaller,
            value => panic!("unknown refund request identity decision: {value}"),
        };
        assert_eq!(actual, expected);
    }
}

#[test]
fn protocol_reservation_cases_matches_production() {
    for case in cases("reservation_cases") {
        let before_reserved = amount(text(&case, "before_reserved"));
        let before_candidate = amount(text(&case, "before_candidate"));
        let after_reserved = amount(text(&case, "after_reserved"));
        let after_candidate = amount(text(&case, "after_candidate"));
        let exact_commit = before_reserved
            .checked_add(before_candidate)
            .is_some_and(|committed| committed == after_reserved && after_candidate == 0);
        assert_eq!(
            exact_commit
                && reserve_admission_preserves_requirement(
                    before_reserved,
                    before_candidate,
                    after_reserved,
                    after_candidate,
                ),
            boolean(&case, "accepted")
        );
    }
}

#[test]
fn protocol_service_fee_cases_matches_production() {
    for case in cases("service_fee_cases") {
        assert_eq!(
            service_fee_change_allowed(
                amount(text(&case, "service_fee")),
                amount(text(&case, "maximum")),
            ),
            boolean(&case, "accepted")
        );
    }
}

#[test]
fn protocol_settlement_cases_matches_production() {
    for case in cases("settlement_cases") {
        let amount_out = amount(text(&case, "amount_out"));
        let ledger_fee = amount(text(&case, "ledger_fee"));
        let service_fee = amount(text(&case, "service_fee"));
        let arithmetic = outbound_settlement(amount_out, ledger_fee, service_fee);
        assert_eq!(
            arithmetic.unwrap_or((0, 0, 0)),
            (
                amount(text(&case, "escrow_debit")),
                amount(text(&case, "reserve_credit")),
                amount(text(&case, "liability_debit")),
            )
        );
        let before = (
            amount(text(&case, "before_escrow")),
            amount(text(&case, "before_base_supply")),
            amount(text(&case, "before_fee_reserve")),
            amount(text(&case, "before_unpaid_liability")),
        );
        assert_eq!(backed(before), boolean(&case, "before_backed"));
        let checked_after = arithmetic.and_then(|_| {
            Some((
                before.0.checked_sub(amount_out.checked_add(ledger_fee)?)?,
                before.1,
                before.2.checked_add(service_fee)?.checked_sub(ledger_fee)?,
                before.3.checked_sub(amount_out.checked_add(service_fee)?)?,
            ))
        });
        let accepted = boolean(&case, "before_backed") && checked_after.is_some();
        assert_eq!(accepted, boolean(&case, "accepted"));
        let after = checked_after
            .filter(|_| boolean(&case, "before_backed"))
            .unwrap_or(before);
        assert_eq!(
            after,
            (
                amount(text(&case, "after_escrow")),
                amount(text(&case, "after_base_supply")),
                amount(text(&case, "after_fee_reserve")),
                amount(text(&case, "after_unpaid_liability")),
            )
        );
        assert_eq!(backed(after), boolean(&case, "after_backed"));
    }
}
