#!/usr/bin/env bash
set -euo pipefail
ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
T="$(mktemp -d "${TMPDIR:-/tmp}/bridge-driver-test.XXXXXX")"
trap 'rm -rf "$T"' EXIT
mkdir -p "$T/bin" "$T/bundle" "$T/source/contracts" "$T/source/scripts" "$T/source/src"
cp "$ROOT/scripts/production-deploy-driver.sh" "$ROOT/scripts/production-activate-driver.sh" "$ROOT/scripts/production-activation-proposal.sh" "$ROOT/scripts/production-live-preflight.sh" "$ROOT/scripts/production-validation.sh" "$ROOT/scripts/live_fee_guard.py" "$T/source/scripts/"
cat >"$T/source/scripts/ci-local.sh" <<'SH'
#!/usr/bin/env bash
set -euo pipefail
[[ "${1:-}" == proofs ]]
printf 'proofs %s\n' "$*" >>"$TRACE"
if [[ "${PROOF_GATE_FAIL:-false}" == true ]]; then exit 42; fi
if [[ "${PROOF_GATE_MUTATE_SOURCE:-false}" == true ]]; then
  printf '\n// proof mutation\n' >>"$(cd "$(dirname "$0")/.." && pwd)/src/main.rs"
fi
SH
cat >"$T/source/scripts/rebuild-release-artifacts.sh" <<'SH'
#!/usr/bin/env bash
set -euo pipefail
printf 'rebuild %s\n' "$*" >>"$TRACE"
[[ "${REPRODUCIBLE_BUILD_FAIL:-false}" != true ]]
SH
chmod +x "$T/source/scripts/production-deploy-driver.sh" "$T/source/scripts/production-activate-driver.sh" "$T/source/scripts/production-activation-proposal.sh" "$T/source/scripts/production-live-preflight.sh" "$T/source/scripts/ci-local.sh"
chmod +x "$T/source/scripts/rebuild-release-artifacts.sh"
printf '/target\n' >"$T/source/.gitignore"
cat >"$T/source/Cargo.toml" <<'TOML'
[package]
name = "bridge-profile"
version = "0.0.0"
edition = "2021"
TOML
cat >"$T/source/Cargo.lock" <<'LOCK'
# This file is automatically @generated by Cargo.
version = 4

[[package]]
name = "bridge-profile"
version = "0.0.0"
LOCK
cat >"$T/source/src/main.rs" <<'RS'
use std::{env,fs,path::Path};
fn copy_dir(from:&Path,to:&Path){fs::create_dir_all(to).unwrap();for e in fs::read_dir(from).unwrap(){let e=e.unwrap();let d=to.join(e.file_name());if e.path().is_dir(){copy_dir(&e.path(),&d)}else{fs::copy(e.path(),d).unwrap();}}}
fn main(){let a:Vec<String>=env::args().skip(1).collect();if a[0]=="render-release-inputs"{copy_dir(Path::new(&env::var("RENDER_SOURCE").unwrap()),Path::new(&a[2]));return}let c=if a[0]=="verify-live"{'b'}else{'a'};println!("gate=pass manifest_sha256={}",c.to_string().repeat(64));}
RS
git -C "$T/source" init -q
git -C "$T/source" config user.email bridge-test@example.invalid
git -C "$T/source" config user.name bridge-test
git -C "$T/source" add .
git -C "$T/source" commit -qm 'reviewed driver fixture'
DRIVER_ROOT="$T/source"
export TRACE="$T/trace"
: >"$TRACE"
cat >"$T/bin/forge" <<'SH'
#!/usr/bin/env bash
echo "forge $*" >>"$TRACE"; [[ " $* " == *" --ledger "* ]]
if [[ "$*" == *BridgeTimelockController* ]]; then touch "$TIMELOCK_DEPLOYED_MARKER"; echo '{"deployedTo":"0x2222222222222222222222222222222222222222","transactionHash":"0xbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb"}'; else touch "$BRIDGE_DEPLOYED_MARKER"; echo '{"deployedTo":"0x3333333333333333333333333333333333333333","transactionHash":"0xaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa"}'; fi
SH
cat >"$T/bin/ci-local.sh" <<'SH'
#!/usr/bin/env bash
touch "$PATH_PROOF_OVERRIDE_MARKER"
exit 0
SH
cat >"$T/bin/cast" <<'SH'
#!/usr/bin/env bash
echo "cast $*" >>"$TRACE"
case "$1 $2" in
  'keccak PROPOSER_ROLE') printf '0x%s\n' "$(printf '11%.0s' {1..32})";;
  'keccak EXECUTOR_ROLE') printf '0x%s\n' "$(printf '22%.0s' {1..32})";;
  'keccak CANCELLER_ROLE') printf '0x%s\n' "$(printf '33%.0s' {1..32})";;
  'keccak RoleGranted(bytes32,address,address)') printf '0x%s\n' "$(printf '44%.0s' {1..32})";;
  'keccak RoleRevoked(bytes32,address,address)') printf '0x%s\n' "$(printf '55%.0s' {1..32})";;
  'keccak DepositMintsPaused(address)') printf '0x%s\n' "$(printf '66%.0s' {1..32})";;
  'keccak WithdrawalsPaused(address)') printf '0x%s\n' "$(printf '77%.0s' {1..32})";;
  'keccak Cancelled(bytes32)') printf '0x%s\n' "$(printf '88%.0s' {1..32})";;
  'keccak 0x00') printf '0x%s\n' "$(printf 'cc%.0s' {1..32})";;
  'keccak 0x01') printf '0x%s\n' "$(printf 'dd%.0s' {1..32})";;
  'nonce 0x4444444444444444444444444444444444444444') [[ -e "$TIMELOCK_DEPLOYED_MARKER" ]] && echo 1 || echo 0;;
  'compute-address 0x4444444444444444444444444444444444444444') [[ "$*" == *'--nonce 0'* ]] && echo 'Computed Address: 0x2222222222222222222222222222222222222222' || echo 'Computed Address: 0x3333333333333333333333333333333333333333';;
  'chain-id --rpc-url') if [[ "${PROVIDER_CHAIN_FAILURES:-0}" -ge 1 && "$*" == *one.example* ]] || [[ "${PROVIDER_CHAIN_FAILURES:-0}" -ge 2 && "$*" == *two.example* ]]; then exit 1; elif [[ "${PROVIDER_WRONG_CHAINS:-0}" -ge 1 && "$*" == *one.example* ]] || [[ "${PROVIDER_WRONG_CHAINS:-0}" -ge 2 && "$*" == *two.example* ]]; then echo 1; else echo 8453; fi;;
  'block safe'|'block finalized') if [[ "${PROVIDER_SAFE_FAILURES:-0}" -ge 1 && "$*" == *one.example* ]] || [[ "${PROVIDER_SAFE_FAILURES:-0}" -ge 2 && "$*" == *two.example* ]]; then exit 1; fi; h="${LATEST_HEIGHT:-100}"; if [[ "${LATEST_BLOCK_DRIFT:-}" =~ ^(all|one)$ && "$*" == *one.example* ]]; then x=1; elif [[ "${LATEST_BLOCK_DRIFT:-}" == all && "$*" == *two.example* ]]; then x=2; elif [[ "${LATEST_BLOCK_DRIFT:-}" == all ]]; then x=3; else x=a; fi; printf '{"number":"0x%x","hash":"0x%s"}\n' "$h" "$(printf "$x%.0s" {1..64})";;
  'block 100') if [[ "${MID_READ_REORG:-}" == all ]]; then x=f; elif [[ "${MID_READ_REORG:-}" == one && "$*" == *three.example* ]]; then x=f; elif [[ "${SIGNED_BLOCK_DRIFT:-}" == all && "$*" == *one.example* ]]; then x=1; elif [[ "${SIGNED_BLOCK_DRIFT:-}" == all && "$*" == *two.example* ]]; then x=2; elif [[ "${SIGNED_BLOCK_DRIFT:-}" == all ]]; then x=3; else x=a; fi; printf '{"number":"0x64","hash":"0x%s"}\n' "$(printf "$x%.0s" {1..64})";;
  'block 1') printf '{"number":"0x1","hash":"0x%s"}\n' "$(printf 'a%.0s' {1..64})";;
  'receipt deposit-action') printf '{"blockNumber":"0x64","blockHash":"0x%s","status":"0x1","logs":[{"address":"0x3333333333333333333333333333333333333333","topics":["0x%s"]}]}\n' "$(printf 'a%.0s' {1..64})" "$(printf '66%.0s' {1..32})";;
  'receipt withdrawal-action') printf '{"blockNumber":"0x64","blockHash":"0x%s","status":"0x1","logs":[{"address":"0x3333333333333333333333333333333333333333","topics":["0x%s"]}]}\n' "$(printf 'a%.0s' {1..64})" "$(printf '77%.0s' {1..32})";;
  'receipt cancel-action') printf '{"blockNumber":"0x64","blockHash":"0x%s","status":"0x1","logs":[{"address":"0x2222222222222222222222222222222222222222","topics":["0x%s"]}]}\n' "$(printf 'a%.0s' {1..64})" "$(printf '88%.0s' {1..32})";;
  'tx deposit-action') echo '{"to":"0x3333333333333333333333333333333333333333","input":"0x1111"}';;
  'tx withdrawal-action') echo '{"to":"0x3333333333333333333333333333333333333333","input":"0x2222"}';;
  'tx cancel-action') echo '{"to":"0x2222222222222222222222222222222222222222","input":"0x3333"}';;
  'receipt 0x'*) if [[ "$2" == "0x$(printf 'a%.0s' {1..64})" ]]; then address=0x3333333333333333333333333333333333333333; bh=b; else address=0x2222222222222222222222222222222222222222; bh=c; fi; if [[ "${DEPLOYMENT_RECEIPT_DRIFT:-}" == true || ( "${ACTIVATION_RECEIPT_DRIFT:-}" == true && "$2" != "0x$(printf 'a%.0s' {1..64})" && "$2" != "0x$(printf 'b%.0s' {1..64})" ) ]]; then bh=f; fi; printf '{"blockNumber":"0x1","blockHash":"0x%s","status":"0x1","contractAddress":"%s"}\n' "$(printf "$bh%.0s" {1..64})" "$address";;
  'logs --address') if [[ "${ROLE_EVENT_DRIFT:-}" == true ]]; then role="$(printf 'ff%.0s' {1..32})"; else role="$(printf '00%.0s' {1..32})"; fi; if [[ "${ROLE_EVENT_HASH_DRIFT:-}" == true ]]; then eh=f; else eh=c; fi; printf '[{"blockNumber":"0x1","blockHash":"0x%s","topics":["0x%s","0x%s","0x%s"]},{"blockNumber":"0x1","blockHash":"0x%s","topics":["0x%s","0x%s","0x%s"]},{"blockNumber":"0x1","blockHash":"0x%s","topics":["0x%s","0x%s","0x%s"]},{"blockNumber":"0x1","blockHash":"0x%s","topics":["0x%s","0x%s","0x%s"]}]\n' \
    "$(printf "$eh%.0s" {1..64})" "$(printf '44%.0s' {1..32})" "$role" "$(printf '00%.0s' {1..12})2222222222222222222222222222222222222222" \
    "$(printf "$eh%.0s" {1..64})" "$(printf '44%.0s' {1..32})" "$(printf '11%.0s' {1..32})" "$(printf '00%.0s' {1..12})6666666666666666666666666666666666666666" \
    "$(printf "$eh%.0s" {1..64})" "$(printf '44%.0s' {1..32})" "$(printf '22%.0s' {1..32})" "$(printf '00%.0s' {1..12})6666666666666666666666666666666666666666" \
    "$(printf "$eh%.0s" {1..64})" "$(printf '44%.0s' {1..32})" "$(printf '33%.0s' {1..32})" "$(printf '00%.0s' {1..12})6666666666666666666666666666666666666666";;
  'code 0x3333333333333333333333333333333333333333') [[ -e "$BRIDGE_DEPLOYED_MARKER" ]] && echo 0x00 || echo 0x;;
  'code 0x2222222222222222222222222222222222222222') if [[ ! -e "$TIMELOCK_DEPLOYED_MARKER" ]]; then echo 0x; elif [[ "${TIMELOCK_CODE_DRIFT:-}" == true ]]; then echo 0x01; else echo 0x00; fi;;
  'code 0x7777777777777777777777777777777777777777') echo 0x00;;
  'calldata unpauseDepositMints()') echo 0x1111;;
  'calldata unpauseWithdrawals()') echo 0x2222;;
  'calldata '*) printf '0x%s\n' "${*:2}";;
  'rpc --rpc-url')
    if [[ "${PROVIDER_EIP1898_FAILURES:-0}" -ge 1 && "$*" == *one.example* ]] || [[ "${PROVIDER_EIP1898_FAILURES:-0}" -ge 2 && "$*" == *two.example* ]]; then exit 1; fi
    if [[ "$*" == *'"blockHash":"0xffff'* ]] || [[ "${MID_READ_REORG:-}" == all ]] || [[ "${MID_READ_REORG:-}" == one && "$*" == *three.example* ]] || [[ "${SIGNED_BLOCK_DRIFT:-}" == all ]]; then exit 1; fi
    if [[ "$*" == *eth_getCode* ]]; then
      if [[ "${TIMELOCK_CODE_DRIFT:-}" == true && "$*" == *0x2222222222222222222222222222222222222222* ]]; then echo '"0x01"'; else echo '"0x00"'; fi
    elif [[ "$*" == *bridgeSnapshot* ]]; then
      if [[ "${CANONICAL_PROBE_MALFORMED:-}" == true ]]; then echo '"0x00"'; elif [[ "${CANONICAL_PROBE_BLOCK_MISMATCH:-}" == true ]]; then printf '"0x%064x%s"\n' 99 "$(printf '0%.0s' {1..704})"; elif [[ "$*" == *'"blockHash":"0xbbbb'* ]]; then printf '"0x%064x%s"\n' 1 "$(printf '0%.0s' {1..704})"; else printf '"0x%064x%s"\n' 100 "$(printf '0%.0s' {1..704})"; fi
    elif [[ "$*" == *bridgeSigner* ]]; then if [[ "${PROVIDER_DRIFT:-}" == all && "$*" == *one.example* ]]; then v=0x9999999999999999999999999999999999999991; elif [[ "${PROVIDER_DRIFT:-}" == all && "$*" == *two.example* ]]; then v=0x9999999999999999999999999999999999999992; elif [[ "${PROVIDER_DRIFT:-}" == all ]]; then v=0x9999999999999999999999999999999999999993; else v=0x1111111111111111111111111111111111111111; fi; printf '"0x%s"\n' "$v";
    elif [[ "$*" == *runtimeAdministrator* ]]; then echo '"0x0x6666666666666666666666666666666666666666"';
    elif [[ "$*" == *baseAdminTimelock* ]]; then echo '"0x0x2222222222222222222222222222222222222222"';
    elif [[ "$*" == *approvedTimelockRuntimeCodeHash* ]]; then [[ "${BRIDGE_APPROVED_HASH_DRIFT:-}" == true ]] && x=dd || x=cc; printf '"0x0x%s"\n' "$(printf "$x%.0s" {1..32})";
    elif [[ "$*" == *'bsns()(address)'* ]]; then echo '"0x0x7777777777777777777777777777777777777777"';
    elif [[ "$*" == *depositMintsPaused* ]]; then if [[ "${CONFIRM_FAIL:-}" == true && -e "$DEPOSIT_PAUSED_MARKER" ]]; then v=false; elif [[ -e "$DEPOSIT_PAUSED_MARKER" ]]; then v=true; elif [[ -e "$EXECUTED_MARKER" || "${BASE_PAUSED:-true}" != true ]]; then v=false; else v=true; fi; echo "\"0x$v\"";
    elif [[ "$*" == *withdrawalsPaused* ]]; then if [[ "${CONFIRM_FAIL:-}" == true && -e "$WITHDRAWAL_PAUSED_MARKER" ]]; then v=false; elif [[ -e "$WITHDRAWAL_PAUSED_MARKER" ]]; then v=true; elif [[ -e "$EXECUTED_MARKER" || "${BASE_PAUSED:-true}" != true ]]; then v=false; else v=true; fi; echo "\"0x$v\"";
    elif [[ "$*" == *serviceFee* ]]; then echo '"0x50000000"';
    elif [[ "$*" == *getMinDelay* ]]; then printf '"0x%064x"\n' 86400;
    elif [[ "$*" == *hasRole* ]]; then if [[ "${ROLE_DRIFT:-}" == true && "$*" != *"0x$(printf '00%.0s' {1..32})"* && "$*" != *' 0x0000000000000000000000000000000000000000'* ]]; then v=false; elif [[ "$*" == *"0x$(printf '00%.0s' {1..32}) 0x2222222222222222222222222222222222222222"* ]]; then v=true; elif [[ "$*" == *"0x$(printf '00%.0s' {1..32})"* || "$*" == *' 0x0000000000000000000000000000000000000000'* ]]; then v=false; else v=true; fi; echo "\"0x$v\"";
    elif [[ "$*" == *isOperationDone* ]]; then [[ -e "$EXECUTED_MARKER" ]] && v=true || v=false; echo "\"0x$v\"";
    elif [[ "$*" == *isOperationPending* || "$*" == *isOperationReady* ]]; then [[ -e "$EXECUTED_MARKER" || -e "$CANCELLED_MARKER" ]] && v=false || v=true; echo "\"0x$v\"";
    elif [[ "$*" == *'name()(string)'* || "$*" == *'symbol()(string)'* ]]; then echo '"0xKINIC"';
    elif [[ "$*" == *'decimals()(uint8)'* ]]; then echo '"0x8"';
    elif [[ "$*" == *'bridge()(address)'* ]]; then echo '"0x0x3333333333333333333333333333333333333333"';
    else echo "unexpected cast rpc: $*" >&2; exit 1; fi;;
  'decode-abi '*) v="${3#0x}"; if [[ "$2" == *'(string)'* ]]; then printf '"%s"\n' "$v"; elif [[ "$2" == getMinDelay* ]]; then echo 86400; else echo "$v"; fi;;
  'send '*) if [[ "$*" == *executeBatch* ]]; then [[ "${EXECUTE_FAIL:-}" != true ]] || exit 1; touch "$EXECUTED_MARKER"; tx=e; elif [[ "$*" == *'cancel(bytes32)'* ]]; then if [[ -e "$EXECUTED_MARKER" ]]; then exit 1; fi; touch "$CANCELLED_MARKER"; tx=c; elif [[ "$*" == *pauseDepositMints* ]]; then [[ "${DEPOSIT_PAUSE_FAIL:-}" != true ]] || exit 1; touch "$DEPOSIT_PAUSED_MARKER"; tx=d; elif [[ "$*" == *pauseWithdrawals* ]]; then [[ "${WITHDRAWAL_PAUSE_FAIL:-}" != true ]] || exit 1; touch "$WITHDRAWAL_PAUSED_MARKER"; tx=f; else tx=b; fi; printf '{"status":"0x1","transactionHash":"0x%s"}\n' "$(printf "$tx%.0s" {1..64})";;
  'call 0x3333333333333333333333333333333333333333') case "$3" in bridgeSigner*) if [[ "${PROVIDER_DRIFT:-}" == all && "$*" == *one.example* ]]; then echo 0x9999999999999999999999999999999999999991; elif [[ "${PROVIDER_DRIFT:-}" == all && "$*" == *two.example* ]]; then echo 0x9999999999999999999999999999999999999992; elif [[ "${PROVIDER_DRIFT:-}" == all ]]; then echo 0x9999999999999999999999999999999999999993; else echo 0x1111111111111111111111111111111111111111; fi;; runtimeAdministrator*) echo 0x6666666666666666666666666666666666666666;; baseAdminTimelock*) echo 0x2222222222222222222222222222222222222222;; approvedTimelockRuntimeCodeHash*) [[ "${BRIDGE_APPROVED_HASH_DRIFT:-}" == true ]] && x=dd || x=cc; printf '0x%s\n' "$(printf "$x%.0s" {1..32})";; bsns*) echo 0x7777777777777777777777777777777777777777;; depositMintsPaused*) if [[ "${CONFIRM_FAIL:-}" == true && -e "$DEPOSIT_PAUSED_MARKER" ]]; then echo false; elif [[ -e "$DEPOSIT_PAUSED_MARKER" ]]; then echo true; elif [[ -e "$EXECUTED_MARKER" || "${BASE_PAUSED:-true}" != true ]]; then echo false; else echo true; fi;; withdrawalsPaused*) if [[ "${CONFIRM_FAIL:-}" == true && -e "$WITHDRAWAL_PAUSED_MARKER" ]]; then echo false; elif [[ -e "$WITHDRAWAL_PAUSED_MARKER" ]]; then echo true; elif [[ -e "$EXECUTED_MARKER" || "${BASE_PAUSED:-true}" != true ]]; then echo false; else echo true; fi;; esac;;
  'call 0x2222222222222222222222222222222222222222') case "$3" in getMinDelay*) echo 86400;; hasRole*) if [[ "${ROLE_DRIFT:-}" == true && "$4" != "0x$(printf '00%.0s' {1..32})" && "$5" != 0x0000000000000000000000000000000000000000 ]]; then echo false; elif [[ "$4" == "0x$(printf '00%.0s' {1..32})" && "$5" == 0x2222222222222222222222222222222222222222 ]]; then echo true; elif [[ "$4" == "0x$(printf '00%.0s' {1..32})" || "$5" == 0x0000000000000000000000000000000000000000 ]]; then echo false; else echo true; fi;; hashOperationBatch*) echo 0xbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb;; isOperationDone*) [[ -e "$EXECUTED_MARKER" ]] && echo true || echo false;; isOperationPending*|isOperationReady*) [[ -e "$EXECUTED_MARKER" || -e "$CANCELLED_MARKER" ]] && echo false || echo true;; esac;;
  'call 0x7777777777777777777777777777777777777777') case "$3" in name*) echo '"KINIC"';; symbol*) echo '"KINIC"';; decimals*) echo 8;; bridge*) echo 0x3333333333333333333333333333333333333333;; esac;;
  *) echo "unexpected cast call: $*" >&2; exit 1;;
esac
SH
cat >"$T/bin/icp" <<'SH'
#!/usr/bin/env bash
echo "icp $*" >>"$TRACE"
if [[ "$*" == *initialize_public_config* ]]; then if [[ "${INITIALIZE_PUBLIC_CONFIG_FAIL:-false}" == true ]]; then echo '{"Err":"DerivationUnavailable"}'; else echo '{"Ok":null}'; fi;
elif [[ "$*" == *get_public_config* ]]; then if [[ "${CANISTER_SIGNER_DRIFT:-false}" == true ]]; then signer_byte=34; else signer_byte=17; fi; signer="$signer_byte"; for _ in {2..20}; do signer="$signer,$signer_byte"; done; printf '{"base_chain_id":8453,"bridge_contract":[51,51,51,51,51,51,51,51,51,51,51,51,51,51,51,51,51,51,51,51],"expected_bridge_runtime_sha256":[110,52,11,156,255,179,122,152,156,165,68,230,187,120,10,44,120,144,29,63,179,55,56,118,133,17,163,6,23,175,160,29],"timelock_contract":[34,34,34,34,34,34,34,34,34,34,34,34,34,34,34,34,34,34,34,34],"deployment_instance_id":[17,17,17,17,17,17,17,17,17,17,17,17,17,17,17,17,17,17,17,17,17,17,17,17,17,17,17,17,17,17,17,17],"ledger_canister_id":"aaaaa-aa","index_canister_id":"aaaaa-aa","schema_version":30,"expected_bridge_signer":[%s],"governance_operator":[102,102,102,102,102,102,102,102,102,102,102,102,102,102,102,102,102,102,102,102],"evm_rpc_canister_id":"aaaaa-aa","rpc_provider_urls_sha256":"%s","deposit_rate_limit_window_seconds":1,"deposit_rate_limit_global":1,"deposit_rate_limit_per_principal":1,"notification_rate_limit_window_seconds":600,"notification_rate_limit_global":60,"settlement_rate_limit_window_seconds":1,"settlement_rate_limit_global":1,"settlement_rate_limit_per_principal":1,"settlement_rate_limit_per_record":1,"settlement_retry_interval_seconds":60,"governance_evm_fee":{"gas_limit_ceiling":"1","max_fee_per_gas_ceiling":"1","max_priority_fee_per_gas_ceiling":"1","l1_fee_per_transaction_ceiling_wei":"1","quote_validity_seconds":90,"gas_limit_multiplier_bps":13000,"base_fee_multiplier_bps":60000,"l1_fee_multiplier_bps":15000},"governance_replacement":{"max_replacements":3,"fee_bump_bps":1250},"governance_eth_floor_wei":"1","cycles_floor":"1","settlement_cycle_ceiling":"1","governance_principal":"aaaaa-aa","pause_principal":"2vxsx-fae","fee_recipient":{"owner":"aaaaa-aa","subaccount":[]}}\n' "$signer" "$RPC_DIGEST";
elif [[ "$*" == *get_bridge_status* ]]; then if [[ -e "$IC_RESUMED_MARKER" ]]; then paused=false; else paused="${CANISTER_PAUSED:-true}"; fi; printf '{"deposits_paused":%s,"reserve":{"sufficient":true}}\n' "$paused";
elif [[ "$*" == *icrc1_fee* ]]; then echo '100000';
elif [[ "$*" == *resume_new_deposits* ]]; then if [[ "${RESUME_FAIL:-}" == true ]]; then echo '{"Err":"StorageFailure"}'; exit 1; fi; touch "$IC_RESUMED_MARKER"; echo '{"Ok":null}';
elif [[ "$*" == *pause_new_deposits* ]]; then if [[ "${IC_PAUSE_FAIL:-}" == true ]]; then exit 1; fi; rm -f "$IC_RESUMED_MARKER"; echo '{"Ok":null}';
elif [[ "$*" == *'identity principal --identity production'* ]]; then echo 'aaaaa-aa';
elif [[ "$*" == *list_nervous_system_functions* ]]; then echo '{"functions":[{"id":1,"target_canister_id":"aaaaa-aa","target_method_name":"schedule_activation"}]}';
elif [[ "$*" == *manage_neuron* ]]; then echo '{"command":{"MakeProposal":{"proposal_id":[]}}}';
elif [[ "$*" == *'canister status bridge-canister -e production -i --identity'* ]]; then echo 'aaaaa-aa';
elif [[ "$*" == *'canister status'* ]]; then if [[ "${CONTROLLER_DRIFT:-false}" == true ]]; then controllers='["aaaaa-aa","2vxsx-fae"]'; else controllers='["aaaaa-aa"]'; fi; printf '{"controllers":%s,"module_hash":"6e340b9cffb37a989ca544e6bb780a2c78901d3fb33738768511a30617afa01d"}\n' "$controllers";
else echo '{}'; fi
SH
chmod +x "$T/bin/forge" "$T/bin/cast" "$T/bin/icp" "$T/bin/ci-local.sh"
export PATH="$T/bin:$PATH"
export PATH_PROOF_OVERRIDE_MARKER="$T/path-proof-override-used"
export EXECUTED_MARKER="$T/executed" CANCELLED_MARKER="$T/cancelled" IC_RESUMED_MARKER="$T/ic-resumed" DEPOSIT_PAUSED_MARKER="$T/deposit-paused" WITHDRAWAL_PAUSED_MARKER="$T/withdrawal-paused"
export TIMELOCK_DEPLOYED_MARKER="$T/timelock-deployed" BRIDGE_DEPLOYED_MARKER="$T/bridge-deployed"
export BRIDGE_TIMELOCK_CANCELLER_ADDRESS=0x5555555555555555555555555555555555555555
export BRIDGE_ICP_IDENTITY=production
export BRIDGE_CANONICAL_CONFIRM_TIMEOUT_SECONDS=1 BRIDGE_CANONICAL_CONFIRM_POLL_SECONDS=1
export BRIDGE_DEPLOYMENT_BINDING_FILE="$T/deployment-binding.json"
export BRIDGE_DEPLOY_GAS_LIMIT=10000000 BRIDGE_DEPLOY_MAX_FEE_PER_GAS=100 BRIDGE_DEPLOY_PRIORITY_FEE_PER_GAS=2
export RPC_DIGEST="$(python3 -c 'import hashlib;print(hashlib.sha256(b"[]").hexdigest())')"
export INDEPENDENT_RPC_DIGEST="$(python3 -c 'import hashlib,json;print(hashlib.sha256(json.dumps(["https://one.example","https://two.example","https://three.example"],separators=(",",":"),ensure_ascii=False).encode()).hexdigest())')"
cat >"$T/bundle/profile.json" <<'JSON'
{"chain_id":8453,"evm_rpc_canister_id":"aaaaa-aa","bridge_canister_id":"aaaaa-aa","ledger_canister_id":"aaaaa-aa","bridge_contract":"0x3333333333333333333333333333333333333333","bsns_contract":"0x7777777777777777777777777777777777777777","decimals":8,"expected_bridge_signer":"0x1111111111111111111111111111111111111111","governance_operator":"0x6666666666666666666666666666666666666666","pause_principal":"7jkta-eyaaa-aaaaq-aaarq-cai","timelock":{"address":"0x2222222222222222222222222222222222222222","runtime_code_hash":"0xcccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc","minimum_delay_seconds":86400,"proposer":"0x6666666666666666666666666666666666666666","executor":"0x6666666666666666666666666666666666666666","canceller":"0x6666666666666666666666666666666666666666"},"root_canister_id":"aaaaa-aa","bridge_runtime_bytecode_sha256":"6e340b9cffb37a989ca544e6bb780a2c78901d3fb33738768511a30617afa01d","bsns_runtime_bytecode_sha256":"6e340b9cffb37a989ca544e6bb780a2c78901d3fb33738768511a30617afa01d","bridge_canister_wasm_sha256":"6e340b9cffb37a989ca544e6bb780a2c78901d3fb33738768511a30617afa01d","ic_host":"https://icp-api.io","base_rpc_url":"https://rpc.example","deployment_block":0,"parameters":{"ledger_fee":100000,"service_fee":50000000},"rpc_providers":[{"url":"https://one.example"},{"url":"https://two.example"},{"url":"https://three.example"}]}
JSON
cat >"$T/constructors.json" <<'JSON'
{"timelock":["86400","[0x6666666666666666666666666666666666666666]","[0x6666666666666666666666666666666666666666]","[0x6666666666666666666666666666666666666666]"],"bridge":["KINIC","KINIC","8","0x1111111111111111111111111111111111111111","0x6666666666666666666666666666666666666666","0x2222222222222222222222222222222222222222","0xcccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc","1","2","3600","2","1"]}
JSON
cat >"$T/init.json" <<'JSON'
{"settlement_rate_limit_global":1,"settlement_rate_limit_per_principal":1,"settlement_cycle_ceiling":"1","settlement_rate_limit_per_record":1,"settlement_retry_interval_seconds":60,"deposit_rate_limit_window_seconds":1,"notification_rate_limit_window_seconds":600,"notification_rate_limit_global":60,"ecdsa_key_name":"key_1","base_chain_id":8453,"bridge_contract_hex":"3333333333333333333333333333333333333333","expected_bridge_runtime_sha256_hex":"4444444444444444444444444444444444444444444444444444444444444444","timelock_contract_hex":"2222222222222222222222222222222222222222","deployment_instance_id_hex":"1111111111111111111111111111111111111111111111111111111111111111","governance_evm_fee":{"gas_limit_ceiling":"1","max_fee_per_gas_ceiling":"1","max_priority_fee_per_gas_ceiling":"1","l1_fee_per_transaction_ceiling_wei":"1","quote_validity_seconds":90,"gas_limit_multiplier_bps":13000,"base_fee_multiplier_bps":60000,"l1_fee_multiplier_bps":15000},"governance_replacement":{"max_replacements":3,"fee_bump_bps":1250},"fee_recipient":{"owner":"aaaaa-aa","subaccount_hex":""},"settlement_rate_limit_window_seconds":1,"ecdsa_derivation_path_utf8":["bridge-operator"],"governance_ecdsa_derivation_path_utf8":["governance-operator"],"evm_rpc_canister_id":"aaaaa-aa","deposit_rate_limit_per_principal":1,"pause_principal":"2vxsx-fae","governance_eth_floor_wei":"1","custom_evm_rpc_urls":[],"deposit_rate_limit_global":1,"governance_principal":"aaaaa-aa","index_canister_id":"aaaaa-aa","ledger_canister_id":"aaaaa-aa","cycles_floor":"1"}
JSON
mkdir -p "$T/rendered"
cp "$T/init.json" "$T/rendered/canister-init.json"
cp "$T/constructors.json" "$T/rendered/contract-constructor-args.json"
printf '{}\n' >"$T/rendered/ui-runtime-profile.json"
printf '{}\n' >"$T/rendered/release-inputs-manifest.json"
printf '{"bridge":["MALICIOUS"],"timelock":[]}\n' >"$T/malicious-constructors.json"
printf '{"malicious":true}\n' >"$T/malicious-init.json"
export RENDER_SOURCE="$T/rendered"
printf wasm >"$T/bundle/bridge-canister.wasm"
SOURCE_REVISION="$(git -C "$DRIVER_ROOT" rev-parse HEAD)"; SOURCE_TREE="$(git -C "$DRIVER_ROOT" archive HEAD | shasum -a 256 | awk '{print $1}')"
printf '{"release_id":"release-test","source_revision":"%s","source_tree_sha256":"%s"}\n' "$SOURCE_REVISION" "$SOURCE_TREE" >"$T/bundle/release-manifest.json"
printf '{"final_controllers":["aaaaa-aa"]}\n' >"$T/bundle/controller-handover.json"
printf '{"gate_a_manifest_sha256":"%s","bridge_deployment_transaction_hash":"0x%s","bridge_deployment_block_number":1,"bridge_deployment_block_hash":"0x%s","timelock_deployment_transaction_hash":"0x%s","timelock_deployment_block_number":1,"timelock_deployment_block_hash":"0x%s"}\n' "$(printf 'a%.0s' {1..64})" "$(printf 'a%.0s' {1..64})" "$(printf 'b%.0s' {1..64})" "$(printf 'b%.0s' {1..64})" "$(printf 'c%.0s' {1..64})" >"$T/bundle/gate-a-receipt.json"
printf '{"base_chain_id":8453,"rpc_provider_urls_sha256":"%s","base_actions":[{"kind":"PauseDepositMints","transaction_hash":"deposit-action","block_number":100,"block_hash":"0x%s","target":"0x3333333333333333333333333333333333333333","calldata_hex":"0x1111"},{"kind":"PauseWithdrawals","transaction_hash":"withdrawal-action","block_number":100,"block_hash":"0x%s","target":"0x3333333333333333333333333333333333333333","calldata_hex":"0x2222"},{"kind":"CancelTimelock","transaction_hash":"cancel-action","block_number":100,"block_hash":"0x%s","target":"0x2222222222222222222222222222222222222222","calldata_hex":"0x3333"}]}\n' "$INDEPENDENT_RPC_DIGEST" "$(printf 'a%.0s' {1..64})" "$(printf 'a%.0s' {1..64})" "$(printf 'a%.0s' {1..64})" >"$T/bundle/monitor-drill.json"
: >"$TRACE"
BRIDGE_GATE_A_RPC_URL_1=https://one.example BRIDGE_GATE_A_RPC_URL_2=https://two.example BRIDGE_GATE_A_RPC_URL_3=https://three.example \
  "$DRIVER_ROOT/scripts/production-live-preflight.sh" verify-gate-a "$T/bundle" >/dev/null
[[ "$(grep -c '^cast block finalized' "$TRACE")" -eq 3 ]]
[[ "$(grep -c '^cast rpc ' "$TRACE")" -eq 9 ]]
! grep -Eq '^cast block [0-9]+' "$TRACE"
if CANONICAL_PROBE_MALFORMED=true \
  BRIDGE_GATE_A_RPC_URL_1=https://one.example BRIDGE_GATE_A_RPC_URL_2=https://two.example BRIDGE_GATE_A_RPC_URL_3=https://three.example \
  "$DRIVER_ROOT/scripts/production-live-preflight.sh" verify-gate-a "$T/bundle" >/dev/null 2>&1; then
  echo "Gate A accepted malformed canonical probes" >&2
  exit 1
fi
if BRIDGE_GATE_A_MANIFEST_SHA256="$(printf 'b%.0s' {1..64})" BRIDGE_RELEASE_BUNDLE="$T/bundle" BRIDGE_CANISTER_INIT_FILE="$T/init.json" BRIDGE_CONSTRUCTOR_ARGS_FILE="$T/constructors.json" BRIDGE_DEPLOYER_ADDRESS=0x4444444444444444444444444444444444444444 BRIDGE_ICP_IDENTITY=production "$DRIVER_ROOT/scripts/production-deploy-driver.sh" >/dev/null 2>&1; then
  echo "deploy driver accepted a forged Gate A hash" >&2; exit 1
fi
if PROOF_GATE_FAIL=true BRIDGE_GATE_A_MANIFEST_SHA256="$(printf 'a%.0s' {1..64})" BRIDGE_RELEASE_BUNDLE="$T/bundle" BRIDGE_CANISTER_INIT_FILE="$T/init.json" BRIDGE_CONSTRUCTOR_ARGS_FILE="$T/constructors.json" BRIDGE_DEPLOYER_ADDRESS=0x4444444444444444444444444444444444444444 BRIDGE_ICP_IDENTITY=production "$DRIVER_ROOT/scripts/production-deploy-driver.sh" >/dev/null 2>&1; then
  echo "deploy driver accepted a failed proof gate" >&2; exit 1
fi
[[ ! -e "$TIMELOCK_DEPLOYED_MARKER" && ! -e "$BRIDGE_DEPLOYED_MARKER" ]]
if REPRODUCIBLE_BUILD_FAIL=true BRIDGE_GATE_A_MANIFEST_SHA256="$(printf 'a%.0s' {1..64})" BRIDGE_RELEASE_BUNDLE="$T/bundle" BRIDGE_CANISTER_INIT_FILE="$T/init.json" BRIDGE_CONSTRUCTOR_ARGS_FILE="$T/constructors.json" BRIDGE_DEPLOYER_ADDRESS=0x4444444444444444444444444444444444444444 BRIDGE_ICP_IDENTITY=production "$DRIVER_ROOT/scripts/production-deploy-driver.sh" >/dev/null 2>&1; then
  echo "deploy driver accepted a failed reproducible artifact build" >&2; exit 1
fi
[[ ! -e "$TIMELOCK_DEPLOYED_MARKER" && ! -e "$BRIDGE_DEPLOYED_MARKER" ]]
if PROOF_GATE_MUTATE_SOURCE=true BRIDGE_GATE_A_MANIFEST_SHA256="$(printf 'a%.0s' {1..64})" BRIDGE_RELEASE_BUNDLE="$T/bundle" BRIDGE_CANISTER_INIT_FILE="$T/init.json" BRIDGE_CONSTRUCTOR_ARGS_FILE="$T/constructors.json" BRIDGE_DEPLOYER_ADDRESS=0x4444444444444444444444444444444444444444 BRIDGE_ICP_IDENTITY=production "$DRIVER_ROOT/scripts/production-deploy-driver.sh" >/dev/null 2>&1; then
  echo "deploy driver accepted source mutation during proofs" >&2; exit 1
fi
git -C "$DRIVER_ROOT" restore src/main.rs
[[ ! -e "$TIMELOCK_DEPLOYED_MARKER" && ! -e "$BRIDGE_DEPLOYED_MARKER" ]]
BRIDGE_GATE_A_MANIFEST_SHA256="$(printf 'a%.0s' {1..64})" BRIDGE_RELEASE_BUNDLE="$T/bundle" BRIDGE_CANISTER_INIT_FILE="$T/malicious-init.json" BRIDGE_CONSTRUCTOR_ARGS_FILE="$T/malicious-constructors.json" BRIDGE_DEPLOYER_ADDRESS=0x4444444444444444444444444444444444444444 BRIDGE_ICP_IDENTITY=production "$DRIVER_ROOT/scripts/production-deploy-driver.sh"
python3 - "$TRACE" <<'PY'
import sys
s=open(sys.argv[1]).read(); required=['proofs proofs','rebuild ','initialize_public_config','get_public_config','get_bridge_status','BridgeTimelockController','src/Bridge.sol','cast call']; pos=-1
for x in required:
  pos=s.find(x,pos+1); assert pos>=0,(x,s)
assert '--ledger' in s and 'unpause' not in s
assert 'MALICIOUS' not in s
PY
[[ ! -e "$T/path-proof-override-used" ]]
if INITIALIZE_PUBLIC_CONFIG_FAIL=true BRIDGE_GATE_A_MANIFEST_SHA256="$(printf 'a%.0s' {1..64})" BRIDGE_RELEASE_BUNDLE="$T/bundle" BRIDGE_DEPLOYER_ADDRESS=0x4444444444444444444444444444444444444444 BRIDGE_ICP_IDENTITY=production "$DRIVER_ROOT/scripts/production-deploy-driver.sh" >/dev/null 2>&1; then
  echo "deploy driver accepted failed public configuration initialization" >&2; exit 1
fi
if TIMELOCK_CODE_DRIFT=true BRIDGE_GATE_A_MANIFEST_SHA256="$(printf 'a%.0s' {1..64})" BRIDGE_RELEASE_BUNDLE="$T/bundle" BRIDGE_DEPLOYER_ADDRESS=0x4444444444444444444444444444444444444444 BRIDGE_ICP_IDENTITY=production "$DRIVER_ROOT/scripts/production-deploy-driver.sh" >/dev/null 2>&1; then
  echo "deploy driver accepted a deployed Timelock runtime code hash mismatch" >&2; exit 1
fi
if CANISTER_PAUSED=false BRIDGE_GATE_A_MANIFEST_SHA256="$(printf 'a%.0s' {1..64})" BRIDGE_RELEASE_BUNDLE="$T/bundle" BRIDGE_CANISTER_INIT_FILE="$T/init.json" BRIDGE_CONSTRUCTOR_ARGS_FILE="$T/constructors.json" BRIDGE_DEPLOYER_ADDRESS=0x4444444444444444444444444444444444444444 BRIDGE_ICP_IDENTITY=production "$DRIVER_ROOT/scripts/production-deploy-driver.sh" >/dev/null 2>&1; then
  echo "deploy driver accepted deposits_paused=false" >&2; exit 1
fi
cat >"$T/bundle/signer-snapshot.json" <<'JSON'
{}
JSON
: >"$TRACE"; BRIDGE_ICP_IDENTITY=observer "$DRIVER_ROOT/scripts/production-live-preflight.sh" capture "$T/bundle" "$T/snapshot.json"
if grep -q sign_chain_key_challenge "$TRACE"; then
  echo "live preflight called the retired chain-key challenge endpoint" >&2; exit 1
fi
cp "$T/snapshot.json" "$T/bundle/signer-snapshot.json"
for isolated in chain_failure wrong_chain safe_failure eip1898_unsupported; do
  case "$isolated" in
    chain_failure) args=(PROVIDER_CHAIN_FAILURES=1);;
    wrong_chain) args=(PROVIDER_WRONG_CHAINS=1);;
    safe_failure) args=(PROVIDER_SAFE_FAILURES=1);;
    eip1898_unsupported) args=(PROVIDER_EIP1898_FAILURES=1);;
  esac
  env "${args[@]}" BRIDGE_ICP_IDENTITY=production "$DRIVER_ROOT/scripts/production-live-preflight.sh" capture "$T/bundle" "$T/isolated-$isolated.json"
done
for insufficient in chain_failure wrong_chain safe_failure eip1898_unsupported; do
  case "$insufficient" in
    chain_failure) args=(PROVIDER_CHAIN_FAILURES=2);;
    wrong_chain) args=(PROVIDER_WRONG_CHAINS=2);;
    safe_failure) args=(PROVIDER_SAFE_FAILURES=2);;
    eip1898_unsupported) args=(PROVIDER_EIP1898_FAILURES=2);;
  esac
  if env "${args[@]}" BRIDGE_ICP_IDENTITY=production "$DRIVER_ROOT/scripts/production-live-preflight.sh" capture "$T/bundle" "$T/insufficient-$insufficient.json" >/dev/null 2>&1; then
    echo "live preflight accepted fewer than two usable providers: $insufficient" >&2; exit 1
  fi
done
: >"$TRACE"
SNS_IDENTITY_FIXTURE=production
SNS_NEURON_SUBACCOUNT_FIXTURE="$(printf '11%.0s' {1..32})"
SNS_PROPOSER_PRINCIPAL_FIXTURE=aaaaa-aa
ACTIVATION_SUBMISSION_FIXTURE="$T/activation-submission.json"
if BRIDGE_GATE_B_MANIFEST_SHA256="$(printf 'b%.0s' {1..64})" \
  BRIDGE_RELEASE_BUNDLE="$T/bundle" \
  BRIDGE_ACTIVATION_PHASE=schedule \
  BRIDGE_ACTIVATION_SUBMISSION_OUT="$ACTIVATION_SUBMISSION_FIXTURE" \
  BRIDGE_SNS_IDENTITY="$SNS_IDENTITY_FIXTURE" \
  BRIDGE_SNS_NEURON_SUBACCOUNT="$SNS_NEURON_SUBACCOUNT_FIXTURE" \
  BRIDGE_SNS_PROPOSER_PRINCIPAL="$SNS_PROPOSER_PRINCIPAL_FIXTURE" \
  "$DRIVER_ROOT/scripts/production-activate-driver.sh"; then
  echo "activation driver reported success without submitting an SNS proposal" >&2
  exit 1
fi
grep -q '^icp identity principal --identity production$' "$TRACE"
grep -q 'list_nervous_system_functions' "$TRACE"
grep -q 'manage_neuron' "$TRACE"
[[ -f "$ACTIVATION_SUBMISSION_FIXTURE" && ! -s "$ACTIVATION_SUBMISSION_FIXTURE" ]]
! grep -q '^cast send' "$TRACE"
! grep -q resume_new_deposits "$TRACE"
: >"$TRACE"; "$DRIVER_ROOT/scripts/production-live-preflight.sh" verify "$T/bundle"
[[ "$(grep -c '^cast chain-id' "$TRACE")" -eq 3 ]]
! grep -Eq '^cast block [0-9]+' "$TRACE"
python3 - "$TRACE" <<'PY'
import sys
count=0
for line in open(sys.argv[1]):
  if line.startswith('cast rpc ') and (' eth_call ' in line or ' eth_getCode ' in line):
    count+=1
    assert '{"blockHash":"0x' in line and '"requireCanonical":true}' in line,line
assert count>0
PY
for drift in base canister signer controller roles role_events role_event_hash deployment providers timelock_code approved_hash mid_read_reorg canonical_probe canonical_probe_block; do
  case "$drift" in
    base) args=(BASE_PAUSED=false);;
    canister) args=(CANISTER_PAUSED=false);;
    signer) args=(CANISTER_SIGNER_DRIFT=true);;
    controller) args=(CONTROLLER_DRIFT=true);;
    roles) args=(ROLE_DRIFT=true);;
    role_events) args=(ROLE_EVENT_DRIFT=true);;
    role_event_hash) args=(ROLE_EVENT_HASH_DRIFT=true);;
    deployment) args=(DEPLOYMENT_RECEIPT_DRIFT=true);;
    providers) args=(PROVIDER_DRIFT=all);;
    timelock_code) args=(TIMELOCK_CODE_DRIFT=true);;
    approved_hash) args=(BRIDGE_APPROVED_HASH_DRIFT=true);;
    mid_read_reorg) args=(MID_READ_REORG=all);;
    canonical_probe) args=(CANONICAL_PROBE_MALFORMED=true);;
    canonical_probe_block) args=(CANONICAL_PROBE_BLOCK_MISMATCH=true);;
  esac
  if env "${args[@]}" "$DRIVER_ROOT/scripts/production-live-preflight.sh" capture "$T/bundle" "$T/rejected-$drift.json" >/dev/null 2>&1; then
    echo "live preflight accepted $drift drift" >&2; exit 1
  fi
done
for drift in stale_head signed_orphan latest_quorum; do
  case "$drift" in
    stale_head) args=(LATEST_HEIGHT=99);;
    signed_orphan) args=(SIGNED_BLOCK_DRIFT=all);;
    latest_quorum) args=(LATEST_BLOCK_DRIFT=all);;
  esac
  if env "${args[@]}" "$DRIVER_ROOT/scripts/production-live-preflight.sh" verify "$T/bundle" >/dev/null 2>&1; then
    echo "live preflight accepted $drift" >&2; exit 1
  fi
done
