#!/usr/bin/env bash
set -euo pipefail

ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
TEST_TMP_ROOT="$(mktemp -d "${TMPDIR:-/tmp}/bridge-production-release.XXXXXX")"
trap 'rm -rf "$TEST_TMP_ROOT"' EXIT

mkdir -p "$TEST_TMP_ROOT/bundle-a" "$TEST_TMP_ROOT/bundle-b" "$TEST_TMP_ROOT/source/scripts" "$TEST_TMP_ROOT/source/src" "$TEST_TMP_ROOT/release-inputs"
git -C "$TEST_TMP_ROOT/source" init -q
git -C "$TEST_TMP_ROOT/source" config user.email bridge-test@example.invalid
git -C "$TEST_TMP_ROOT/source" config user.name bridge-test
printf 'release source\n' >"$TEST_TMP_ROOT/source/source.txt"
printf '/target\n' >"$TEST_TMP_ROOT/source/.gitignore"
cat >"$TEST_TMP_ROOT/source/Cargo.toml" <<'TOML'
[package]
name = "bridge-profile"
version = "0.0.0"
edition = "2021"
TOML
cat >"$TEST_TMP_ROOT/source/Cargo.lock" <<'LOCK'
# This file is automatically @generated by Cargo.
version = 4

[[package]]
name = "bridge-profile"
version = "0.0.0"
LOCK
cat >"$TEST_TMP_ROOT/source/src/main.rs" <<'RS'
use std::{env,fs,path::Path};
fn copy_dir(from:&Path,to:&Path){fs::create_dir_all(to).unwrap();for e in fs::read_dir(from).unwrap(){let e=e.unwrap();let d=to.join(e.file_name());if e.path().is_dir(){copy_dir(&e.path(),&d)}else{fs::copy(e.path(),d).unwrap();}}}
fn main(){let a:Vec<String>=env::args().skip(1).collect();fs::OpenOptions::new().create(true).append(true).open(env::var("GATE_CALLS").unwrap()).and_then(|mut f|{use std::io::Write;writeln!(f,"{}",a.join(" "))}).unwrap();if a[0].starts_with("render-"){copy_dir(Path::new(&env::var("RENDER_SOURCE").unwrap()),Path::new(&a[2]));return}println!("gate=pass manifest_sha256={:064}",1);if env::var("GATE_RESULT").as_deref()==Ok("fail"){std::process::exit(1)}}
RS
printf '%s\n' '#!/usr/bin/env bash' 'touch "$ACTION_MARKER"' >"$TEST_TMP_ROOT/source/scripts/production-deploy-driver.sh"
printf '%s\n' '#!/usr/bin/env bash' 'touch "$ACTION_MARKER"' >"$TEST_TMP_ROOT/source/scripts/production-activate-driver.sh"
printf '%s\n' '#!/usr/bin/env bash' 'exit 0' >"$TEST_TMP_ROOT/source/scripts/production-live-preflight.sh"
cp "$ROOT/scripts/production-release.sh" "$TEST_TMP_ROOT/source/scripts/production-release.sh"
chmod +x "$TEST_TMP_ROOT/source/scripts/production-deploy-driver.sh" "$TEST_TMP_ROOT/source/scripts/production-activate-driver.sh" "$TEST_TMP_ROOT/source/scripts/production-live-preflight.sh" "$TEST_TMP_ROOT/source/scripts/production-release.sh"
git -C "$TEST_TMP_ROOT/source" add source.txt .gitignore Cargo.toml Cargo.lock src/main.rs
git -C "$TEST_TMP_ROOT/source" add scripts/production-deploy-driver.sh scripts/production-activate-driver.sh scripts/production-live-preflight.sh scripts/production-release.sh
git -C "$TEST_TMP_ROOT/source" commit -qm 'test source'
printf '%s\n' '#!/usr/bin/env bash' 'touch "$PROFILE_OVERRIDE_MARKER"' 'exit 0' >"$TEST_TMP_ROOT/malicious-profile"
chmod +x "$TEST_TMP_ROOT/malicious-profile"
SOURCE_REVISION="$(git -C "$TEST_TMP_ROOT/source" rev-parse HEAD)"
SOURCE_TREE_SHA256="$(git -C "$TEST_TMP_ROOT/source" archive HEAD | shasum -a 256 | awk '{print $1}')"
PROFILE_SHA256="$(printf profile | shasum -a 256 | awk '{print $1}')"
WASM_SHA256="$(printf wasm | shasum -a 256 | awk '{print $1}')"
RUNTIME_SHA256="$(printf runtime | shasum -a 256 | awk '{print $1}')"
printf profile >"$TEST_TMP_ROOT/bundle-a/profile.json"
printf profile >"$TEST_TMP_ROOT/bundle-b/profile.json"
printf '{}\n' >"$TEST_TMP_ROOT/release-inputs/canister-init.json"
printf '{}\n' >"$TEST_TMP_ROOT/release-inputs/contract-constructor-args.json"
printf '{}\n' >"$TEST_TMP_ROOT/release-inputs/ui-runtime-profile.json"
python3 -c 'import json,sys; json.dump({"profile_file_sha256":sys.argv[2]},open(sys.argv[1],"w"),sort_keys=True,separators=(",",":")); open(sys.argv[1],"a").write("\n")' \
  "$TEST_TMP_ROOT/release-inputs/release-inputs-manifest.json" "$PROFILE_SHA256"
python3 -c '
import json, sys
json.dump({"release_id": "release-test", "source_revision": sys.argv[3], "source_tree_sha256": sys.argv[4], "artifacts": [{"path": "profile.json", "sha256": sys.argv[5]}, {"path": "bridge-canister.wasm", "sha256": sys.argv[6]}, {"path": "bridge-runtime.bin", "sha256": sys.argv[7]}], **({"parent_gate_a_manifest_sha256": sys.argv[2]} if sys.argv[2] != "-" else {})}, open(sys.argv[1], "w"))
' "$TEST_TMP_ROOT/bundle-a/release-manifest.json" - "$SOURCE_REVISION" "$SOURCE_TREE_SHA256" "$PROFILE_SHA256" "$WASM_SHA256" "$RUNTIME_SHA256"
python3 -c '
import json, sys
json.dump({"release_id": "release-test", "source_revision": sys.argv[3], "source_tree_sha256": sys.argv[4], "artifacts": [{"path": "profile.json", "sha256": sys.argv[5]}, {"path": "bridge-canister.wasm", "sha256": sys.argv[6]}, {"path": "bridge-runtime.bin", "sha256": sys.argv[7]}], "parent_gate_a_manifest_sha256": sys.argv[2]}, open(sys.argv[1], "w"))
' "$TEST_TMP_ROOT/bundle-b/release-manifest.json" "$(printf '%064d' 1)" "$SOURCE_REVISION" "$SOURCE_TREE_SHA256" "$PROFILE_SHA256" "$WASM_SHA256" "$RUNTIME_SHA256"

write_gate() {
  local result="$1"
  if [[ "$result" == 0 ]]; then GATE_RESULT=pass; else GATE_RESULT=fail; fi
}

run_release() {
  GATE_CALLS="$TEST_TMP_ROOT/gate-calls" \
    RENDER_SOURCE="$TEST_TMP_ROOT/release-inputs" \
    BRIDGE_SOURCE_ROOT="$TEST_TMP_ROOT/ignored-source-override" \
    BRIDGE_PROFILE_BIN="$TEST_TMP_ROOT/malicious-profile" \
    PROFILE_OVERRIDE_MARKER="$TEST_TMP_ROOT/profile-override-used" \
    GATE_RESULT="$GATE_RESULT" \
    "$TEST_TMP_ROOT/source/scripts/production-release.sh" "$@"
}

expect_rejected() {
  if run_release "$@" >/dev/null 2>&1; then
    echo "production release command was unexpectedly accepted: $*" >&2
    exit 1
  fi
}

write_gate 1
expect_rejected deploy --bundle "$TEST_TMP_ROOT/bundle-a" --release-inputs "$TEST_TMP_ROOT/release-inputs" --receipt "$TEST_TMP_ROOT/receipt.json" -- "$TEST_TMP_ROOT/source/scripts/production-deploy-driver.sh"
[[ ! -e "$TEST_TMP_ROOT/deployed" ]]

write_gate 0
expect_rejected deploy --bundle "$TEST_TMP_ROOT/bundle-a" --release-inputs "$TEST_TMP_ROOT/release-inputs" --receipt "$TEST_TMP_ROOT/receipt.json" -- touch extra-argument
expect_rejected activate --bundle "$TEST_TMP_ROOT/bundle-b" --release-inputs "$TEST_TMP_ROOT/release-inputs" --receipt "$TEST_TMP_ROOT/receipt.json" -- "$TEST_TMP_ROOT/source/scripts/production-activate-driver.sh"
[[ ! -e "$TEST_TMP_ROOT/activated" ]]

ACTION_MARKER="$TEST_TMP_ROOT/deployed" run_release deploy --bundle "$TEST_TMP_ROOT/bundle-a" --release-inputs "$TEST_TMP_ROOT/release-inputs" --receipt "$TEST_TMP_ROOT/receipt.json" -- "$TEST_TMP_ROOT/source/scripts/production-deploy-driver.sh"
[[ -e "$TEST_TMP_ROOT/deployed" ]]
[[ -s "$TEST_TMP_ROOT/receipt.json" ]]
cp "$TEST_TMP_ROOT/receipt.json" "$TEST_TMP_ROOT/bundle-b/gate-a-receipt.json"
rg -q '^validate-bundle --offline ' "$TEST_TMP_ROOT/gate-calls"

write_gate 1
expect_rejected activate --bundle "$TEST_TMP_ROOT/bundle-b" --receipt "$TEST_TMP_ROOT/receipt.json" \
  --release-inputs "$TEST_TMP_ROOT/release-inputs" --confirm-asset-acceptance UNPAUSE_PRODUCTION_ASSET_ACCEPTANCE -- "$TEST_TMP_ROOT/source/scripts/production-activate-driver.sh"
[[ ! -e "$TEST_TMP_ROOT/activated" ]]

write_gate 0
expect_rejected activate --bundle "$TEST_TMP_ROOT/bundle-b" --receipt "$TEST_TMP_ROOT/receipt.json" \
  --live-preflight /bin/true --release-inputs "$TEST_TMP_ROOT/release-inputs" \
  --confirm-asset-acceptance UNPAUSE_PRODUCTION_ASSET_ACCEPTANCE -- "$TEST_TMP_ROOT/source/scripts/production-activate-driver.sh"
ACTION_MARKER="$TEST_TMP_ROOT/activated" run_release activate --bundle "$TEST_TMP_ROOT/bundle-b" --receipt "$TEST_TMP_ROOT/receipt.json" \
  --release-inputs "$TEST_TMP_ROOT/release-inputs" --confirm-asset-acceptance UNPAUSE_PRODUCTION_ASSET_ACCEPTANCE -- "$TEST_TMP_ROOT/source/scripts/production-activate-driver.sh"
[[ -e "$TEST_TMP_ROOT/activated" ]]
rg -q '^verify-live ' "$TEST_TMP_ROOT/gate-calls"
[[ ! -e "$TEST_TMP_ROOT/profile-override-used" ]]
