#!/usr/bin/env bash
set -euo pipefail

ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
TEST_TMP_ROOT="$(mktemp -d "${TMPDIR:-/tmp}/bridge-production-release.XXXXXX")"
trap 'rm -rf "$TEST_TMP_ROOT"' EXIT

mkdir -p "$TEST_TMP_ROOT/bundle-a" "$TEST_TMP_ROOT/bundle-b" "$TEST_TMP_ROOT/source/scripts" "$TEST_TMP_ROOT/source/src" "$TEST_TMP_ROOT/source/ui/scripts" "$TEST_TMP_ROOT/release-inputs" "$TEST_TMP_ROOT/release-scratch"
git -C "$TEST_TMP_ROOT/source" init -q
git -C "$TEST_TMP_ROOT/source" config user.email bridge-test@example.invalid
git -C "$TEST_TMP_ROOT/source" config user.name bridge-test
printf 'release source\n' >"$TEST_TMP_ROOT/source/source.txt"
printf '/target\n' >"$TEST_TMP_ROOT/source/.gitignore"
cat >"$TEST_TMP_ROOT/source/Cargo.toml" <<'TOML'
[package]
name = "bridge-profile"
version = "0.0.0"
edition = "2021"
TOML
cat >"$TEST_TMP_ROOT/source/Cargo.lock" <<'LOCK'
# This file is automatically @generated by Cargo.
version = 4

[[package]]
name = "bridge-profile"
version = "0.0.0"
LOCK
cat >"$TEST_TMP_ROOT/source/src/main.rs" <<'RS'
use std::{env,fs,path::Path};
fn copy_dir(from:&Path,to:&Path){fs::create_dir_all(to).unwrap();for e in fs::read_dir(from).unwrap(){let e=e.unwrap();let d=to.join(e.file_name());if e.path().is_dir(){copy_dir(&e.path(),&d)}else{fs::copy(e.path(),d).unwrap();}}}
fn main(){let a:Vec<String>=env::args().skip(1).collect();fs::OpenOptions::new().create(true).append(true).open(env::var("GATE_CALLS").unwrap()).and_then(|mut f|{use std::io::Write;writeln!(f,"{}",a.join(" "))}).unwrap();if a[0].starts_with("render-"){copy_dir(Path::new(&env::var("RENDER_SOURCE").unwrap()),Path::new(&a[2]));return}if a[0]=="validate"{println!("{:064}",2);return}println!("gate=pass manifest_sha256={:064}",1);if env::var("GATE_RESULT").as_deref()==Ok("fail"){std::process::exit(1)}}
RS
printf '%s\n' '#!/usr/bin/env bash' 'touch "$ACTION_MARKER"' 'printf '\''{"bridge":{"transaction_hash":"0xaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa","block_number":1,"block_hash":"0xcccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc"},"timelock":{"transaction_hash":"0xbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb","block_number":1,"block_hash":"0xdddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddd"}}\n'\'' >"$BRIDGE_DEPLOYMENT_BINDING_FILE"' >"$TEST_TMP_ROOT/source/scripts/production-deploy-driver.sh"
printf '%s\n' '#!/usr/bin/env bash' 'touch "$ACTION_MARKER"' '[[ "${ACTION_FAIL:-0}" == 0 ]] || exit 23' >"$TEST_TMP_ROOT/source/scripts/production-activate-driver.sh"
printf '%s\n' '#!/usr/bin/env bash' 'exit 0' >"$TEST_TMP_ROOT/source/scripts/production-live-preflight.sh"
printf '%s\n' 'process.exit(0)' >"$TEST_TMP_ROOT/source/ui/scripts/production-assets.mjs"
cp "$ROOT/scripts/production-release.sh" "$ROOT/scripts/production-validation.sh" "$TEST_TMP_ROOT/source/scripts/"
chmod +x "$TEST_TMP_ROOT/source/scripts/production-deploy-driver.sh" "$TEST_TMP_ROOT/source/scripts/production-activate-driver.sh" "$TEST_TMP_ROOT/source/scripts/production-live-preflight.sh" "$TEST_TMP_ROOT/source/scripts/production-release.sh"
git -C "$TEST_TMP_ROOT/source" add source.txt .gitignore Cargo.toml Cargo.lock src/main.rs
git -C "$TEST_TMP_ROOT/source" add scripts/production-deploy-driver.sh scripts/production-activate-driver.sh scripts/production-live-preflight.sh scripts/production-release.sh scripts/production-validation.sh
git -C "$TEST_TMP_ROOT/source" add ui/scripts/production-assets.mjs
git -C "$TEST_TMP_ROOT/source" commit -qm 'test source'
printf '%s\n' '#!/usr/bin/env bash' 'touch "$PROFILE_OVERRIDE_MARKER"' 'exit 0' >"$TEST_TMP_ROOT/malicious-profile"
chmod +x "$TEST_TMP_ROOT/malicious-profile"
SOURCE_REVISION="$(git -C "$TEST_TMP_ROOT/source" rev-parse HEAD)"
SOURCE_TREE_SHA256="$(git -C "$TEST_TMP_ROOT/source" archive HEAD | shasum -a 256 | awk '{print $1}')"
PROFILE_CONTENT='{"deployment_block":0,"name":"planned-profile"}'
PROFILE_SHA256="$(printf '%s' "$PROFILE_CONTENT" | shasum -a 256 | awk '{print $1}')"
WASM_SHA256="$(printf wasm | shasum -a 256 | awk '{print $1}')"
RUNTIME_SHA256="$(printf runtime | shasum -a 256 | awk '{print $1}')"
printf '%s' "$PROFILE_CONTENT" >"$TEST_TMP_ROOT/bundle-a/profile.json"
printf '%s' "$PROFILE_CONTENT" >"$TEST_TMP_ROOT/bundle-b/profile.json"
printf wasm >"$TEST_TMP_ROOT/bundle-a/bridge-canister.wasm"
printf runtime >"$TEST_TMP_ROOT/bundle-a/bridge-runtime.bin"
printf wasm >"$TEST_TMP_ROOT/bundle-b/bridge-canister.wasm"
printf runtime >"$TEST_TMP_ROOT/bundle-b/bridge-runtime.bin"
printf '{}\n' >"$TEST_TMP_ROOT/release-inputs/canister-init.json"
printf '{}\n' >"$TEST_TMP_ROOT/release-inputs/contract-constructor-args.json"
printf '{}\n' >"$TEST_TMP_ROOT/release-inputs/ui-runtime-profile.json"
python3 -c 'import json,sys; json.dump({"profile_file_sha256":sys.argv[2]},open(sys.argv[1],"w"),sort_keys=True,separators=(",",":")); open(sys.argv[1],"a").write("\n")' \
  "$TEST_TMP_ROOT/release-inputs/release-inputs-manifest.json" "$PROFILE_SHA256"
python3 -c '
import json, sys
json.dump({"release_id": "release-test", "source_revision": sys.argv[3], "source_tree_sha256": sys.argv[4], "artifacts": [{"path": "profile.json", "sha256": sys.argv[5]}, {"path": "bridge-canister.wasm", "sha256": sys.argv[6]}, {"path": "bridge-runtime.bin", "sha256": sys.argv[7]}], **({"parent_gate_a_manifest_sha256": sys.argv[2]} if sys.argv[2] != "-" else {})}, open(sys.argv[1], "w"))
' "$TEST_TMP_ROOT/bundle-a/release-manifest.json" - "$SOURCE_REVISION" "$SOURCE_TREE_SHA256" "$PROFILE_SHA256" "$WASM_SHA256" "$RUNTIME_SHA256"
python3 -c '
import json, sys
json.dump({"release_id": "release-test", "source_revision": sys.argv[3], "source_tree_sha256": sys.argv[4], "artifacts": [{"path": "profile.json", "sha256": sys.argv[5]}, {"path": "bridge-canister.wasm", "sha256": sys.argv[6]}, {"path": "bridge-runtime.bin", "sha256": sys.argv[7]}], "parent_gate_a_manifest_sha256": sys.argv[2]}, open(sys.argv[1], "w"))
' "$TEST_TMP_ROOT/bundle-b/release-manifest.json" "$(printf '%064d' 1)" "$SOURCE_REVISION" "$SOURCE_TREE_SHA256" "$PROFILE_SHA256" "$WASM_SHA256" "$RUNTIME_SHA256"

write_gate() {
  local result="$1"
  if [[ "$result" == 0 ]]; then GATE_RESULT=pass; else GATE_RESULT=fail; fi
}

run_release() {
  GATE_CALLS="$TEST_TMP_ROOT/gate-calls" \
    RENDER_SOURCE="$TEST_TMP_ROOT/release-inputs" \
    BRIDGE_SOURCE_ROOT="$TEST_TMP_ROOT/ignored-source-override" \
    BRIDGE_PROFILE_BIN="$TEST_TMP_ROOT/malicious-profile" \
    PROFILE_OVERRIDE_MARKER="$TEST_TMP_ROOT/profile-override-used" \
    TMPDIR="$TEST_TMP_ROOT/release-scratch" \
    GATE_RESULT="$GATE_RESULT" \
    "$TEST_TMP_ROOT/source/scripts/production-release.sh" "$@"
}

expect_rejected() {
  if run_release "$@" >/dev/null 2>&1; then
    echo "production release command was unexpectedly accepted: $*" >&2
    exit 1
  fi
}

ACTIVATION_ARGS=(
  --phase schedule
  --submission "$TEST_TMP_ROOT/activation-submission.json"
  --sns-identity proposer
  --sns-neuron-subaccount "$(printf 'a%.0s' {1..64})"
  --sns-proposer-principal "aaaaa-aa"
  --confirm-asset-acceptance SCHEDULE_PRODUCTION_ASSET_ACTIVATION
)

write_gate 1
expect_rejected deploy --bundle "$TEST_TMP_ROOT/bundle-a" --release-inputs "$TEST_TMP_ROOT/release-inputs" --receipt "$TEST_TMP_ROOT/receipt.json" -- "$TEST_TMP_ROOT/source/scripts/production-deploy-driver.sh"
[[ ! -e "$TEST_TMP_ROOT/deployed" ]]

write_gate 0
expect_rejected deploy --bundle "$TEST_TMP_ROOT/bundle-a" --release-inputs "$TEST_TMP_ROOT/release-inputs" --receipt "$TEST_TMP_ROOT/receipt.json" -- touch extra-argument
expect_rejected activate --bundle "$TEST_TMP_ROOT/bundle-b" --release-inputs "$TEST_TMP_ROOT/release-inputs" --receipt "$TEST_TMP_ROOT/receipt.json" -- "$TEST_TMP_ROOT/source/scripts/production-activate-driver.sh"
[[ ! -e "$TEST_TMP_ROOT/activated" ]]

ACTION_MARKER="$TEST_TMP_ROOT/deployed" run_release deploy --bundle "$TEST_TMP_ROOT/bundle-a" --release-inputs "$TEST_TMP_ROOT/release-inputs" --receipt "$TEST_TMP_ROOT/receipt.json" -- "$TEST_TMP_ROOT/source/scripts/production-deploy-driver.sh"
[[ -e "$TEST_TMP_ROOT/deployed" ]]
[[ -s "$TEST_TMP_ROOT/receipt.json" ]]
[[ -s "$TEST_TMP_ROOT/receipt.json.post-deploy-profile.json" ]]
[[ "$(python3 -c 'import json,sys;print(json.load(open(sys.argv[1]))["deployment_block"])' "$TEST_TMP_ROOT/receipt.json.post-deploy-profile.json")" == 1 ]]
python3 - "$TEST_TMP_ROOT/receipt.json" <<'PY'
import json,sys
receipt=json.load(open(sys.argv[1],encoding='utf-8'))
assert receipt['bridge_deployment_transaction_hash']=='0x'+'a'*64
assert receipt['bridge_deployment_block_number']==1
assert receipt['bridge_deployment_block_hash']=='0x'+'c'*64
assert receipt['timelock_deployment_transaction_hash']=='0x'+'b'*64
assert receipt['timelock_deployment_block_number']==1
assert receipt['timelock_deployment_block_hash']=='0x'+'d'*64
PY
cp "$TEST_TMP_ROOT/receipt.json.post-deploy-profile.json" "$TEST_TMP_ROOT/bundle-b/profile.json"
POST_PROFILE_SHA256="$(shasum -a 256 "$TEST_TMP_ROOT/bundle-b/profile.json" | awk '{print $1}')"
python3 - "$TEST_TMP_ROOT/bundle-b/release-manifest.json" "$POST_PROFILE_SHA256" <<'PY'
import json,sys
p=sys.argv[1]; value=json.load(open(p))
next(a for a in value['artifacts'] if a['path']=='profile.json')['sha256']=sys.argv[2]
json.dump(value,open(p,'w'),sort_keys=True,separators=(',',':'))
PY
python3 -c 'import json,sys; json.dump({"profile_file_sha256":sys.argv[2]},open(sys.argv[1],"w"),sort_keys=True,separators=(",",":")); open(sys.argv[1],"a").write("\n")' \
  "$TEST_TMP_ROOT/release-inputs/release-inputs-manifest.json" "$POST_PROFILE_SHA256"
cp "$TEST_TMP_ROOT/receipt.json" "$TEST_TMP_ROOT/bundle-b/gate-a-receipt.json"
GATE_RECEIPT_SHA256="$(shasum -a 256 "$TEST_TMP_ROOT/bundle-b/gate-a-receipt.json" | awk '{print $1}')"
python3 - "$TEST_TMP_ROOT/bundle-b/release-manifest.json" "$GATE_RECEIPT_SHA256" <<'PY'
import json,sys
p=sys.argv[1]; value=json.load(open(p)); value['artifacts'].append({'path':'gate-a-receipt.json','sha256':sys.argv[2]})
json.dump(value,open(p,'w'),sort_keys=True,separators=(',',':'))
PY
rg -q '^validate-bundle --offline ' "$TEST_TMP_ROOT/gate-calls"

write_gate 1
expect_rejected activate --bundle "$TEST_TMP_ROOT/bundle-b" --receipt "$TEST_TMP_ROOT/receipt.json" \
  --release-inputs "$TEST_TMP_ROOT/release-inputs" "${ACTIVATION_ARGS[@]}" -- "$TEST_TMP_ROOT/source/scripts/production-activate-driver.sh"
[[ ! -e "$TEST_TMP_ROOT/activated" ]]

write_gate 0
expect_rejected activate --bundle "$TEST_TMP_ROOT/bundle-b" --receipt "$TEST_TMP_ROOT/receipt.json" \
  --live-preflight /bin/true --release-inputs "$TEST_TMP_ROOT/release-inputs" \
  --confirm-asset-acceptance UNPAUSE_PRODUCTION_ASSET_ACCEPTANCE -- "$TEST_TMP_ROOT/source/scripts/production-activate-driver.sh"
cp "$TEST_TMP_ROOT/bundle-b/release-manifest.json" "$TEST_TMP_ROOT/manifest-valid.json"
cp "$TEST_TMP_ROOT/release-inputs/release-inputs-manifest.json" "$TEST_TMP_ROOT/inputs-valid.json"
python3 - "$TEST_TMP_ROOT/bundle-b/release-manifest.json" "$TEST_TMP_ROOT/release-inputs/release-inputs-manifest.json" <<'PY'
import json,sys
manifest=json.load(open(sys.argv[1])); forged='f'*64
next(a for a in manifest['artifacts'] if a['path']=='profile.json')['sha256']=forged
json.dump(manifest,open(sys.argv[1],'w'),sort_keys=True,separators=(',',':'))
json.dump({'profile_file_sha256':forged},open(sys.argv[2],'w'),sort_keys=True,separators=(',',':'))
PY
expect_rejected activate --bundle "$TEST_TMP_ROOT/bundle-b" --receipt "$TEST_TMP_ROOT/receipt.json" \
  --release-inputs "$TEST_TMP_ROOT/release-inputs" "${ACTIVATION_ARGS[@]}" -- "$TEST_TMP_ROOT/source/scripts/production-activate-driver.sh"
mv "$TEST_TMP_ROOT/manifest-valid.json" "$TEST_TMP_ROOT/bundle-b/release-manifest.json"
mv "$TEST_TMP_ROOT/inputs-valid.json" "$TEST_TMP_ROOT/release-inputs/release-inputs-manifest.json"
ACTION_MARKER="$TEST_TMP_ROOT/activated" run_release activate --bundle "$TEST_TMP_ROOT/bundle-b" --receipt "$TEST_TMP_ROOT/receipt.json" \
  --release-inputs "$TEST_TMP_ROOT/release-inputs" "${ACTIVATION_ARGS[@]}" -- "$TEST_TMP_ROOT/source/scripts/production-activate-driver.sh"
[[ -e "$TEST_TMP_ROOT/activated" ]]
[[ -z "$(find "$TEST_TMP_ROOT/release-scratch" -mindepth 1 -maxdepth 1 -print -quit)" ]]
rg -q '^verify-live ' "$TEST_TMP_ROOT/gate-calls"
[[ ! -e "$TEST_TMP_ROOT/profile-override-used" ]]

if ACTION_MARKER="$TEST_TMP_ROOT/activation-failed" ACTION_FAIL=1 run_release activate \
  --bundle "$TEST_TMP_ROOT/bundle-b" --receipt "$TEST_TMP_ROOT/receipt.json" \
  --release-inputs "$TEST_TMP_ROOT/release-inputs" "${ACTIVATION_ARGS[@]}" \
  -- "$TEST_TMP_ROOT/source/scripts/production-activate-driver.sh"; then
  echo "production activation propagated a successful status from a failed driver" >&2
  exit 1
else
  [[ "$?" -eq 23 ]]
fi
[[ -e "$TEST_TMP_ROOT/activation-failed" ]]
[[ -z "$(find "$TEST_TMP_ROOT/release-scratch" -mindepth 1 -maxdepth 1 -print -quit)" ]]

printf '{"phase":"schedule","release_id":"release-test","source_revision":"%s"}\n' \
  "$SOURCE_REVISION" >"$TEST_TMP_ROOT/schedule-receipt.json"
EXECUTION_ARGS=(
  --phase execute
  --submission "$TEST_TMP_ROOT/execution-submission.json"
  --sns-identity proposer
  --sns-neuron-subaccount "$(printf 'b%.0s' {1..64})"
  --sns-proposer-principal "aaaaa-aa"
  --prior-schedule-receipt "$TEST_TMP_ROOT/schedule-receipt.json"
  --confirm-asset-acceptance UNPAUSE_PRODUCTION_ASSET_ACCEPTANCE
)
ACTION_MARKER="$TEST_TMP_ROOT/executed" run_release activate --bundle "$TEST_TMP_ROOT/bundle-b" --receipt "$TEST_TMP_ROOT/receipt.json" \
  --release-inputs "$TEST_TMP_ROOT/release-inputs" "${EXECUTION_ARGS[@]}" -- "$TEST_TMP_ROOT/source/scripts/production-activate-driver.sh"
[[ -e "$TEST_TMP_ROOT/executed" ]]
rg -q '^verify-schedule-receipt-live ' "$TEST_TMP_ROOT/gate-calls"

mkdir -p "$TEST_TMP_ROOT/failing-git"
REAL_GIT="$(command -v git)"
cat >"$TEST_TMP_ROOT/failing-git/git" <<'SH'
#!/usr/bin/env bash
if [[ "$*" == *"submodule status --recursive"* ]]; then exit 42; fi
exec "$REAL_GIT" "$@"
SH
chmod +x "$TEST_TMP_ROOT/failing-git/git"
if PATH="$TEST_TMP_ROOT/failing-git:$PATH" REAL_GIT="$REAL_GIT" bash -c \
  'source "$1"; production_require_clean_source "$2"' _ \
  "$TEST_TMP_ROOT/source/scripts/production-validation.sh" "$TEST_TMP_ROOT/source" >/dev/null 2>&1; then
  echo "production source validation accepted a failed submodule inspection" >&2
  exit 1
fi
