#!/usr/bin/env bash
set -euo pipefail
ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
T="$(mktemp -d "${TMPDIR:-/tmp}/bridge-driver-test.XXXXXX")"
trap 'rm -rf "$T"' EXIT
mkdir -p "$T/bin" "$T/bundle" "$T/source/contracts" "$T/source/scripts" "$T/source/src"
cp "$ROOT/scripts/production-deploy-driver.sh" "$ROOT/scripts/production-activate-driver.sh" "$ROOT/scripts/production-live-preflight.sh" "$ROOT/scripts/production-validation.sh" "$T/source/scripts/"
chmod +x "$T/source/scripts/production-deploy-driver.sh" "$T/source/scripts/production-activate-driver.sh" "$T/source/scripts/production-live-preflight.sh"
printf '/target\n' >"$T/source/.gitignore"
cat >"$T/source/Cargo.toml" <<'TOML'
[package]
name = "bridge-profile"
version = "0.0.0"
edition = "2021"
TOML
cat >"$T/source/Cargo.lock" <<'LOCK'
# This file is automatically @generated by Cargo.
version = 4

[[package]]
name = "bridge-profile"
version = "0.0.0"
LOCK
cat >"$T/source/src/main.rs" <<'RS'
use std::{env,fs,path::Path};
fn copy_dir(from:&Path,to:&Path){fs::create_dir_all(to).unwrap();for e in fs::read_dir(from).unwrap(){let e=e.unwrap();let d=to.join(e.file_name());if e.path().is_dir(){copy_dir(&e.path(),&d)}else{fs::copy(e.path(),d).unwrap();}}}
fn main(){let a:Vec<String>=env::args().skip(1).collect();if a[0]=="render-release-inputs"{copy_dir(Path::new(&env::var("RENDER_SOURCE").unwrap()),Path::new(&a[2]));return}let c=if a[0]=="verify-live"{'b'}else{'a'};println!("gate=pass manifest_sha256={}",c.to_string().repeat(64));}
RS
git -C "$T/source" init -q
git -C "$T/source" config user.email bridge-test@example.invalid
git -C "$T/source" config user.name bridge-test
git -C "$T/source" add .
git -C "$T/source" commit -qm 'reviewed driver fixture'
DRIVER_ROOT="$T/source"
export TRACE="$T/trace"
: >"$TRACE"
cat >"$T/bin/forge" <<'SH'
#!/usr/bin/env bash
echo "forge $*" >>"$TRACE"; [[ " $* " == *" --ledger "* ]]
if [[ "$*" == *BridgeTimelockController* ]]; then echo '{"deployedTo":"0x2222222222222222222222222222222222222222"}'; else echo '{"deployedTo":"0x3333333333333333333333333333333333333333"}'; fi
SH
cat >"$T/bin/cast" <<'SH'
#!/usr/bin/env bash
echo "cast $*" >>"$TRACE"
case "$1 $2" in
  'keccak PROPOSER_ROLE') printf '0x%s\n' "$(printf '11%.0s' {1..32})";;
  'keccak EXECUTOR_ROLE') printf '0x%s\n' "$(printf '22%.0s' {1..32})";;
  'keccak CANCELLER_ROLE') printf '0x%s\n' "$(printf '33%.0s' {1..32})";;
  'chain-id --rpc-url') echo 8453;;
  'block safe') h="${LATEST_HEIGHT:-100}"; if [[ "${LATEST_BLOCK_DRIFT:-}" == all && "$*" == *one.example* ]]; then x=1; elif [[ "${LATEST_BLOCK_DRIFT:-}" == all && "$*" == *two.example* ]]; then x=2; elif [[ "${LATEST_BLOCK_DRIFT:-}" == all ]]; then x=3; else x=a; fi; printf '{"number":"0x%x","hash":"0x%s"}\n' "$h" "$(printf "$x%.0s" {1..64})";;
  'block 100') if [[ "${SIGNED_BLOCK_DRIFT:-}" == all && "$*" == *one.example* ]]; then x=1; elif [[ "${SIGNED_BLOCK_DRIFT:-}" == all && "$*" == *two.example* ]]; then x=2; elif [[ "${SIGNED_BLOCK_DRIFT:-}" == all ]]; then x=3; else x=a; fi; printf '{"number":"0x64","hash":"0x%s"}\n' "$(printf "$x%.0s" {1..64})";;
  'code 0x3333333333333333333333333333333333333333') echo 0x00;;
  'code 0x7777777777777777777777777777777777777777') echo 0x00;;
  'calldata unpauseDepositMints()') echo 0x1111;;
  'calldata unpauseWithdrawals()') echo 0x2222;;
  'send '*) if [[ "$*" == *executeBatch* ]]; then touch "$EXECUTED_MARKER"; elif [[ "$*" == *pauseDepositMints* ]]; then [[ "${DEPOSIT_PAUSE_FAIL:-}" != true ]] || exit 1; touch "$DEPOSIT_PAUSED_MARKER"; elif [[ "$*" == *pauseWithdrawals* ]]; then [[ "${WITHDRAWAL_PAUSE_FAIL:-}" != true ]] || exit 1; touch "$WITHDRAWAL_PAUSED_MARKER"; fi; echo '{"status":"0x1"}';;
  'call 0x3333333333333333333333333333333333333333') case "$3" in bridgeSigner*) if [[ "${PROVIDER_DRIFT:-}" == all && "$*" == *one.example* ]]; then echo 0x9999999999999999999999999999999999999991; elif [[ "${PROVIDER_DRIFT:-}" == all && "$*" == *two.example* ]]; then echo 0x9999999999999999999999999999999999999992; elif [[ "${PROVIDER_DRIFT:-}" == all ]]; then echo 0x9999999999999999999999999999999999999993; else echo 0x1111111111111111111111111111111111111111; fi;; runtimeAdministrator*) echo 0x6666666666666666666666666666666666666666;; baseAdminTimelock*) echo 0x2222222222222222222222222222222222222222;; bsns*) echo 0x7777777777777777777777777777777777777777;; depositMintsPaused*) if [[ "${CONFIRM_FAIL:-}" == true && -e "$DEPOSIT_PAUSED_MARKER" ]]; then echo false; elif [[ -e "$DEPOSIT_PAUSED_MARKER" ]]; then echo true; elif [[ -e "$EXECUTED_MARKER" || "${BASE_PAUSED:-true}" != true ]]; then echo false; else echo true; fi;; withdrawalsPaused*) if [[ "${CONFIRM_FAIL:-}" == true && -e "$WITHDRAWAL_PAUSED_MARKER" ]]; then echo false; elif [[ -e "$WITHDRAWAL_PAUSED_MARKER" ]]; then echo true; elif [[ -e "$EXECUTED_MARKER" || "${BASE_PAUSED:-true}" != true ]]; then echo false; else echo true; fi;; esac;;
  'call 0x2222222222222222222222222222222222222222') case "$3" in getMinDelay*) echo 259200;; hasRole*) if [[ "${ROLE_DRIFT:-}" == true && "$4" != "0x$(printf '00%.0s' {1..32})" && "$5" != 0x0000000000000000000000000000000000000000 ]]; then echo false; elif [[ "$4" == "0x$(printf '00%.0s' {1..32})" && "$5" == 0x2222222222222222222222222222222222222222 ]]; then echo true; elif [[ "$4" == "0x$(printf '00%.0s' {1..32})" || "$5" == 0x0000000000000000000000000000000000000000 ]]; then echo false; else echo true; fi;; hashOperationBatch*) echo 0xbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb;; isOperationPending*) echo true;; isOperationReady*) echo true;; esac;;
  'call 0x7777777777777777777777777777777777777777') case "$3" in name*) echo '"KINIC"';; symbol*) echo '"KINIC"';; decimals*) echo 8;; bridge*) echo 0x3333333333333333333333333333333333333333;; esac;;
  *) echo "unexpected cast call: $*" >&2; exit 1;;
esac
SH
cat >"$T/bin/dfx" <<'SH'
#!/usr/bin/env bash
echo "dfx $*" >>"$TRACE"
if [[ "$*" == *get_public_config* ]]; then printf '{"expected_bridge_signer":[17,17,17,17,17,17,17,17,17,17,17,17,17,17,17,17,17,17,17,17],"evm_rpc_canister_id":"aaaaa-aa","rpc_provider_urls_sha256":"%s"}\n' "$RPC_DIGEST";
elif [[ "$*" == *get_bridge_status* ]]; then if [[ -e "$IC_RESUMED_MARKER" ]]; then paused=false; else paused="${CANISTER_PAUSED:-true}"; fi; printf '{"deposits_paused":%s,"reserve":{"sufficient":true}}\n' "$paused";
elif [[ "$*" == *sign_chain_key_challenge* ]]; then printf '{"Ok":"0x'; printf '11%.0s' {1..65}; echo '"}';
elif [[ "$*" == *resume_new_deposits* ]]; then if [[ "${RESUME_FAIL:-}" == true ]]; then echo '{"Err":"StorageFailure"}'; exit 1; fi; touch "$IC_RESUMED_MARKER"; echo '{"Ok":null}';
elif [[ "$*" == *pause_new_deposits* ]]; then if [[ "${IC_PAUSE_FAIL:-}" == true ]]; then exit 1; fi; rm -f "$IC_RESUMED_MARKER"; echo '{"Ok":null}';
elif [[ "$*" == *'canister status'* ]]; then echo '{"controllers":["aaaaa-aa"],"module_hash":"6e340b9cffb37a989ca544e6bb780a2c78901d3fb33738768511a30617afa01d"}';
else echo '{}'; fi
SH
chmod +x "$T/bin/forge" "$T/bin/cast" "$T/bin/dfx"
export PATH="$T/bin:$PATH"
export EXECUTED_MARKER="$T/executed" IC_RESUMED_MARKER="$T/ic-resumed" DEPOSIT_PAUSED_MARKER="$T/deposit-paused" WITHDRAWAL_PAUSED_MARKER="$T/withdrawal-paused"
export RPC_DIGEST="$(python3 -c 'import hashlib,json;print(hashlib.sha256(json.dumps(["https://one.example","https://two.example","https://three.example"],separators=(",",":"),ensure_ascii=False).encode()).hexdigest())')"
cat >"$T/bundle/profile.json" <<'JSON'
{"chain_id":8453,"evm_rpc_canister_id":"aaaaa-aa","bridge_canister_id":"aaaaa-aa","bridge_contract":"0x3333333333333333333333333333333333333333","bsns_contract":"0x7777777777777777777777777777777777777777","decimals":8,"expected_bridge_signer":"0x1111111111111111111111111111111111111111","runtime_administrator":"0x6666666666666666666666666666666666666666","base_admin_wallet":"0x4444444444444444444444444444444444444444","release_approver":"0x8888888888888888888888888888888888888888","timelock":{"address":"0x2222222222222222222222222222222222222222","minimum_delay_seconds":259200,"proposer":"0x4444444444444444444444444444444444444444","executor":"0x4444444444444444444444444444444444444444","canceller":"0x5555555555555555555555555555555555555555"},"root_canister_id":"aaaaa-aa","bridge_runtime_bytecode_sha256":"6e340b9cffb37a989ca544e6bb780a2c78901d3fb33738768511a30617afa01d","bsns_runtime_bytecode_sha256":"6e340b9cffb37a989ca544e6bb780a2c78901d3fb33738768511a30617afa01d","bridge_canister_wasm_sha256":"6e340b9cffb37a989ca544e6bb780a2c78901d3fb33738768511a30617afa01d","ic_host":"https://icp-api.io","base_rpc_url":"https://rpc.example","rpc_providers":[{"url":"https://one.example"},{"url":"https://two.example"},{"url":"https://three.example"}]}
JSON
cat >"$T/constructors.json" <<'JSON'
{"timelock":["259200","[0x4444444444444444444444444444444444444444]","[0x5555555555555555555555555555555555555555]","[0x4444444444444444444444444444444444444444]"],"bridge":["KINIC","KINIC","8","0x1111111111111111111111111111111111111111","0x6666666666666666666666666666666666666666","0x2222222222222222222222222222222222222222","1","2","3600","2","1"]}
JSON
cat >"$T/init.json" <<'JSON'
{"settlement_rate_limit_global":1,"settlement_rate_limit_per_principal":1,"settlement_cycle_ceiling":"1","settlement_rate_limit_per_record":1,"finance_administrator":"aaaaa-aa","deposit_rate_limit_window_seconds":1,"ecdsa_key_name":"key_1","base_chain_id":8453,"bridge_contract_hex":"3333333333333333333333333333333333333333","max_priority_fee_per_gas":"1","fee_recipient":{"owner":"aaaaa-aa","subaccount_hex":""},"settlement_rate_limit_window_seconds":1,"ecdsa_derivation_path_utf8":[],"evm_rpc_canister_id":"aaaaa-aa","deposit_rate_limit_per_principal":1,"pause_principals":["aaaaa-aa"],"max_fee_per_gas":"1","eth_floor_wei":"1","custom_evm_rpc_urls":["https://one.example","https://two.example","https://three.example"],"transaction_gas_limit":"1","deposit_rate_limit_global":1,"governance_principal":"aaaaa-aa","index_canister_id":"aaaaa-aa","ledger_canister_id":"aaaaa-aa","cycles_floor":"1"}
JSON
mkdir -p "$T/rendered"
cp "$T/init.json" "$T/rendered/canister-init.json"
cp "$T/constructors.json" "$T/rendered/contract-constructor-args.json"
printf '{}\n' >"$T/rendered/ui-runtime-profile.json"
printf '{}\n' >"$T/rendered/release-inputs-manifest.json"
printf '{"bridge":["MALICIOUS"],"timelock":[]}\n' >"$T/malicious-constructors.json"
printf '{"malicious":true}\n' >"$T/malicious-init.json"
export RENDER_SOURCE="$T/rendered"
printf wasm >"$T/bundle/bridge-canister.wasm"
SOURCE_REVISION="$(git -C "$DRIVER_ROOT" rev-parse HEAD)"; SOURCE_TREE="$(git -C "$DRIVER_ROOT" archive HEAD | shasum -a 256 | awk '{print $1}')"
printf '{"release_id":"release-test","source_revision":"%s","source_tree_sha256":"%s"}\n' "$SOURCE_REVISION" "$SOURCE_TREE" >"$T/bundle/release-manifest.json"
printf '{"gate_a_manifest_sha256":"%s"}\n' "$(printf 'a%.0s' {1..64})" >"$T/bundle/gate-a-receipt.json"
if BRIDGE_GATE_A_MANIFEST_SHA256="$(printf 'b%.0s' {1..64})" BRIDGE_RELEASE_BUNDLE="$T/bundle" BRIDGE_CANISTER_INIT_FILE="$T/init.json" BRIDGE_CONSTRUCTOR_ARGS_FILE="$T/constructors.json" BRIDGE_DEPLOYER_ADDRESS=0x4444444444444444444444444444444444444444 BRIDGE_DFX_IDENTITY=production "$DRIVER_ROOT/scripts/production-deploy-driver.sh" >/dev/null 2>&1; then
  echo "deploy driver accepted a forged Gate A hash" >&2; exit 1
fi
BRIDGE_GATE_A_MANIFEST_SHA256="$(printf 'a%.0s' {1..64})" BRIDGE_RELEASE_BUNDLE="$T/bundle" BRIDGE_CANISTER_INIT_FILE="$T/malicious-init.json" BRIDGE_CONSTRUCTOR_ARGS_FILE="$T/malicious-constructors.json" BRIDGE_DEPLOYER_ADDRESS=0x4444444444444444444444444444444444444444 BRIDGE_DFX_IDENTITY=production "$DRIVER_ROOT/scripts/production-deploy-driver.sh"
python3 - "$TRACE" <<'PY'
import sys
s=open(sys.argv[1]).read(); required=['BridgeTimelockController','src/Bridge.sol','cast call','dfx canister install','dfx canister call']; pos=-1
for x in required:
  pos=s.find(x,pos+1); assert pos>=0,(x,s)
assert '--ledger' in s and 'unpause' not in s
assert 'MALICIOUS' not in s
PY
if CANISTER_PAUSED=false BRIDGE_GATE_A_MANIFEST_SHA256="$(printf 'a%.0s' {1..64})" BRIDGE_RELEASE_BUNDLE="$T/bundle" BRIDGE_CANISTER_INIT_FILE="$T/init.json" BRIDGE_CONSTRUCTOR_ARGS_FILE="$T/constructors.json" BRIDGE_DEPLOYER_ADDRESS=0x4444444444444444444444444444444444444444 BRIDGE_DFX_IDENTITY=production "$DRIVER_ROOT/scripts/production-deploy-driver.sh" >/dev/null 2>&1; then
  echo "deploy driver accepted deposits_paused=false" >&2; exit 1
fi
cat >"$T/bundle/signer-snapshot.json" <<'JSON'
{"chain_key_eip191_signature":"0x00"}
JSON
: >"$TRACE"; BRIDGE_DFX_IDENTITY=production "$DRIVER_ROOT/scripts/production-live-preflight.sh" capture "$T/bundle" "$T/snapshot.json"
cp "$T/snapshot.json" "$T/bundle/signer-snapshot.json"
: >"$TRACE"; export ACTIVATION_PHASE=schedule
if BRIDGE_GATE_B_MANIFEST_SHA256="$(printf 'a%.0s' {1..64})" BRIDGE_RELEASE_BUNDLE="$T/bundle" BRIDGE_ACTIVATION_PHASE=schedule BRIDGE_BASE_ADMIN_ADDRESS=0x4444444444444444444444444444444444444444 BRIDGE_DFX_IDENTITY=production "$DRIVER_ROOT/scripts/production-activate-driver.sh" >/dev/null 2>&1; then
  echo "activation driver accepted a forged Gate B hash" >&2; exit 1
fi
if BASE_PAUSED=false BRIDGE_GATE_B_MANIFEST_SHA256="$(printf 'b%.0s' {1..64})" BRIDGE_RELEASE_BUNDLE="$T/bundle" BRIDGE_ACTIVATION_PHASE=schedule BRIDGE_BASE_ADMIN_ADDRESS=0x4444444444444444444444444444444444444444 BRIDGE_DFX_IDENTITY=production "$DRIVER_ROOT/scripts/production-activate-driver.sh" >/dev/null 2>&1; then
  echo "activation accepted an already-unpaused Base" >&2; exit 1
fi
if CANISTER_PAUSED=false BRIDGE_GATE_B_MANIFEST_SHA256="$(printf 'b%.0s' {1..64})" BRIDGE_RELEASE_BUNDLE="$T/bundle" BRIDGE_ACTIVATION_PHASE=schedule BRIDGE_BASE_ADMIN_ADDRESS=0x4444444444444444444444444444444444444444 BRIDGE_DFX_IDENTITY=production "$DRIVER_ROOT/scripts/production-activate-driver.sh" >/dev/null 2>&1; then
  echo "activation accepted an already-unpaused Canister" >&2; exit 1
fi
BRIDGE_GATE_B_MANIFEST_SHA256="$(printf 'b%.0s' {1..64})" BRIDGE_RELEASE_BUNDLE="$T/bundle" BRIDGE_ACTIVATION_PHASE=schedule BRIDGE_BASE_ADMIN_ADDRESS=0x4444444444444444444444444444444444444444 BRIDGE_DFX_IDENTITY=production "$DRIVER_ROOT/scripts/production-activate-driver.sh"
grep -q scheduleBatch "$TRACE"; ! grep -q resume_new_deposits "$TRACE"
: >"$TRACE"; export ACTIVATION_PHASE=execute
rm -f "$EXECUTED_MARKER" "$IC_RESUMED_MARKER" "$DEPOSIT_PAUSED_MARKER" "$WITHDRAWAL_PAUSED_MARKER"
if RESUME_FAIL=true BRIDGE_GATE_B_MANIFEST_SHA256="$(printf 'b%.0s' {1..64})" BRIDGE_RELEASE_BUNDLE="$T/bundle" BRIDGE_ACTIVATION_PHASE=execute BRIDGE_BASE_ADMIN_ADDRESS=0x4444444444444444444444444444444444444444 BRIDGE_RUNTIME_ADMIN_ADDRESS=0x6666666666666666666666666666666666666666 BRIDGE_DFX_IDENTITY=production "$DRIVER_ROOT/scripts/production-activate-driver.sh" >"$T/fault.log" 2>&1; then
  echo "activation did not fail after IC resume failure" >&2; exit 1
fi
[[ -e "$DEPOSIT_PAUSED_MARKER" && -e "$WITHDRAWAL_PAUSED_MARKER" ]] && grep -q 'INCIDENT:' "$T/fault.log" && grep -q pauseDepositMints "$TRACE" && grep -q pauseWithdrawals "$TRACE"
for scenario in ic_outage one_cast confirm; do
  rm -f "$EXECUTED_MARKER" "$IC_RESUMED_MARKER" "$DEPOSIT_PAUSED_MARKER" "$WITHDRAWAL_PAUSED_MARKER"
  case "$scenario" in ic_outage) extra=(IC_PAUSE_FAIL=true);; one_cast) extra=(DEPOSIT_PAUSE_FAIL=true);; confirm) extra=(CONFIRM_FAIL=true);; esac
  if env RESUME_FAIL=true "${extra[@]}" BRIDGE_GATE_B_MANIFEST_SHA256="$(printf 'b%.0s' {1..64})" BRIDGE_RELEASE_BUNDLE="$T/bundle" BRIDGE_ACTIVATION_PHASE=execute BRIDGE_BASE_ADMIN_ADDRESS=0x4444444444444444444444444444444444444444 BRIDGE_RUNTIME_ADMIN_ADDRESS=0x6666666666666666666666666666666666666666 BRIDGE_DFX_IDENTITY=production "$DRIVER_ROOT/scripts/production-activate-driver.sh" >"$T/$scenario.log" 2>&1; then
    echo "activation did not fail for $scenario compensation fault" >&2; exit 1
  fi
  grep -q 'compensation incomplete' "$T/$scenario.log"
  grep -q pauseDepositMints "$TRACE" && grep -q pauseWithdrawals "$TRACE"
  if [[ "$scenario" == ic_outage ]]; then [[ -e "$DEPOSIT_PAUSED_MARKER" && -e "$WITHDRAWAL_PAUSED_MARKER" ]]; fi
  if [[ "$scenario" == one_cast ]]; then [[ ! -e "$DEPOSIT_PAUSED_MARKER" && -e "$WITHDRAWAL_PAUSED_MARKER" ]]; fi
done
rm -f "$EXECUTED_MARKER" "$IC_RESUMED_MARKER" "$DEPOSIT_PAUSED_MARKER" "$WITHDRAWAL_PAUSED_MARKER"
BRIDGE_GATE_B_MANIFEST_SHA256="$(printf 'b%.0s' {1..64})" BRIDGE_RELEASE_BUNDLE="$T/bundle" BRIDGE_ACTIVATION_PHASE=execute BRIDGE_BASE_ADMIN_ADDRESS=0x4444444444444444444444444444444444444444 BRIDGE_RUNTIME_ADMIN_ADDRESS=0x6666666666666666666666666666666666666666 BRIDGE_DFX_IDENTITY=production "$DRIVER_ROOT/scripts/production-activate-driver.sh"
python3 - "$TRACE" <<'PY'
import sys
s=open(sys.argv[1]).read(); assert s.index('executeBatch') < s.index('resume_new_deposits') and '--ledger' in s
PY
: >"$TRACE"; unset ACTIVATION_PHASE; rm -f "$EXECUTED_MARKER" "$IC_RESUMED_MARKER"; BRIDGE_DFX_IDENTITY=production "$DRIVER_ROOT/scripts/production-live-preflight.sh" verify "$T/bundle"
[[ "$(grep -c '^cast chain-id' "$TRACE")" -eq 3 ]]
python3 - "$TRACE" <<'PY'
import sys
for line in open(sys.argv[1]):
  if line.startswith(('cast call ','cast code ')):
    assert '--block 100' in line,line
PY
for drift in base canister roles providers; do
  case "$drift" in
    base) args=(BASE_PAUSED=false);;
    canister) args=(CANISTER_PAUSED=false);;
    roles) args=(ROLE_DRIFT=true);;
    providers) args=(PROVIDER_DRIFT=all);;
  esac
  if env "${args[@]}" BRIDGE_DFX_IDENTITY=production "$DRIVER_ROOT/scripts/production-live-preflight.sh" capture "$T/bundle" "$T/rejected-$drift.json" >/dev/null 2>&1; then
    echo "live preflight accepted $drift drift" >&2; exit 1
  fi
done
for drift in stale_head signed_orphan latest_quorum; do
  case "$drift" in
    stale_head) args=(LATEST_HEIGHT=99);;
    signed_orphan) args=(SIGNED_BLOCK_DRIFT=all);;
    latest_quorum) args=(LATEST_BLOCK_DRIFT=all);;
  esac
  if env "${args[@]}" BRIDGE_DFX_IDENTITY=production "$DRIVER_ROOT/scripts/production-live-preflight.sh" verify "$T/bundle" >/dev/null 2>&1; then
    echo "live preflight accepted $drift" >&2; exit 1
  fi
done
