#!/usr/bin/env bash
set -euo pipefail

ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
T="$(mktemp -d "${TMPDIR:-/tmp}/bridge-production-upgrade-test.XXXXXX")"
trap 'rm -rf "$T"' EXIT
mkdir -p "$T/source/scripts" "$T/source/canister/bridge-canister" "$T/source/tools/bridge-profile/src" "$T/bin" "$T/evidence"
cp "$ROOT/scripts/production-canister-upgrade.sh" "$T/source/scripts/"
printf 'service : {}\n' >"$T/source/canister/bridge-canister/bridge.did"
cat >"$T/source/Cargo.toml" <<'EOF'
[workspace]
members = ["tools/bridge-profile"]
resolver = "2"
EOF
cat >"$T/source/tools/bridge-profile/Cargo.toml" <<'EOF'
[package]
name = "bridge-profile"
version = "0.1.0"
edition = "2021"
EOF
cat >"$T/source/Cargo.lock" <<'EOF'
# This file is automatically @generated by Cargo.
# It is not intended for manual editing.
version = 4

[[package]]
name = "bridge-profile"
version = "0.1.0"
EOF
cat >"$T/source/tools/bridge-profile/src/main.rs" <<'RS'
use std::{env, fs, fs::OpenOptions, io::Write};
fn main() {
    let args = env::args().collect::<Vec<_>>();
    match args.get(1).map(String::as_str) {
        Some("production-upgrade-public-state-sha256")
        | Some("verify-production-upgrade-state-preserved") => println!("{}", "a".repeat(64)),
        Some("submit-production-canister-upgrade") => {
            fs::write(env::var("TEST_LIVE_MODULE").unwrap(), env::var("TEST_NEW_SHA").unwrap()).unwrap();
            let mut artifact = OpenOptions::new().write(true).create_new(true).open(&args[7]).unwrap();
            artifact.write_all(b"{\"schema_version\":1}\n").unwrap();
            artifact.sync_all().unwrap();
            let mut response = OpenOptions::new().write(true).create_new(true).open(&args[8]).unwrap();
            writeln!(response, "request_id={}", "9".repeat(64)).unwrap();
            writeln!(response, "response_hex=").unwrap();
            response.sync_all().unwrap();
            println!("request_id={}", "9".repeat(64));
            println!("response_hex=");
        }
        Some("verify-production-upgrade-submission") => println!("{}", "9".repeat(64)),
        _ => std::process::exit(97),
    }
}
RS
git -C "$T/source" init -q
git -C "$T/source" config user.email bridge-test@example.invalid
git -C "$T/source" config user.name bridge-test
git -C "$T/source" config core.hooksPath /dev/null
git -C "$T/source" add .
git -C "$T/source" commit -qm 'test production upgrade source'
REVISION="$(git -C "$T/source" rev-parse HEAD)"
INSTALLER="lqfvd-m7ihy-e5dvc-gngvr-blzbt-pupeq-6t7ua-r7v4p-bvqjw-ea7gl-4qe"
CANISTER="lb5i5-ziaaa-aaaar-qcgwq-cai"
printf old-wasm >"$T/old.wasm"
printf new-wasm >"$T/new.wasm"
OLD_SHA="$(shasum -a 256 "$T/old.wasm" | awk '{print $1}')"
NEW_SHA="$(shasum -a 256 "$T/new.wasm" | awk '{print $1}')"
printf '%s\n' "$OLD_SHA" >"$T/live-module"
printf 'dummy production identity\n' >"$T/production.pem"
printf '{"bridge_canister_id":"%s","bridge_canister_wasm_sha256":"%s","ic_host":"https://icp-api.io"}\n' \
  "$CANISTER" "$OLD_SHA" >"$T/gate-a-profile.json"
printf '{"source_revision":"%s","bridge_canister_wasm_sha256":"%s","canister_install":{"canister_id":"%s","installer_principal":"%s"}}\n' \
  "$REVISION" "$OLD_SHA" "$CANISTER" "$INSTALLER" >"$T/gate-a-receipt.json"

cat >"$T/bin/icp" <<'SH'
#!/usr/bin/env bash
set -euo pipefail
if [[ "$1 $2" == "identity principal" ]]; then printf '%s\n' "$TEST_INSTALLER"; exit 0; fi
if [[ "$1 $2 $3" == "canister status $TEST_CANISTER" ]]; then
  printf '{"status":{"settings":{"controllers":["%s"]},"module_hash":"%s"}}\n' "$TEST_INSTALLER" "$(<"$TEST_LIVE_MODULE")"
  exit 0
fi
if [[ "$1 $2 $3" == "canister call $TEST_CANISTER" ]]; then printf '4449444c0000\n'; exit 0; fi
exit 97
SH
chmod +x "$T/bin/icp"
export PATH="$T/bin:$PATH"
export TEST_INSTALLER="$INSTALLER" TEST_CANISTER="$CANISTER" TEST_LIVE_MODULE="$T/live-module" \
  TEST_NEW_SHA="$NEW_SHA"

BRIDGE_ICP_IDENTITY=production "$T/source/scripts/production-canister-upgrade.sh" preflight \
  --wasm "$T/new.wasm" --gate-a-profile "$T/gate-a-profile.json" \
  --gate-a-receipt "$T/gate-a-receipt.json" --evidence "$T/evidence/preflight.json" >/dev/null
if BRIDGE_ICP_IDENTITY=production "$T/source/scripts/production-canister-upgrade.sh" execute \
  --wasm "$T/new.wasm" --gate-a-profile "$T/gate-a-profile.json" \
  --gate-a-receipt "$T/gate-a-receipt.json" --preflight "$T/evidence/preflight.json" \
  --controller-pem "$T/production.pem" \
  --receipt "$T/evidence/receipt.json" >/dev/null 2>&1; then
  echo "production upgrade accepted a missing explicit confirmation" >&2
  exit 1
fi
[[ ! -e "$T/evidence/receipt.json.execution.json" ]]
if BRIDGE_ICP_IDENTITY=production BRIDGE_CONFIRM_PRODUCTION_CANISTER_UPGRADE=WRONG \
  "$T/source/scripts/production-canister-upgrade.sh" execute \
  --wasm "$T/new.wasm" --gate-a-profile "$T/gate-a-profile.json" \
  --gate-a-receipt "$T/gate-a-receipt.json" --preflight "$T/evidence/preflight.json" \
  --controller-pem "$T/production.pem" \
  --receipt "$T/evidence/receipt.json" >/dev/null 2>&1; then
  echo "production upgrade accepted an incorrect explicit confirmation" >&2
  exit 1
fi
[[ ! -e "$T/evidence/receipt.json.execution.json" ]]
BRIDGE_ICP_IDENTITY=production \
BRIDGE_CONFIRM_PRODUCTION_CANISTER_UPGRADE=UPGRADE_PRODUCTION_BRIDGE_CANISTER \
  "$T/source/scripts/production-canister-upgrade.sh" execute \
  --wasm "$T/new.wasm" --gate-a-profile "$T/gate-a-profile.json" \
  --gate-a-receipt "$T/gate-a-receipt.json" --preflight "$T/evidence/preflight.json" \
  --controller-pem "$T/production.pem" \
  --receipt "$T/evidence/receipt.json" >/dev/null
python3 -I -S - "$T/evidence/receipt.json" "$OLD_SHA" "$NEW_SHA" "$INSTALLER" <<'PY'
import hashlib,json,sys
value=json.load(open(sys.argv[1],encoding='utf-8'))
assert value['kind']=='production-controller-bootstrap-upgrade'
assert value['install_mode']=='upgrade'
assert value['before_module_sha256']==sys.argv[2]
assert value['after_module_sha256']==sys.argv[3]
assert value['before_controllers']==value['after_controllers']==[sys.argv[4]]
assert 'before_canister_version' not in value and 'after_canister_version' not in value
assert value['request_id']=='9'*64
assert value['recovered'] is False and value['recovered_at_unix'] is None
assert hashlib.sha256(bytes.fromhex(value['response_stdout_hex'])).hexdigest()==value['response_stdout_sha256']
PY

mv "$T/evidence/receipt.json" "$T/evidence/receipt.initial.json"
cp "$T/evidence/preflight.json" "$T/evidence/preflight.original.json"
python3 -I -S - "$T/evidence/preflight.json" <<'PY'
import json,sys
path=sys.argv[1]; value=json.load(open(path,encoding='utf-8'))
value['before_public_state_sha256']='b'*64
open(path,'w',encoding='utf-8').write(json.dumps(value,sort_keys=True,separators=(',',':'))+'\n')
PY
if BRIDGE_ICP_IDENTITY=production "$T/source/scripts/production-canister-upgrade.sh" recover \
  --wasm "$T/new.wasm" --gate-a-profile "$T/gate-a-profile.json" \
  --gate-a-receipt "$T/gate-a-receipt.json" --preflight "$T/evidence/preflight.json" \
  --controller-pem "$T/production.pem" --receipt "$T/evidence/receipt.json" >/dev/null 2>&1; then
  echo "production upgrade recovery accepted a different preflight" >&2
  exit 1
fi
[[ ! -e "$T/evidence/receipt.json" ]]
mv "$T/evidence/preflight.original.json" "$T/evidence/preflight.json"
BRIDGE_ICP_IDENTITY=production "$T/source/scripts/production-canister-upgrade.sh" recover \
  --wasm "$T/new.wasm" --gate-a-profile "$T/gate-a-profile.json" \
  --gate-a-receipt "$T/gate-a-receipt.json" --preflight "$T/evidence/preflight.json" \
  --controller-pem "$T/production.pem" --receipt "$T/evidence/receipt.json" >/dev/null
python3 -I -S - "$T/evidence/receipt.initial.json" "$T/evidence/receipt.json" <<'PY'
import json,sys
before=json.load(open(sys.argv[1],encoding='utf-8')); recovered=json.load(open(sys.argv[2],encoding='utf-8'))
before.pop('verified_at_unix'); recovered.pop('verified_at_unix')
before.pop('recovered'); recovered.pop('recovered')
before.pop('recovered_at_unix'); recovered.pop('recovered_at_unix')
assert before==recovered,{k:(before.get(k),recovered.get(k)) for k in before.keys()|recovered.keys() if before.get(k)!=recovered.get(k)}
value=json.load(open(sys.argv[2],encoding='utf-8'))
assert value['recovered'] is True and isinstance(value['recovered_at_unix'],int)
PY

if BRIDGE_ICP_IDENTITY=anonymous "$T/source/scripts/production-canister-upgrade.sh" preflight \
  --wasm "$T/new.wasm" --gate-a-profile "$T/gate-a-profile.json" \
  --gate-a-receipt "$T/gate-a-receipt.json" --evidence "$T/evidence/anonymous.json" >/dev/null 2>&1; then
  echo "production upgrade accepted a non-production identity" >&2
  exit 1
fi

if BRIDGE_ICP_IDENTITY=production \
  BRIDGE_CONFIRM_PRODUCTION_CANISTER_UPGRADE=UPGRADE_PRODUCTION_BRIDGE_CANISTER \
  "$T/source/scripts/production-canister-upgrade.sh" recover \
  --wasm "$T/new.wasm" --gate-a-profile "$T/gate-a-profile.json" \
  --gate-a-receipt "$T/gate-a-receipt.json" --preflight "$T/evidence/preflight.json" \
  --controller-pem "$T/production.pem" --receipt "$T/evidence/unexpected-confirmation.json" \
  >/dev/null 2>&1; then
  echo "production upgrade recovery accepted an execute-only confirmation" >&2
  exit 1
fi
