#!/usr/bin/env bash
set -euo pipefail

ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
T="$(mktemp -d "${TMPDIR:-/tmp}/bridge-production-upgrade-test.XXXXXX")"
trap 'rm -rf "$T"' EXIT
mkdir -p "$T/source/scripts" "$T/source/canister/bridge-canister" "$T/source/tools/bridge-profile/src" "$T/bin" "$T/evidence"
cp "$ROOT/scripts/production-canister-upgrade.sh" "$T/source/scripts/"
printf 'service : {}\n' >"$T/source/canister/bridge-canister/bridge.did"
cat >"$T/source/Cargo.toml" <<'EOF'
[workspace]
members = ["tools/bridge-profile"]
resolver = "2"
EOF
cat >"$T/source/tools/bridge-profile/Cargo.toml" <<'EOF'
[package]
name = "bridge-profile"
version = "0.1.0"
edition = "2021"
EOF
cat >"$T/source/Cargo.lock" <<'EOF'
# This file is automatically @generated by Cargo.
# It is not intended for manual editing.
version = 4

[[package]]
name = "bridge-profile"
version = "0.1.0"
EOF
cat >"$T/source/tools/bridge-profile/src/main.rs" <<'RS'
use std::{env, fs, fs::OpenOptions, io::Write, path::Path};
fn main() {
    let args = env::args().collect::<Vec<_>>();
    match args.get(1).map(String::as_str) {
        Some("production-upgrade-public-state-sha256") => {
            if args.get(2).is_some_and(|value| value == "4449444c0002") {
                eprintln!("production upgrade requires a sufficient cycles reserve");
                std::process::exit(1);
            }
            if let (Ok(path), Ok(marker)) = (env::var("TEST_MUTATE_PREFLIGHT_PATH"), env::var("TEST_MUTATION_MARKER")) {
                if !Path::new(&marker).exists() {
                    let mut preflight = OpenOptions::new().append(true).open(path).unwrap();
                    preflight.write_all(b" \n").unwrap();
                    preflight.sync_all().unwrap();
                    fs::write(marker, b"mutated\n").unwrap();
                }
            }
            println!("{}", "a".repeat(64));
        }
        Some("validate-production-upgrade-gate-a-binding") => {
            if let (Ok(path), Ok(marker)) = (env::var("TEST_MUTATE_SOURCE_ON_VALIDATE"), env::var("TEST_SOURCE_MUTATION_MARKER")) {
                if !Path::new(&marker).exists() {
                    fs::write(path, b"service : { changed : () -> (); }\n").unwrap();
                    fs::write(marker, b"mutated\n").unwrap();
                }
            }
            println!("{}", "b".repeat(64));
        }
        Some("validate-production-upgrade-history") => {
            if env::var("TEST_REJECT_PRIOR_HISTORY").is_ok() {
                eprintln!("production upgrade history entry is incomplete");
                std::process::exit(1);
            }
            println!("{}", "c".repeat(64));
        }
        Some("validate-production-upgrade-live-predecessor") => {
            if env::var("TEST_REJECT_LIVE_PREDECESSOR").is_ok() {
                eprintln!("live predecessor differs from the typed upgrade history");
                std::process::exit(1);
            }
            println!("{}", "d".repeat(64));
        }
        Some("production-upgrade-history-sources") => {
            if env::var("TEST_FAIL_HISTORY_SOURCES").is_ok() {
                eprintln!("history source enumeration failed");
                std::process::exit(1);
            }
            if env::var("TEST_EMPTY_HISTORY_SOURCES").is_ok() {
                return;
            }
            println!("{}\t{}", env::var("TEST_REVISION").unwrap(), env::var("TEST_SOURCE_TREE").unwrap());
        }
        Some("production-upgrade-snapshot-metadata") => {
            let lifecycle = fs::read_to_string(env::var("TEST_LIVE_LIFECYCLE").unwrap()).unwrap();
            let paused = fs::read_to_string(env::var("TEST_LIVE_PAUSED").unwrap()).unwrap();
            let schema = fs::read_to_string(env::var("TEST_LIVE_SCHEMA").unwrap()).unwrap();
            println!("{}\t{}\t{}", lifecycle.trim(), paused.trim(), schema.trim());
        }
        Some("validate-operational-epoch-snapshot") => {
            if env::var("TEST_REJECT_OPERATIONAL_SNAPSHOT").is_ok() { std::process::exit(1); }
            println!("operational_epoch_snapshot=verified");
        },
        Some("verify-production-upgrade-state-preserved") => println!("{}", "a".repeat(64)),
        Some("prepare-production-canister-upgrade") => {
            let mut artifact = OpenOptions::new().write(true).create_new(true).open(&args[7]).unwrap();
            artifact.write_all(b"{\"schema_version\":2}\n").unwrap();
            artifact.sync_all().unwrap();
            println!("request_id={}", "9".repeat(64));
        }
        Some("validate-production-upgrade-submission") => println!("{}", "9".repeat(64)),
        Some("upload-production-canister-upgrade-chunks") => {
            fs::create_dir_all(&args[8]).unwrap();
            if let Ok(marker) = env::var("TEST_UPLOAD_FAIL_ONCE") {
                if !Path::new(&marker).exists() {
                    fs::write(marker, b"failed\n").unwrap();
                    std::process::exit(1);
                }
            }
            let mut evidence = OpenOptions::new().write(true).create_new(true).open(Path::new(&args[8]).join("complete.json")).unwrap();
            evidence.write_all(b"{\"schema_version\":1,\"chunks\":[{\"index\":0}]}\n").unwrap();
            evidence.sync_all().unwrap();
            if let Ok(path) = env::var("TEST_MUTATE_SOURCE_AFTER_UPLOAD") {
                fs::write(path, b"service : { changed_after_upload : () -> (); }\n").unwrap();
            }
            if let Ok(path) = env::var("TEST_DROP_RESERVE_AFTER_UPLOAD") {
                fs::write(path, b"false\n").unwrap();
            }
        }
        Some("submit-production-canister-upgrade") => {
            let count_path = env::var("TEST_SUBMIT_COUNT").unwrap();
            let count: u64 = fs::read_to_string(&count_path).unwrap().trim().parse().unwrap();
            fs::write(&count_path, format!("{}\n", count + 1)).unwrap();
            fs::write(env::var("TEST_LIVE_MODULE").unwrap(), env::var("TEST_NEW_SHA").unwrap()).unwrap();
            fs::write(env::var("TEST_LIVE_SCHEMA").unwrap(), b"36\n").unwrap();
            let mut response = OpenOptions::new().write(true).create_new(true).open(&args[9]).unwrap();
            writeln!(response, "request_id={}", "9".repeat(64)).unwrap();
            writeln!(response, "response_hex=").unwrap();
            response.sync_all().unwrap();
            println!("request_id={}", "9".repeat(64));
            println!("response_hex=");
        }
        Some("verify-production-upgrade-submission") => println!("{}", "9".repeat(64)),
        _ => std::process::exit(97),
    }
}
RS
git -C "$T/source" init -q
git -C "$T/source" config user.email bridge-test@example.invalid
git -C "$T/source" config user.name bridge-test
git -C "$T/source" config core.hooksPath /dev/null
git -C "$T/source" add .
git -C "$T/source" commit -qm 'test production upgrade source'
INSTALL_REVISION="$(git -C "$T/source" rev-parse HEAD)"
INSTALL_TREE="$(git -C "$T/source" archive HEAD | shasum -a 256 | awk '{print $1}')"
printf 'gate a completed after install\n' >"$T/source/gate-a-source-marker"
git -C "$T/source" add gate-a-source-marker
git -C "$T/source" commit -qm 'test Gate A completion source'
REVISION="$(git -C "$T/source" rev-parse HEAD)"
SOURCE_TREE="$(git -C "$T/source" archive HEAD | shasum -a 256 | awk '{print $1}')"
INSTALLER="lqfvd-m7ihy-e5dvc-gngvr-blzbt-pupeq-6t7ua-r7v4p-bvqjw-ea7gl-4qe"
CANISTER="lb5i5-ziaaa-aaaar-qcgwq-cai"
printf old-wasm >"$T/old.wasm"
printf new-wasm >"$T/new.wasm"
OLD_SHA="$(shasum -a 256 "$T/old.wasm" | awk '{print $1}')"
NEW_SHA="$(shasum -a 256 "$T/new.wasm" | awk '{print $1}')"
printf '%s\n' "$OLD_SHA" >"$T/live-module"
printf '0\n' >"$T/submit-count"
printf '0\n' >"$T/status-call-count"
printf 'true\n' >"$T/reserve-sufficient"
printf 'Bootstrap\n' >"$T/live-lifecycle"
printf 'true\n' >"$T/live-paused"
printf '35\n' >"$T/live-schema"
printf 'dummy production identity\n' >"$T/production.pem"
printf '{"bridge_canister_id":"%s","bridge_canister_wasm_sha256":"%s","ic_host":"https://icp-api.io","parameters":{"ledger_fee":100000}}\n' \
  "$CANISTER" "$OLD_SHA" >"$T/gate-a-profile.json"
printf '{"source_revision":"%s","source_tree_sha256":"%s","bridge_canister_wasm_sha256":"%s","canister_install":{"source_revision":"%s","source_tree_sha256":"%s","canister_id":"%s","installer_principal":"%s","runtime_binding":{"schema_version":35}}}\n' \
  "$REVISION" "$SOURCE_TREE" "$OLD_SHA" "$INSTALL_REVISION" "$INSTALL_TREE" "$CANISTER" "$INSTALLER" >"$T/gate-a-receipt.json"

cat >"$T/bin/icp" <<'SH'
#!/usr/bin/env bash
set -euo pipefail
if [[ "$1 $2" == "identity principal" ]]; then printf '%s\n' "$TEST_INSTALLER"; exit 0; fi
if [[ "$1 $2" == "build bridge-canister" ]]; then
  mkdir -p "$CARGO_TARGET_DIR/wasm32-unknown-unknown/release"
  cp "$TEST_REPRO_WASM" "$CARGO_TARGET_DIR/wasm32-unknown-unknown/release/bridge_canister.wasm"
  exit 0
fi
if [[ "$1 $2 $3" == "canister status $TEST_CANISTER" ]]; then
  printf '{"status":{"settings":{"controllers":["%s"]},"module_hash":"%s"}}\n' "$TEST_INSTALLER" "$(<"$TEST_LIVE_MODULE")"
  exit 0
fi
if [[ "$1 $2 $3" == "canister call $TEST_CANISTER" ]]; then
  if [[ "$4" == get_bridge_status ]]; then
    count="$(<"$TEST_STATUS_CALL_COUNT")"
    if [[ "$(<"$TEST_RESERVE_SUFFICIENT")" != true ]]; then
      printf '4449444c0002\n'
    elif [[ "$count" == 0 ]]; then
      printf '4449444c0000\n'
    else
      printf '4449444c0001\n'
    fi
    printf '%s\n' "$((count + 1))" >"$TEST_STATUS_CALL_COUNT"
  else
    printf '4449444c0000\n'
  fi
  exit 0
fi
exit 97
SH
chmod +x "$T/bin/icp"
export PATH="$T/bin:$PATH"
export TEST_INSTALLER="$INSTALLER" TEST_CANISTER="$CANISTER" TEST_LIVE_MODULE="$T/live-module" \
  TEST_NEW_SHA="$NEW_SHA" TEST_SUBMIT_COUNT="$T/submit-count" TEST_STATUS_CALL_COUNT="$T/status-call-count" \
  TEST_RESERVE_SUFFICIENT="$T/reserve-sufficient" TEST_REPRO_WASM="$T/new.wasm"
export TEST_LIVE_LIFECYCLE="$T/live-lifecycle" TEST_LIVE_PAUSED="$T/live-paused" \
  TEST_LIVE_SCHEMA="$T/live-schema" TEST_REVISION="$REVISION" TEST_SOURCE_TREE="$SOURCE_TREE"

printf wrong-wasm >"$T/not-reproducible.wasm"
if BRIDGE_ICP_IDENTITY=production "$T/source/scripts/production-canister-upgrade.sh" preflight \
  --wasm "$T/not-reproducible.wasm" --gate-a-profile "$T/gate-a-profile.json" \
  --gate-a-receipt "$T/gate-a-receipt.json" --evidence "$T/evidence/not-reproducible.json" >/dev/null 2>&1; then
  echo "production upgrade accepted a Wasm not built from the current source" >&2
  exit 1
fi
[[ ! -e "$T/evidence/not-reproducible.json" ]]

for field in source_tree_sha256 canister_install.source_tree_sha256; do
  receipt="$T/gate-a-receipt-${field//./-}-drift.json"
  python3 - "$T/gate-a-receipt.json" "$receipt" "$field" <<'PY'
import json,sys
value=json.load(open(sys.argv[1],encoding='utf-8'))
target=value
parts=sys.argv[3].split('.')
for part in parts[:-1]: target=target[part]
target[parts[-1]]='f'*64
with open(sys.argv[2],'w',encoding='utf-8') as output: json.dump(value,output)
PY
  if BRIDGE_ICP_IDENTITY=production "$T/source/scripts/production-canister-upgrade.sh" preflight \
    --wasm "$T/new.wasm" --gate-a-profile "$T/gate-a-profile.json" \
    --gate-a-receipt "$receipt" --evidence "$T/evidence/${field//./-}-drift.json" >/dev/null 2>&1; then
    echo "production upgrade accepted $field drift" >&2
    exit 1
  fi
  [[ ! -e "$T/evidence/${field//./-}-drift.json" ]]
done

if BRIDGE_ICP_IDENTITY=production \
  TEST_MUTATE_SOURCE_ON_VALIDATE="$T/source/canister/bridge-canister/bridge.did" \
  TEST_SOURCE_MUTATION_MARKER="$T/source-mutated-on-validate" \
  "$T/source/scripts/production-canister-upgrade.sh" preflight \
  --wasm "$T/new.wasm" --gate-a-profile "$T/gate-a-profile.json" \
  --gate-a-receipt "$T/gate-a-receipt.json" --evidence "$T/evidence/source-drift.json" >/dev/null 2>&1; then
  echo "production upgrade accepted source drift after validator build" >&2
  exit 1
fi
[[ ! -e "$T/evidence/source-drift.json" ]]
git -C "$T/source" checkout -q -- canister/bridge-canister/bridge.did

BRIDGE_ICP_IDENTITY=production "$T/source/scripts/production-canister-upgrade.sh" preflight \
  --wasm "$T/new.wasm" --gate-a-profile "$T/gate-a-profile.json" \
  --gate-a-receipt "$T/gate-a-receipt.json" --evidence "$T/evidence/preflight.json" >/dev/null
if BRIDGE_ICP_IDENTITY=production "$T/source/scripts/production-canister-upgrade.sh" execute \
  --wasm "$T/new.wasm" --gate-a-profile "$T/gate-a-profile.json" \
  --gate-a-receipt "$T/gate-a-receipt.json" --preflight "$T/evidence/preflight.json" \
  --controller-pem "$T/production.pem" \
  --receipt "$T/evidence/receipt.json" >/dev/null 2>&1; then
  echo "production upgrade accepted a missing explicit confirmation" >&2
  exit 1
fi
[[ ! -e "$T/evidence/receipt.json.execution.json" ]]
[[ "$(<"$T/submit-count")" == 0 ]]
if BRIDGE_ICP_IDENTITY=production BRIDGE_CONFIRM_PRODUCTION_CANISTER_UPGRADE=WRONG \
  "$T/source/scripts/production-canister-upgrade.sh" execute \
  --wasm "$T/new.wasm" --gate-a-profile "$T/gate-a-profile.json" \
  --gate-a-receipt "$T/gate-a-receipt.json" --preflight "$T/evidence/preflight.json" \
  --controller-pem "$T/production.pem" \
  --receipt "$T/evidence/receipt.json" >/dev/null 2>&1; then
  echo "production upgrade accepted an incorrect explicit confirmation" >&2
  exit 1
fi
[[ ! -e "$T/evidence/receipt.json.execution.json" ]]
[[ "$(<"$T/submit-count")" == 0 ]]
printf 'false\n' >"$T/reserve-sufficient"
if BRIDGE_ICP_IDENTITY=production \
  BRIDGE_CONFIRM_PRODUCTION_CANISTER_UPGRADE=UPGRADE_PRODUCTION_BRIDGE_CANISTER \
  "$T/source/scripts/production-canister-upgrade.sh" execute \
  --wasm "$T/new.wasm" --gate-a-profile "$T/gate-a-profile.json" \
  --gate-a-receipt "$T/gate-a-receipt.json" --preflight "$T/evidence/preflight.json" \
  --controller-pem "$T/production.pem" \
  --receipt "$T/evidence/insufficient-receipt.json" >/dev/null 2>&1; then
  echo "production upgrade accepted an insufficient live cycles reserve" >&2
  exit 1
fi
[[ ! -e "$T/evidence/insufficient-receipt.json.execution.json" ]]
[[ "$(<"$T/submit-count")" == 0 ]]
printf 'true\n' >"$T/reserve-sufficient"
printf 'partial signed submission\n' >"$T/evidence/preparing-receipt.json.submission.json.preparing.dead"
BRIDGE_ICP_IDENTITY=production \
BRIDGE_CONFIRM_PRODUCTION_CANISTER_UPGRADE=UPGRADE_PRODUCTION_BRIDGE_CANISTER \
  "$T/source/scripts/production-canister-upgrade.sh" execute \
  --wasm "$T/new.wasm" --gate-a-profile "$T/gate-a-profile.json" \
  --gate-a-receipt "$T/gate-a-receipt.json" --preflight "$T/evidence/preflight.json" \
  --controller-pem "$T/production.pem" \
  --receipt "$T/evidence/preparing-receipt.json" >/dev/null
[[ -f "$T/evidence/preparing-receipt.json" && "$(<"$T/submit-count")" == 1 ]]
printf '%s\n' "$OLD_SHA" >"$T/live-module"
printf '0\n' >"$T/submit-count"
printf '{"schema_version":2}\n' >"$T/evidence/submission-candidate.json.submission.json"
BRIDGE_ICP_IDENTITY=production \
BRIDGE_CONFIRM_PRODUCTION_CANISTER_UPGRADE=UPGRADE_PRODUCTION_BRIDGE_CANISTER \
  "$T/source/scripts/production-canister-upgrade.sh" execute \
  --wasm "$T/new.wasm" --gate-a-profile "$T/gate-a-profile.json" \
  --gate-a-receipt "$T/gate-a-receipt.json" --preflight "$T/evidence/preflight.json" \
  --controller-pem "$T/production.pem" \
  --receipt "$T/evidence/submission-candidate.json" >/dev/null
python3 -I -S - "$T/evidence/submission-candidate.json.execution.json" "$T/evidence/submission-candidate.json.submission.json" <<'PY'
import hashlib,json,sys
marker=json.load(open(sys.argv[1],encoding='utf-8'))
assert marker['submission_sha256']==hashlib.sha256(open(sys.argv[2],'rb').read()).hexdigest()
PY
[[ -f "$T/evidence/submission-candidate.json" && "$(<"$T/submit-count")" == 1 ]]
printf '%s\n' "$OLD_SHA" >"$T/live-module"
printf '0\n' >"$T/submit-count"
printf '{"schema_version":2}\n' >"$T/evidence/resume-receipt.json.submission.json"
mkdir -m 700 "$T/evidence/resume-receipt.json.uploads"
if BRIDGE_ICP_IDENTITY=production TEST_UPLOAD_FAIL_ONCE="$T/upload-failed-once" \
  BRIDGE_CONFIRM_PRODUCTION_CANISTER_UPGRADE=UPGRADE_PRODUCTION_BRIDGE_CANISTER \
  "$T/source/scripts/production-canister-upgrade.sh" execute \
  --wasm "$T/new.wasm" --gate-a-profile "$T/gate-a-profile.json" \
  --gate-a-receipt "$T/gate-a-receipt.json" --preflight "$T/evidence/preflight.json" \
  --controller-pem "$T/production.pem" \
  --receipt "$T/evidence/resume-receipt.json" >/dev/null 2>&1; then
  echo "production upgrade did not stop after an incomplete chunk upload" >&2
  exit 1
fi
[[ -f "$T/evidence/resume-receipt.json.execution.json" ]]
[[ -f "$T/evidence/resume-receipt.json.submission.json" ]]
[[ -d "$T/evidence/resume-receipt.json.uploads" ]]
[[ ! -e "$T/evidence/resume-receipt.json.stdout" ]]
[[ "$(<"$T/submit-count")" == 0 ]]
cp "$T/evidence/resume-receipt.json.submission.json" "$T/resume-submission.approved"
printf 'tampered\n' >>"$T/evidence/resume-receipt.json.submission.json"
if BRIDGE_ICP_IDENTITY=production TEST_UPLOAD_FAIL_ONCE="$T/upload-failed-once" \
  BRIDGE_CONFIRM_PRODUCTION_CANISTER_UPGRADE=UPGRADE_PRODUCTION_BRIDGE_CANISTER \
  "$T/source/scripts/production-canister-upgrade.sh" execute \
  --wasm "$T/new.wasm" --gate-a-profile "$T/gate-a-profile.json" \
  --gate-a-receipt "$T/gate-a-receipt.json" --preflight "$T/evidence/preflight.json" \
  --controller-pem "$T/production.pem" \
  --receipt "$T/evidence/resume-receipt.json" >/dev/null 2>&1; then
  echo "production upgrade resumed with a submission not bound by its marker" >&2
  exit 1
fi
[[ "$(<"$T/submit-count")" == 0 ]]
cp "$T/resume-submission.approved" "$T/evidence/resume-receipt.json.submission.json"
BRIDGE_ICP_IDENTITY=production TEST_UPLOAD_FAIL_ONCE="$T/upload-failed-once" \
BRIDGE_CONFIRM_PRODUCTION_CANISTER_UPGRADE=UPGRADE_PRODUCTION_BRIDGE_CANISTER \
  "$T/source/scripts/production-canister-upgrade.sh" execute \
  --wasm "$T/new.wasm" --gate-a-profile "$T/gate-a-profile.json" \
  --gate-a-receipt "$T/gate-a-receipt.json" --preflight "$T/evidence/preflight.json" \
  --controller-pem "$T/production.pem" \
  --receipt "$T/evidence/resume-receipt.json" >/dev/null
[[ -f "$T/evidence/resume-receipt.json" && "$(<"$T/submit-count")" == 1 ]]
printf '%s\n' "$OLD_SHA" >"$T/live-module"
printf '0\n' >"$T/submit-count"
printf 'true\n' >"$T/reserve-sufficient"
if BRIDGE_ICP_IDENTITY=production TEST_DROP_RESERVE_AFTER_UPLOAD="$T/reserve-sufficient" \
  BRIDGE_CONFIRM_PRODUCTION_CANISTER_UPGRADE=UPGRADE_PRODUCTION_BRIDGE_CANISTER \
  "$T/source/scripts/production-canister-upgrade.sh" execute \
  --wasm "$T/new.wasm" --gate-a-profile "$T/gate-a-profile.json" \
  --gate-a-receipt "$T/gate-a-receipt.json" --preflight "$T/evidence/preflight.json" \
  --controller-pem "$T/production.pem" \
  --receipt "$T/evidence/post-upload-insufficient.json" >/dev/null 2>&1; then
  echo "production upgrade accepted a reserve drop after chunk upload" >&2
  exit 1
fi
[[ -f "$T/evidence/post-upload-insufficient.json.uploads/complete.json" ]]
[[ ! -e "$T/evidence/post-upload-insufficient.json.stdout" ]]
[[ "$(<"$T/submit-count")" == 0 ]]
printf 'true\n' >"$T/reserve-sufficient"
if BRIDGE_ICP_IDENTITY=production TEST_MUTATE_SOURCE_AFTER_UPLOAD="$T/source/canister/bridge-canister/bridge.did" \
  BRIDGE_CONFIRM_PRODUCTION_CANISTER_UPGRADE=UPGRADE_PRODUCTION_BRIDGE_CANISTER \
  "$T/source/scripts/production-canister-upgrade.sh" execute \
  --wasm "$T/new.wasm" --gate-a-profile "$T/gate-a-profile.json" \
  --gate-a-receipt "$T/gate-a-receipt.json" --preflight "$T/evidence/preflight.json" \
  --controller-pem "$T/production.pem" \
  --receipt "$T/evidence/source-drift-after-upload.json" >/dev/null 2>&1; then
  echo "production upgrade sent the final install after source drift" >&2
  exit 1
fi
[[ -f "$T/evidence/source-drift-after-upload.json.uploads/complete.json" ]]
[[ ! -e "$T/evidence/source-drift-after-upload.json.stdout" ]]
[[ "$(<"$T/submit-count")" == 0 ]]
git -C "$T/source" checkout -q -- canister/bridge-canister/bridge.did
printf '%s\n' "$OLD_SHA" >"$T/live-module"
printf '0\n' >"$T/status-call-count"

cp "$T/evidence/preflight.json" "$T/evidence/preflight.approved.json"
BRIDGE_ICP_IDENTITY=production TEST_MUTATE_PREFLIGHT_PATH="$T/evidence/preflight.json" \
TEST_MUTATION_MARKER="$T/preflight-mutated" \
BRIDGE_CONFIRM_PRODUCTION_CANISTER_UPGRADE=UPGRADE_PRODUCTION_BRIDGE_CANISTER \
  "$T/source/scripts/production-canister-upgrade.sh" execute \
  --wasm "$T/new.wasm" --gate-a-profile "$T/gate-a-profile.json" \
  --gate-a-receipt "$T/gate-a-receipt.json" --preflight "$T/evidence/preflight.json" \
  --controller-pem "$T/production.pem" \
  --receipt "$T/evidence/receipt.json" >/dev/null
python3 -I -S - "$T/evidence/receipt.json" "$OLD_SHA" "$NEW_SHA" "$INSTALLER" <<'PY'
import hashlib,json,sys
value=json.load(open(sys.argv[1],encoding='utf-8'))
assert value['kind']=='production-controller-bootstrap-upgrade'
assert value['install_mode']=='upgrade'
assert value['before_module_sha256']==sys.argv[2]
assert value['after_module_sha256']==sys.argv[3]
assert value['before_schema_version']==35
assert value['after_schema_version']==36
assert value['before_controllers']==value['after_controllers']==[sys.argv[4]]
assert 'before_canister_version' not in value and 'after_canister_version' not in value
assert value['request_id']=='9'*64
assert value['recovered'] is False and value['recovered_at_unix'] is None
assert hashlib.sha256(bytes.fromhex(value['response_stdout_hex'])).hexdigest()==value['response_stdout_sha256']
assert hashlib.sha256(bytes.fromhex(value['submission_json_hex'])).hexdigest()==value['submission_json_sha256']
assert hashlib.sha256(bytes.fromhex(value['chunk_upload_evidence_json_hex'])).hexdigest()==value['chunk_upload_evidence_json_sha256']
evidence=json.loads(bytes.fromhex(value['chunk_upload_evidence_json_hex']))
assert evidence['schema_version']==1 and evidence['chunks']
PY
[[ -e "$T/preflight-mutated" && "$(<"$T/submit-count")" == 1 ]]
[[ "$(<"$T/status-call-count")" -ge 3 ]]
python3 -I -S - "$T/evidence/receipt.json.execution.json" "$T/evidence/preflight.approved.json" "$T/evidence/preflight.json" <<'PY'
import hashlib,json,sys
marker=json.load(open(sys.argv[1],encoding='utf-8'))
approved=open(sys.argv[2],'rb').read(); changed=open(sys.argv[3],'rb').read()
assert approved != changed
assert marker['preflight_sha256']==hashlib.sha256(approved).hexdigest()
PY

mv "$T/evidence/receipt.json" "$T/evidence/receipt.initial.json"
if BRIDGE_ICP_IDENTITY=production "$T/source/scripts/production-canister-upgrade.sh" recover \
  --wasm "$T/new.wasm" --gate-a-profile "$T/gate-a-profile.json" \
  --gate-a-receipt "$T/gate-a-receipt.json" --preflight "$T/evidence/preflight.json" \
  --controller-pem "$T/production.pem" --receipt "$T/evidence/receipt.json" >/dev/null 2>&1; then
  echo "production upgrade recovery accepted a different preflight" >&2
  exit 1
fi
[[ ! -e "$T/evidence/receipt.json" ]]
[[ "$(<"$T/submit-count")" == 1 ]]
mv "$T/evidence/preflight.approved.json" "$T/evidence/preflight.json"
for case_name in missing-hash changed-hash changed-submission; do
  recovery="$T/evidence/recover-$case_name.json"
  cp "$T/evidence/receipt.json.stdout" "$recovery.stdout"
  cp "$T/evidence/receipt.json.stderr" "$recovery.stderr"
  cp "$T/evidence/receipt.json.submission.json" "$recovery.submission.json"
  cp "$T/evidence/receipt.json.execution.json" "$recovery.execution.json"
  cp -R "$T/evidence/receipt.json.uploads" "$recovery.uploads"
  python3 -I -S - "$recovery.execution.json" "$recovery.submission.json" "$case_name" <<'PY'
import json,os,sys
marker_path,submission_path,case_name=sys.argv[1:]
if case_name=='changed-submission':
 os.chmod(submission_path,0o600)
 with open(submission_path,'ab') as output: output.write(b'changed\n')
else:
 os.chmod(marker_path,0o600)
 marker=json.load(open(marker_path,encoding='utf-8'))
 if case_name=='missing-hash': marker.pop('submission_sha256')
 else: marker['submission_sha256']='0'*64
 with open(marker_path,'w',encoding='utf-8') as output:
  json.dump(marker,output,sort_keys=True,separators=(',',':')); output.write('\n')
PY
  if BRIDGE_ICP_IDENTITY=production "$T/source/scripts/production-canister-upgrade.sh" recover \
    --wasm "$T/new.wasm" --gate-a-profile "$T/gate-a-profile.json" \
    --gate-a-receipt "$T/gate-a-receipt.json" --preflight "$T/evidence/preflight.json" \
    --controller-pem "$T/production.pem" --receipt "$recovery" >/dev/null 2>&1; then
    echo "production upgrade recovery accepted $case_name marker/submission drift" >&2
    exit 1
  fi
  [[ ! -e "$recovery" && "$(<"$T/submit-count")" == 1 ]]
done
BRIDGE_ICP_IDENTITY=production "$T/source/scripts/production-canister-upgrade.sh" recover \
  --wasm "$T/new.wasm" --gate-a-profile "$T/gate-a-profile.json" \
  --gate-a-receipt "$T/gate-a-receipt.json" --preflight "$T/evidence/preflight.json" \
  --controller-pem "$T/production.pem" --receipt "$T/evidence/receipt.json" >/dev/null
python3 -I -S - "$T/evidence/receipt.initial.json" "$T/evidence/receipt.json" <<'PY'
import json,sys
before=json.load(open(sys.argv[1],encoding='utf-8')); recovered=json.load(open(sys.argv[2],encoding='utf-8'))
before.pop('verified_at_unix'); recovered.pop('verified_at_unix')
before.pop('recovered'); recovered.pop('recovered')
before.pop('recovered_at_unix'); recovered.pop('recovered_at_unix')
assert before==recovered,{k:(before.get(k),recovered.get(k)) for k in before.keys()|recovered.keys() if before.get(k)!=recovered.get(k)}
value=json.load(open(sys.argv[2],encoding='utf-8'))
assert value['recovered'] is True and isinstance(value['recovered_at_unix'],int)
PY
[[ "$(<"$T/submit-count")" == 1 ]]

printf third-wasm >"$T/third.wasm"
THIRD_SHA="$(shasum -a 256 "$T/third.wasm" | awk '{print $1}')"
export TEST_NEW_SHA="$THIRD_SHA"
export TEST_REPRO_WASM="$T/third.wasm"
python3 - "$T/evidence/receipt.initial.json" "$T/evidence/prior-upgrade-large-chain.json" "$T/evidence/prior-upgrade-large-raw.json" "$T/evidence/prior-upgrade-oversized-entry.json" <<'PY'
import hashlib,json,sys
source,chain_path,raw_path,oversized_entry_path=sys.argv[1:]
receipt=json.load(open(source,encoding='utf-8'))
large_chain_receipt={**receipt,'padding':'0'*(65*1024*1024)}
raw=json.dumps(large_chain_receipt,sort_keys=True,separators=(',',':')).encode()
digest=hashlib.sha256(raw).hexdigest()
chain={
 'schema_version':1,
 'kind':'production-controller-bootstrap-upgrade-chain',
 'entries':[{
  'sequence':0,
  'previous_receipt_sha256':None,
  'receipt_sha256':digest,
  'receipt_json_hex':raw.hex(),
 }],
}
with open(chain_path,'w',encoding='utf-8') as output:
 json.dump(chain,output,sort_keys=True,separators=(',',':')); output.write('\n')
large_raw={**receipt,'padding':'0'*(129*1024*1024)}
with open(raw_path,'w',encoding='utf-8') as output:
 json.dump(large_raw,output,sort_keys=True,separators=(',',':')); output.write('\n')
oversized_entry={**receipt,'padding':'0'*(129*1024*1024)}
oversized_raw=json.dumps(oversized_entry,sort_keys=True,separators=(',',':')).encode()
oversized_chain={
 'schema_version':1,
 'kind':'production-controller-bootstrap-upgrade-chain',
 'entries':[{
  'sequence':0,
  'previous_receipt_sha256':None,
  'receipt_sha256':hashlib.sha256(oversized_raw).hexdigest(),
  'receipt_json_hex':oversized_raw.hex(),
 }],
}
with open(oversized_entry_path,'w',encoding='utf-8') as output:
 json.dump(oversized_chain,output,sort_keys=True,separators=(',',':')); output.write('\n')
PY
BRIDGE_ICP_IDENTITY=production "$T/source/scripts/production-canister-upgrade.sh" preflight \
  --wasm "$T/third.wasm" --gate-a-profile "$T/gate-a-profile.json" \
  --gate-a-receipt "$T/gate-a-receipt.json" \
  --prior-upgrade-evidence "$T/evidence/prior-upgrade-large-chain.json" \
  --evidence "$T/evidence/large-chain-preflight.json" >/dev/null
if BRIDGE_ICP_IDENTITY=production "$T/source/scripts/production-canister-upgrade.sh" preflight \
  --wasm "$T/third.wasm" --gate-a-profile "$T/gate-a-profile.json" \
  --gate-a-receipt "$T/gate-a-receipt.json" \
  --prior-upgrade-evidence "$T/evidence/prior-upgrade-large-raw.json" \
  --evidence "$T/evidence/large-raw-preflight.json" >/dev/null 2>&1; then
  echo "production upgrade accepted oversized raw prior evidence" >&2
  exit 1
fi
if BRIDGE_ICP_IDENTITY=production "$T/source/scripts/production-canister-upgrade.sh" preflight \
  --wasm "$T/third.wasm" --gate-a-profile "$T/gate-a-profile.json" \
  --gate-a-receipt "$T/gate-a-receipt.json" \
  --prior-upgrade-evidence "$T/evidence/prior-upgrade-oversized-entry.json" \
  --evidence "$T/evidence/oversized-entry-preflight.json" >/dev/null 2>&1; then
  echo "production upgrade accepted an oversized receipt inside prior chain evidence" >&2
  exit 1
fi
cp "$T/evidence/receipt.initial.json" "$T/evidence/prior-upgrade.json"
cp "$T/evidence/prior-upgrade.json" "$T/evidence/prior-upgrade.approved.json"
printf 'OperationalConfigSealed\n' >"$T/live-lifecycle"
if TEST_REJECT_LIVE_PREDECESSOR=1 BRIDGE_ICP_IDENTITY=production \
  "$T/source/scripts/production-canister-upgrade.sh" preflight \
  --wasm "$T/third.wasm" --gate-a-profile "$T/gate-a-profile.json" \
  --gate-a-receipt "$T/gate-a-receipt.json" \
  --prior-upgrade-evidence "$T/evidence/prior-upgrade.json" \
  --evidence "$T/evidence/rejected-live-predecessor.json" >/dev/null 2>&1; then
  echo "production upgrade accepted live state outside the typed upgrade history" >&2
  exit 1
fi
[[ ! -e "$T/evidence/rejected-live-predecessor.json" && "$(<"$T/submit-count")" == 1 ]]
if TEST_REJECT_OPERATIONAL_SNAPSHOT=1 BRIDGE_ICP_IDENTITY=production \
  "$T/source/scripts/production-canister-upgrade.sh" preflight \
  --wasm "$T/third.wasm" --gate-a-profile "$T/gate-a-profile.json" \
  --gate-a-receipt "$T/gate-a-receipt.json" \
  --prior-upgrade-evidence "$T/evidence/prior-upgrade.json" \
  --evidence "$T/evidence/rejected-operational-snapshot.json" >/dev/null 2>&1; then
  echo "production upgrade accepted an invalid operational epoch snapshot" >&2
  exit 1
fi
[[ ! -e "$T/evidence/rejected-operational-snapshot.json" && "$(<"$T/submit-count")" == 1 ]]
for source_mode in TEST_FAIL_HISTORY_SOURCES TEST_EMPTY_HISTORY_SOURCES; do
  if env "$source_mode=1" BRIDGE_ICP_IDENTITY=production \
    "$T/source/scripts/production-canister-upgrade.sh" preflight \
    --wasm "$T/third.wasm" --gate-a-profile "$T/gate-a-profile.json" \
    --gate-a-receipt "$T/gate-a-receipt.json" \
    --prior-upgrade-evidence "$T/evidence/prior-upgrade.json" \
    --evidence "$T/evidence/rejected-history-sources-$source_mode.json" >/dev/null 2>&1; then
    echo "production upgrade accepted unavailable prior source identities" >&2
    exit 1
  fi
  [[ ! -e "$T/evidence/rejected-history-sources-$source_mode.json" && "$(<"$T/submit-count")" == 1 ]]
done
if TEST_SOURCE_TREE="$(printf '0%.0s' {1..64})" BRIDGE_ICP_IDENTITY=production \
  "$T/source/scripts/production-canister-upgrade.sh" preflight \
  --wasm "$T/third.wasm" --gate-a-profile "$T/gate-a-profile.json" \
  --gate-a-receipt "$T/gate-a-receipt.json" \
  --prior-upgrade-evidence "$T/evidence/prior-upgrade.json" \
  --evidence "$T/evidence/rejected-prior-tree.json" >/dev/null 2>&1; then
  echo "production upgrade accepted a prior source tree hash mismatch" >&2
  exit 1
fi
[[ ! -e "$T/evidence/rejected-prior-tree.json" && "$(<"$T/submit-count")" == 1 ]]
if TEST_REJECT_PRIOR_HISTORY=1 BRIDGE_ICP_IDENTITY=production \
  "$T/source/scripts/production-canister-upgrade.sh" preflight \
  --wasm "$T/third.wasm" --gate-a-profile "$T/gate-a-profile.json" \
  --gate-a-receipt "$T/gate-a-receipt.json" \
  --prior-upgrade-evidence "$T/evidence/prior-upgrade.json" \
  --evidence "$T/evidence/rejected-prior-history.json" >/dev/null 2>&1; then
  echo "production upgrade accepted semantically invalid prior evidence" >&2
  exit 1
fi
[[ ! -e "$T/evidence/rejected-prior-history.json" && "$(<"$T/submit-count")" == 1 ]]
BRIDGE_ICP_IDENTITY=production "$T/source/scripts/production-canister-upgrade.sh" preflight \
  --wasm "$T/third.wasm" --gate-a-profile "$T/gate-a-profile.json" \
  --gate-a-receipt "$T/gate-a-receipt.json" \
  --prior-upgrade-evidence "$T/evidence/prior-upgrade.json" \
  --evidence "$T/evidence/second-preflight.json" >/dev/null
python3 -I -S - "$T/evidence/second-preflight.json" "$T/evidence/prior-upgrade.approved.json" "$NEW_SHA" <<'PY'
import hashlib,json,sys
value=json.load(open(sys.argv[1],encoding='utf-8'))
assert value['before_module_sha256']==sys.argv[3]
assert value['before_schema_version']==36
assert value['before_lifecycle']=='OperationalConfigSealed'
assert value['before_deposits_paused'] is True
assert value['prior_upgrade_evidence_sha256']==hashlib.sha256(open(sys.argv[2],'rb').read()).hexdigest()
PY
printf ' \n' >>"$T/evidence/prior-upgrade.json"
if BRIDGE_ICP_IDENTITY=production \
  BRIDGE_CONFIRM_PRODUCTION_CANISTER_UPGRADE=UPGRADE_PRODUCTION_BRIDGE_CANISTER \
  "$T/source/scripts/production-canister-upgrade.sh" execute \
  --wasm "$T/third.wasm" --gate-a-profile "$T/gate-a-profile.json" \
  --gate-a-receipt "$T/gate-a-receipt.json" \
  --prior-upgrade-evidence "$T/evidence/prior-upgrade.json" \
  --preflight "$T/evidence/second-preflight.json" --controller-pem "$T/production.pem" \
  --receipt "$T/evidence/second-receipt.json" >/dev/null 2>&1; then
  echo "production upgrade accepted prior evidence changed after preflight" >&2
  exit 1
fi
[[ "$(<"$T/submit-count")" == 1 ]]
cp "$T/evidence/prior-upgrade.approved.json" "$T/evidence/prior-upgrade.json"
BRIDGE_ICP_IDENTITY=production \
BRIDGE_CONFIRM_PRODUCTION_CANISTER_UPGRADE=UPGRADE_PRODUCTION_BRIDGE_CANISTER \
  "$T/source/scripts/production-canister-upgrade.sh" execute \
  --wasm "$T/third.wasm" --gate-a-profile "$T/gate-a-profile.json" \
  --gate-a-receipt "$T/gate-a-receipt.json" \
  --prior-upgrade-evidence "$T/evidence/prior-upgrade.json" \
  --preflight "$T/evidence/second-preflight.json" --controller-pem "$T/production.pem" \
  --receipt "$T/evidence/second-receipt.json" >/dev/null
python3 -I -S - "$T/evidence/second-receipt.json" "$NEW_SHA" "$THIRD_SHA" <<'PY'
import json,sys
value=json.load(open(sys.argv[1],encoding='utf-8'))
assert value['before_module_sha256']==sys.argv[2]
assert value['after_module_sha256']==sys.argv[3]
assert value['before_schema_version']==36
assert value['after_schema_version']==36
assert value.get('prior_upgrade_evidence_sha256') is None
PY
[[ "$(<"$T/submit-count")" == 2 ]]

if BRIDGE_ICP_IDENTITY=anonymous "$T/source/scripts/production-canister-upgrade.sh" preflight \
  --wasm "$T/new.wasm" --gate-a-profile "$T/gate-a-profile.json" \
  --gate-a-receipt "$T/gate-a-receipt.json" --evidence "$T/evidence/anonymous.json" >/dev/null 2>&1; then
  echo "production upgrade accepted a non-production identity" >&2
  exit 1
fi

if BRIDGE_ICP_IDENTITY=production \
  BRIDGE_CONFIRM_PRODUCTION_CANISTER_UPGRADE=UPGRADE_PRODUCTION_BRIDGE_CANISTER \
  "$T/source/scripts/production-canister-upgrade.sh" recover \
  --wasm "$T/new.wasm" --gate-a-profile "$T/gate-a-profile.json" \
  --gate-a-receipt "$T/gate-a-receipt.json" --preflight "$T/evidence/preflight.json" \
  --controller-pem "$T/production.pem" --receipt "$T/evidence/unexpected-confirmation.json" \
  >/dev/null 2>&1; then
  echo "production upgrade recovery accepted an execute-only confirmation" >&2
  exit 1
fi
[[ "$(<"$T/submit-count")" == 2 ]]
