#!/usr/bin/env bash
set -euo pipefail
ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
T="$(mktemp -d "${TMPDIR:-/tmp}/bridge-driver-test.XXXXXX")"
trap 'rm -rf "$T"' EXIT
mkdir "$T/runtime-tmp"
export TMPDIR="$T/runtime-tmp"
mkdir -p "$T/bin" "$T/bundle" "$T/source/contracts" "$T/source/scripts" "$T/source/src"
cp "$ROOT/scripts/production-deploy-driver.sh" "$ROOT/scripts/production-activate-driver.sh" "$ROOT/scripts/production-seal-driver.sh" "$ROOT/scripts/production-activation-proposal.sh" "$ROOT/scripts/production-live-preflight.sh" "$ROOT/scripts/production-validation.sh" "$T/source/scripts/"
cat >"$T/source/scripts/ci-local.sh" <<'SH'
#!/usr/bin/env bash
set -euo pipefail
[[ "${1:-}" == proofs ]]
printf 'proofs %s\n' "$*" >>"$TRACE"
if [[ "${PROOF_GATE_FAIL:-false}" == true ]]; then exit 42; fi
if [[ "${PROOF_GATE_MUTATE_SOURCE:-false}" == true ]]; then
  printf '\n// proof mutation\n' >>"$(cd "$(dirname "$0")/.." && pwd)/src/main.rs"
fi
SH
cat >"$T/source/scripts/rebuild-release-artifacts.sh" <<'SH'
#!/usr/bin/env bash
set -euo pipefail
printf 'rebuild %s\n' "$*" >>"$TRACE"
[[ "${REPRODUCIBLE_BUILD_FAIL:-false}" != true ]]
SH
chmod +x "$T/source/scripts/production-deploy-driver.sh" "$T/source/scripts/production-activate-driver.sh" "$T/source/scripts/production-seal-driver.sh" "$T/source/scripts/production-activation-proposal.sh" "$T/source/scripts/production-live-preflight.sh" "$T/source/scripts/ci-local.sh"
chmod +x "$T/source/scripts/rebuild-release-artifacts.sh"
printf '/target\n' >"$T/source/.gitignore"
cat >"$T/source/Cargo.toml" <<'TOML'
[package]
name = "bridge-profile"
version = "0.0.0"
edition = "2021"
TOML
cat >"$T/source/Cargo.lock" <<'LOCK'
# This file is automatically @generated by Cargo.
version = 4

[[package]]
name = "bridge-profile"
version = "0.0.0"
LOCK
cat >"$T/source/src/main.rs" <<'RS'
use std::{env,fs,path::Path};
fn copy_dir(from:&Path,to:&Path){fs::create_dir_all(to).unwrap();for e in fs::read_dir(from).unwrap(){let e=e.unwrap();let d=to.join(e.file_name());if e.path().is_dir(){copy_dir(&e.path(),&d)}else{fs::copy(e.path(),d).unwrap();}}}
fn field(value:&str,name:&str)->String{value.split(&format!("\"{}\":\"",name)).nth(1).unwrap().split('"').next().unwrap().into()}
fn main(){let a:Vec<String>=env::args().skip(1).collect();if let Ok(trace)=env::var("TRACE"){use std::io::Write;writeln!(fs::OpenOptions::new().create(true).append(true).open(trace).unwrap(),"profile {}",a.join(" ")).unwrap()}if a[0]=="render-release-inputs"{copy_dir(Path::new(&env::var("RENDER_SOURCE").unwrap()),Path::new(&a[2]));return}if a[0]=="reserve-operational-config-seal"{if Path::new(&a[3]).exists(){println!("existing")}else{fs::write(&a[3],"{\"schema_version\":1}\n").unwrap();println!("created")}}else if a[0]=="write-operational-config-seal-receipt"{fs::write(&a[4],"{\"schema_version\":1}\n").unwrap()}else if a[0]=="authorize-controller-activation"{let root=Path::new(&a[2]);let m=fs::read_to_string(root.join("release-manifest.json")).unwrap();let p=fs::read_to_string(root.join("profile.json")).unwrap();let value=format!("{{\"schema_version\":1,\"phase\":\"{}\",\"release_id\":\"{}\",\"source_revision\":\"{}\",\"source_tree_sha256\":\"{}\",\"gate_b_manifest_sha256\":\"{}\",\"operational_config_seal_receipt_sha256\":\"{}\",\"controller_principal\":\"aaaaa-aa\",\"certified_controller_set\":[\"aaaaa-aa\"],\"certified_module_sha256\":\"{}\",\"authorized_at_unix\":1}}\n",a[1],field(&m,"release_id"),field(&m,"source_revision"),field(&m,"source_tree_sha256"),a[3],env::var("SEAL_RECEIPT_HASH").unwrap(),field(&p,"bridge_canister_wasm_sha256"));fs::write(&a[5],value).unwrap()}else if a[0]=="verify-controller-activation-authorization-fresh"&&env::var("STALE_ACTIVATION_AUTH").as_deref()==Ok("true"){std::process::exit(1)}else if a[0]=="verify-controller-activation-authorization"&&env::var("CANISTER_CONTROLLER_DRIFT").as_deref()==Ok("true"){std::process::exit(1)}else if a[0]=="verify-controller-activation-artifact"&&env::var("ACTIVATION_BINDING_DRIFT").as_deref()==Ok("true"){std::process::exit(1)}else if a[0]=="validate-bundle"&&a.iter().any(|v|v=="--gate-b"){println!("gate_b=pre_seal-pass authorizing=seal manifest_sha256={}","b".repeat(64))}else if a[0]=="validate-bundle"{println!("gate_a=pass authorizing=true manifest_sha256={}","a".repeat(64))}else if a[0]=="verify-production-canister-predeploy"{if a.len()!=3||env::var("CANISTER_PREDEPLOY_FAIL").as_deref()==Ok("true")||env::var("CANISTER_MODULE_DRIFT").as_deref()==Ok("true")||env::var("CANISTER_CONTROLLER_DRIFT").as_deref()==Ok("true"){std::process::exit(1)}println!("production_canister_predeploy=verified")}else if a[0]=="verify-live"{if env::var("FINAL_LIVE_FAIL").as_deref()==Ok("true"){std::process::exit(1)}println!("gate_b=live-pass authorizing={} manifest_sha256={}",a[1],"b".repeat(64))}else{println!("gate=pass manifest_sha256={}","b".repeat(64))}}
RS
git -C "$T/source" init -q
git -C "$T/source" config user.email bridge-test@example.invalid
git -C "$T/source" config user.name bridge-test
git -C "$T/source" add .
git -C "$T/source" commit -qm 'reviewed driver fixture'
DRIVER_ROOT="$T/source"
export TRACE="$T/trace"
: >"$TRACE"
cat >"$T/bin/forge" <<'SH'
#!/usr/bin/env bash
echo "forge $*" >>"$TRACE"
[[ " $* " == *" --keystore "* && " $* " != *" --ledger "* ]]
if [[ "$*" == *BridgeTimelockController* ]]; then touch "$TIMELOCK_DEPLOYED_MARKER"; echo '{"transactionHash":"0xbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb"}'; else touch "$BRIDGE_DEPLOYED_MARKER"; echo '{"transactionHash":"0xaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa"}'; fi
SH
cat >"$T/bin/ci-local.sh" <<'SH'
#!/usr/bin/env bash
touch "$PATH_PROOF_OVERRIDE_MARKER"
exit 0
SH
cat >"$T/bin/cast" <<'SH'
#!/usr/bin/env bash
echo "cast $*" >>"$TRACE"
case "$1 $2" in
  'wallet address') echo 0x4444444444444444444444444444444444444444;;
  'balance 0x4444444444444444444444444444444444444444') echo 999999999999999999999999;;
  'keccak PROPOSER_ROLE') printf '0x%s\n' "$(printf '11%.0s' {1..32})";;
  'keccak EXECUTOR_ROLE') printf '0x%s\n' "$(printf '22%.0s' {1..32})";;
  'keccak CANCELLER_ROLE') printf '0x%s\n' "$(printf '33%.0s' {1..32})";;
  'keccak RoleGranted(bytes32,address,address)') printf '0x%s\n' "$(printf '44%.0s' {1..32})";;
  'keccak RoleRevoked(bytes32,address,address)') printf '0x%s\n' "$(printf '55%.0s' {1..32})";;
  'keccak DepositMintsPaused(address)') printf '0x%s\n' "$(printf '66%.0s' {1..32})";;
  'keccak WithdrawalsPaused(address)') printf '0x%s\n' "$(printf '77%.0s' {1..32})";;
  'keccak Cancelled(bytes32)') printf '0x%s\n' "$(printf '88%.0s' {1..32})";;
  'keccak 0x00') printf '0x%s\n' "$(printf 'cc%.0s' {1..32})";;
  'keccak 0x01') printf '0x%s\n' "$(printf 'dd%.0s' {1..32})";;
  'nonce 0x4444444444444444444444444444444444444444') [[ -e "$TIMELOCK_DEPLOYED_MARKER" ]] && echo 1 || echo 0;;
  'compute-address 0x4444444444444444444444444444444444444444') [[ "$*" == *'--nonce 0'* ]] && echo 'Computed Address: 0x2222222222222222222222222222222222222222' || echo 'Computed Address: 0x3333333333333333333333333333333333333333';;
  'chain-id --rpc-url') if [[ "${PROVIDER_CHAIN_FAILURES:-0}" -ge 1 && "$*" == *one.example* ]] || [[ "${PROVIDER_CHAIN_FAILURES:-0}" -ge 2 && "$*" == *two.example* ]]; then exit 1; elif [[ "${PROVIDER_MALFORMED_CHAINS:-0}" -ge 1 && "$*" == *one.example* ]] || [[ "${PROVIDER_MALFORMED_CHAINS:-0}" -ge 2 && "$*" == *two.example* ]]; then echo invalid; elif [[ "${PROVIDER_WRONG_CHAINS:-0}" -ge 1 && "$*" == *one.example* ]] || [[ "${PROVIDER_WRONG_CHAINS:-0}" -ge 2 && "$*" == *two.example* ]]; then echo 1; else echo 8453; fi;;
  'block pending') [[ "${DEPLOY_FEE_RPC_FAIL:-}" != true ]] || exit 1; if [[ -n "${DEPLOY_BASE_FEE_RAW+x}" ]]; then printf '%s\n' "$DEPLOY_BASE_FEE_RAW"; else printf '{"baseFeePerGas":"0x%x"}\n' "${DEPLOY_BASE_FEE:-98}"; fi;;
  'block safe'|'block finalized') if [[ "${PROVIDER_SAFE_FAILURES:-0}" -ge 1 && "$*" == *one.example* ]] || [[ "${PROVIDER_SAFE_FAILURES:-0}" -ge 2 && "$*" == *two.example* ]]; then exit 1; fi; h="${LATEST_HEIGHT:-100}"; if [[ "${LATEST_BLOCK_DRIFT:-}" =~ ^(all|one)$ && "$*" == *one.example* ]]; then x=1; elif [[ "${LATEST_BLOCK_DRIFT:-}" == all && "$*" == *two.example* ]]; then x=2; elif [[ "${LATEST_BLOCK_DRIFT:-}" == all ]]; then x=3; else x=a; fi; printf '{"number":"0x%x","hash":"0x%s"}\n' "$h" "$(printf "$x%.0s" {1..64})";;
  'block 100') if [[ "${MID_READ_REORG:-}" == all ]]; then x=f; elif [[ "${MID_READ_REORG:-}" == one && "$*" == *three.example* ]]; then x=f; elif [[ "${SIGNED_BLOCK_DRIFT:-}" == all && "$*" == *one.example* ]]; then x=1; elif [[ "${SIGNED_BLOCK_DRIFT:-}" == all && "$*" == *two.example* ]]; then x=2; elif [[ "${SIGNED_BLOCK_DRIFT:-}" == all ]]; then x=3; else x=a; fi; printf '{"number":"0x64","hash":"0x%s"}\n' "$(printf "$x%.0s" {1..64})";;
  'block 1') printf '{"number":"0x1","hash":"0x%s"}\n' "$(printf 'a%.0s' {1..64})";;
  'receipt deposit-action') printf '{"blockNumber":"0x64","blockHash":"0x%s","status":"0x1","logs":[{"address":"0x3333333333333333333333333333333333333333","topics":["0x%s"]}]}\n' "$(printf 'a%.0s' {1..64})" "$(printf '66%.0s' {1..32})";;
  'receipt withdrawal-action') printf '{"blockNumber":"0x64","blockHash":"0x%s","status":"0x1","logs":[{"address":"0x3333333333333333333333333333333333333333","topics":["0x%s"]}]}\n' "$(printf 'a%.0s' {1..64})" "$(printf '77%.0s' {1..32})";;
  'receipt cancel-action') printf '{"blockNumber":"0x64","blockHash":"0x%s","status":"0x1","logs":[{"address":"0x2222222222222222222222222222222222222222","topics":["0x%s"]}]}\n' "$(printf 'a%.0s' {1..64})" "$(printf '88%.0s' {1..32})";;
  'receipt 0x8888888888888888888888888888888888888888888888888888888888888888') if [[ "${KEEPER_BURN_DRIFT:-}" == true ]]; then bh=f; else bh=a; fi; printf '{"blockNumber":"0x64","blockHash":"0x%s","status":"0x1","logs":[{"address":"0x3333333333333333333333333333333333333333","topics":["0x%s","0x%s"]}]}\n' "$(printf "$bh%.0s" {1..64})" "$(printf '99%.0s' {1..32})" "$(printf '77%.0s' {1..32})";;
  'tx deposit-action') echo '{"to":"0x3333333333333333333333333333333333333333","input":"0x1111"}';;
  'tx withdrawal-action') echo '{"to":"0x3333333333333333333333333333333333333333","input":"0x2222"}';;
  'tx cancel-action') echo '{"to":"0x2222222222222222222222222222222222222222","input":"0x3333"}';;
  'tx 0x8888888888888888888888888888888888888888888888888888888888888888') echo '{"to":"0x3333333333333333333333333333333333333333","input":"0x4444"}';;
  'receipt 0x'*) if [[ "${DEPLOYMENT_RECEIPT_UNAVAILABLE:-}" == true ]]; then exit 1; fi; if [[ "$2" == "0x$(printf 'a%.0s' {1..64})" ]]; then address=0x3333333333333333333333333333333333333333; bh=b; else address=0x2222222222222222222222222222222222222222; bh=c; fi; if [[ "${DEPLOYMENT_RECEIPT_DRIFT:-}" == true || ( "${ACTIVATION_RECEIPT_DRIFT:-}" == true && "$2" != "0x$(printf 'a%.0s' {1..64})" && "$2" != "0x$(printf 'b%.0s' {1..64})" ) ]]; then bh=f; fi; if [[ "${DEPLOYMENT_BLOCK_HASH_INVALID:-}" == true ]]; then block_hash=12; else block_hash="$(printf "$bh%.0s" {1..64})"; fi; printf '{"blockNumber":"0x1","blockHash":"0x%s","status":"0x1","contractAddress":"%s"}\n' "$block_hash" "$address";;
  'logs --address') if [[ "${ROLE_EVENT_DRIFT:-}" == true ]]; then role="$(printf 'ff%.0s' {1..32})"; else role="$(printf '00%.0s' {1..32})"; fi; if [[ "${ROLE_EVENT_HASH_DRIFT:-}" == true ]]; then eh=f; else eh=c; fi; printf '[{"blockNumber":"0x1","blockHash":"0x%s","topics":["0x%s","0x%s","0x%s"]},{"blockNumber":"0x1","blockHash":"0x%s","topics":["0x%s","0x%s","0x%s"]},{"blockNumber":"0x1","blockHash":"0x%s","topics":["0x%s","0x%s","0x%s"]},{"blockNumber":"0x1","blockHash":"0x%s","topics":["0x%s","0x%s","0x%s"]}]\n' \
    "$(printf "$eh%.0s" {1..64})" "$(printf '44%.0s' {1..32})" "$role" "$(printf '00%.0s' {1..12})2222222222222222222222222222222222222222" \
    "$(printf "$eh%.0s" {1..64})" "$(printf '44%.0s' {1..32})" "$(printf '11%.0s' {1..32})" "$(printf '00%.0s' {1..12})6666666666666666666666666666666666666666" \
    "$(printf "$eh%.0s" {1..64})" "$(printf '44%.0s' {1..32})" "$(printf '22%.0s' {1..32})" "$(printf '00%.0s' {1..12})6666666666666666666666666666666666666666" \
    "$(printf "$eh%.0s" {1..64})" "$(printf '44%.0s' {1..32})" "$(printf '33%.0s' {1..32})" "$(printf '00%.0s' {1..12})6666666666666666666666666666666666666666";;
  'code 0x3333333333333333333333333333333333333333') [[ -e "$BRIDGE_DEPLOYED_MARKER" ]] && echo 0x00 || echo 0x;;
  'code 0x2222222222222222222222222222222222222222') if [[ ! -e "$TIMELOCK_DEPLOYED_MARKER" ]]; then echo 0x; elif [[ "${TIMELOCK_CODE_DRIFT:-}" == true ]]; then echo 0x01; else echo 0x00; fi;;
  'code 0x7777777777777777777777777777777777777777') echo 0x00;;
  'calldata unpauseDepositMints()') echo 0x1111;;
  'calldata unpauseWithdrawals()') echo 0x2222;;
  'calldata '*) printf '0x%s\n' "${*:2}";;
  'rpc --rpc-url')
    if [[ "$*" == *eth_maxPriorityFeePerGas* ]]; then
      [[ "${DEPLOY_PRIORITY_FEE_RPC_FAIL:-}" != true ]] || exit 1
      if [[ -n "${DEPLOY_PRIORITY_FEE_RAW+x}" ]]; then printf '%s\n' "$DEPLOY_PRIORITY_FEE_RAW"; else printf '"0x%x"\n' "${DEPLOY_SUGGESTED_PRIORITY_FEE:-2}"; fi
      exit 0
    fi
    if [[ "${PROVIDER_EIP1898_FAILURES:-0}" -ge 1 && "$*" == *one.example* ]] || [[ "${PROVIDER_EIP1898_FAILURES:-0}" -ge 2 && "$*" == *two.example* ]]; then exit 1; fi
    if [[ "$*" == *'"blockHash":"0xffff'* ]] || [[ "${MID_READ_REORG:-}" == all ]] || [[ "${MID_READ_REORG:-}" == one && "$*" == *three.example* ]] || [[ "${SIGNED_BLOCK_DRIFT:-}" == all ]]; then exit 1; fi
    if [[ "$*" == *eth_getCode* ]]; then
      if [[ "${TIMELOCK_CODE_DRIFT:-}" == true && "$*" == *0x2222222222222222222222222222222222222222* ]]; then echo '"0x01"'; else echo '"0x00"'; fi
    elif [[ "$*" == *bridgeSnapshot* ]]; then
      if [[ "${CANONICAL_PROBE_MALFORMED:-}" == true ]]; then echo '"0x00"'; elif [[ "${CANONICAL_PROBE_BLOCK_MISMATCH:-}" == true ]]; then printf '"0x%064x%s"\n' 99 "$(printf '0%.0s' {1..704})"; elif [[ "$*" == *'"blockHash":"0xbbbb'* ]]; then printf '"0x%064x%s"\n' 1 "$(printf '0%.0s' {1..704})"; else printf '"0x%064x%s"\n' 100 "$(printf '0%.0s' {1..704})"; fi
    elif [[ "$*" == *bridgeSigner* ]]; then if [[ "${PROVIDER_DRIFT:-}" == all && "$*" == *one.example* ]]; then v=0x9999999999999999999999999999999999999991; elif [[ "${PROVIDER_DRIFT:-}" == all && "$*" == *two.example* ]]; then v=0x9999999999999999999999999999999999999992; elif [[ "${PROVIDER_DRIFT:-}" == all ]]; then v=0x9999999999999999999999999999999999999993; else v=0x1111111111111111111111111111111111111111; fi; printf '"0x%s"\n' "$v";
    elif [[ "$*" == *runtimeAdministrator* ]]; then echo '"0x0x8888888888888888888888888888888888888888"';
    elif [[ "$*" == *baseAdminTimelock* ]]; then echo '"0x0x2222222222222222222222222222222222222222"';
    elif [[ "$*" == *approvedTimelockRuntimeCodeHash* ]]; then [[ "${BRIDGE_APPROVED_HASH_DRIFT:-}" == true ]] && x=dd || x=cc; printf '"0x0x%s"\n' "$(printf "$x%.0s" {1..32})";
    elif [[ "$*" == *'bsns()(address)'* ]]; then echo '"0x0x7777777777777777777777777777777777777777"';
    elif [[ "$*" == *depositMintsPaused* ]]; then if [[ "${CONFIRM_FAIL:-}" == true && -e "$DEPOSIT_PAUSED_MARKER" ]]; then v=false; elif [[ -e "$DEPOSIT_PAUSED_MARKER" ]]; then v=true; elif [[ -e "$EXECUTED_MARKER" || "${BASE_PAUSED:-true}" != true ]]; then v=false; else v=true; fi; echo "\"0x$v\"";
    elif [[ "$*" == *withdrawalsPaused* ]]; then if [[ "${CONFIRM_FAIL:-}" == true && -e "$WITHDRAWAL_PAUSED_MARKER" ]]; then v=false; elif [[ -e "$WITHDRAWAL_PAUSED_MARKER" ]]; then v=true; elif [[ -e "$EXECUTED_MARKER" || "${BASE_PAUSED:-true}" != true ]]; then v=false; else v=true; fi; echo "\"0x$v\"";
    elif [[ "$*" == *serviceFee* ]]; then echo '"0x50000000"';
    elif [[ "$*" == *getMinDelay* ]]; then printf '"0x%064x"\n' 86400;
    elif [[ "$*" == *hasRole* ]]; then if [[ "${ROLE_DRIFT:-}" == true && "$*" != *"0x$(printf '00%.0s' {1..32})"* && "$*" != *' 0x0000000000000000000000000000000000000000'* ]]; then v=false; elif [[ "$*" == *"0x$(printf '00%.0s' {1..32}) 0x2222222222222222222222222222222222222222"* ]]; then v=true; elif [[ "$*" == *"0x$(printf '00%.0s' {1..32})"* || "$*" == *' 0x0000000000000000000000000000000000000000'* ]]; then v=false; else v=true; fi; echo "\"0x$v\"";
    elif [[ "$*" == *isOperationDone* ]]; then [[ -e "$EXECUTED_MARKER" ]] && v=true || v=false; echo "\"0x$v\"";
    elif [[ "$*" == *isOperationPending* || "$*" == *isOperationReady* ]]; then [[ -e "$EXECUTED_MARKER" || -e "$CANCELLED_MARKER" ]] && v=false || v=true; echo "\"0x$v\"";
    elif [[ "$*" == *'name()(string)'* || "$*" == *'symbol()(string)'* ]]; then echo '"0xKINIC"';
    elif [[ "$*" == *'decimals()(uint8)'* ]]; then echo '"0x8"';
    elif [[ "$*" == *'bridge()(address)'* ]]; then echo '"0x0x3333333333333333333333333333333333333333"';
    else echo "unexpected cast rpc: $*" >&2; exit 1; fi;;
  'decode-abi '*) v="${3#0x}"; if [[ "$2" == *'(string)'* ]]; then printf '"%s"\n' "$v"; elif [[ "$2" == getMinDelay* ]]; then echo 86400; else echo "$v"; fi;;
  'send '*) if [[ "$*" == *executeBatch* ]]; then [[ "${EXECUTE_FAIL:-}" != true ]] || exit 1; touch "$EXECUTED_MARKER"; tx=e; elif [[ "$*" == *'cancel(bytes32)'* ]]; then if [[ -e "$EXECUTED_MARKER" ]]; then exit 1; fi; touch "$CANCELLED_MARKER"; tx=c; elif [[ "$*" == *pauseDepositMints* ]]; then [[ "${DEPOSIT_PAUSE_FAIL:-}" != true ]] || exit 1; touch "$DEPOSIT_PAUSED_MARKER"; tx=d; elif [[ "$*" == *pauseWithdrawals* ]]; then [[ "${WITHDRAWAL_PAUSE_FAIL:-}" != true ]] || exit 1; touch "$WITHDRAWAL_PAUSED_MARKER"; tx=f; else tx=b; fi; printf '{"status":"0x1","transactionHash":"0x%s"}\n' "$(printf "$tx%.0s" {1..64})";;
  'call 0x3333333333333333333333333333333333333333') case "$3" in bridgeSigner*) if [[ "${PROVIDER_DRIFT:-}" == all && "$*" == *one.example* ]]; then echo 0x9999999999999999999999999999999999999991; elif [[ "${PROVIDER_DRIFT:-}" == all && "$*" == *two.example* ]]; then echo 0x9999999999999999999999999999999999999992; elif [[ "${PROVIDER_DRIFT:-}" == all ]]; then echo 0x9999999999999999999999999999999999999993; else echo 0x1111111111111111111111111111111111111111; fi;; runtimeAdministrator*) echo 0x8888888888888888888888888888888888888888;; baseAdminTimelock*) echo 0x2222222222222222222222222222222222222222;; approvedTimelockRuntimeCodeHash*) [[ "${BRIDGE_APPROVED_HASH_DRIFT:-}" == true ]] && x=dd || x=cc; printf '0x%s\n' "$(printf "$x%.0s" {1..32})";; bsns*) echo 0x7777777777777777777777777777777777777777;; depositMintsPaused*) if [[ "${CONFIRM_FAIL:-}" == true && -e "$DEPOSIT_PAUSED_MARKER" ]]; then echo false; elif [[ -e "$DEPOSIT_PAUSED_MARKER" ]]; then echo true; elif [[ -e "$EXECUTED_MARKER" || "${BASE_PAUSED:-true}" != true ]]; then echo false; else echo true; fi;; withdrawalsPaused*) if [[ "${CONFIRM_FAIL:-}" == true && -e "$WITHDRAWAL_PAUSED_MARKER" ]]; then echo false; elif [[ -e "$WITHDRAWAL_PAUSED_MARKER" ]]; then echo true; elif [[ -e "$EXECUTED_MARKER" || "${BASE_PAUSED:-true}" != true ]]; then echo false; else echo true; fi;; esac;;
  'call 0x2222222222222222222222222222222222222222') case "$3" in getMinDelay*) echo 86400;; hasRole*) if [[ "${ROLE_DRIFT:-}" == true && "$4" != "0x$(printf '00%.0s' {1..32})" && "$5" != 0x0000000000000000000000000000000000000000 ]]; then echo false; elif [[ "$4" == "0x$(printf '00%.0s' {1..32})" && "$5" == 0x2222222222222222222222222222222222222222 ]]; then echo true; elif [[ "$4" == "0x$(printf '00%.0s' {1..32})" || "$5" == 0x0000000000000000000000000000000000000000 ]]; then echo false; else echo true; fi;; hashOperationBatch*) echo 0xbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb;; isOperationDone*) [[ -e "$EXECUTED_MARKER" ]] && echo true || echo false;; isOperationPending*|isOperationReady*) [[ -e "$EXECUTED_MARKER" || -e "$CANCELLED_MARKER" ]] && echo false || echo true;; esac;;
  'call 0x7777777777777777777777777777777777777777') case "$3" in name*) echo '"KINIC"';; symbol*) echo '"KINIC"';; decimals*) echo 8;; bridge*) echo 0x3333333333333333333333333333333333333333;; esac;;
  *) echo "unexpected cast call: $*" >&2; exit 1;;
esac
SH
cat >"$T/bin/icp" <<'SH'
#!/usr/bin/env bash
echo "icp $*" >>"$TRACE"
if [[ "$*" == *initialize_public_config* ]]; then if [[ "${INITIALIZE_PUBLIC_CONFIG_FAIL:-false}" == true ]]; then echo '{"Err":"DerivationUnavailable"}'; else echo '{"Ok":null}'; fi;
elif [[ "$*" == *get_runtime_binding* ]]; then if [[ "${CANISTER_SIGNER_DRIFT:-false}" == true ]]; then signer_byte=34; else signer_byte=17; fi; signer="$signer_byte"; for _ in {2..20}; do signer="$signer,$signer_byte"; done; printf '{"base_chain_id":8453,"bridge_contract":[51,51,51,51,51,51,51,51,51,51,51,51,51,51,51,51,51,51,51,51],"expected_bridge_runtime_sha256":[110,52,11,156,255,179,122,152,156,165,68,230,187,120,10,44,120,144,29,63,179,55,56,118,133,17,163,6,23,175,160,29],"timelock_contract":[34,34,34,34,34,34,34,34,34,34,34,34,34,34,34,34,34,34,34,34],"deployment_instance_id":[17,17,17,17,17,17,17,17,17,17,17,17,17,17,17,17,17,17,17,17,17,17,17,17,17,17,17,17,17,17,17,17],"minimum_withdrawal_id":[0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1],"ledger_canister_id":"aaaaa-aa","index_canister_id":"aaaaa-aa","schema_version":35,"expected_bridge_signer":[%s],"evm_rpc_canister_id":"aaaaa-aa","rpc_provider_urls_sha256":"%s"}\n' "$signer" "$RPC_DIGEST";
elif [[ "$*" == *get_bridge_status* ]]; then printf '{"deposits_paused":%s,"reserve":{"sufficient":true}}\n' "${CANISTER_PAUSED:-true}";
elif [[ "$*" == *icrc1_fee* ]]; then echo '100000';
elif [[ "$*" == *pause_new_deposits* ]]; then if [[ "${IC_PAUSE_FAIL:-}" == true ]]; then exit 1; fi; echo '{"Ok":null}';
elif [[ "$*" == *'identity principal --identity production'* ]]; then if [[ "${CONFIRMATION_RELAYER_DRIFT:-false}" == true ]]; then echo '2vxsx-fae'; else echo 'aaaaa-aa'; fi;
elif [[ "$*" == *refresh_activation_attestation* ]]; then if [[ "${REFRESH_CALL_FAIL:-false}" == true ]]; then exit 1; else echo '{"Ok":{}}'; fi;
elif [[ "$*" == *list_nervous_system_functions* ]]; then echo '{"functions":[{"id":1,"target_canister_id":"aaaaa-aa","target_method_name":"schedule_activation"}]}';
elif [[ "$*" == *manage_neuron* ]]; then echo '{"command":{"MakeProposal":{"proposal_id":[]}}}';
elif [[ "$*" == *'canister status bridge-canister -e production -i --identity'* ]]; then echo 'aaaaa-aa';
elif [[ "$*" == *'canister status'* ]]; then if [[ "${CONTROLLER_DRIFT:-false}" == true ]]; then controllers='["aaaaa-aa","2vxsx-fae"]'; else controllers='["aaaaa-aa"]'; fi; printf '{"controllers":%s,"module_hash":"6e340b9cffb37a989ca544e6bb780a2c78901d3fb33738768511a30617afa01d"}\n' "$controllers";
else echo '{}'; fi
SH
chmod +x "$T/bin/forge" "$T/bin/cast" "$T/bin/icp" "$T/bin/ci-local.sh"
export PATH="$T/bin:$PATH"
export PATH_PROOF_OVERRIDE_MARKER="$T/path-proof-override-used"
export EXECUTED_MARKER="$T/executed" CANCELLED_MARKER="$T/cancelled" DEPOSIT_PAUSED_MARKER="$T/deposit-paused" WITHDRAWAL_PAUSED_MARKER="$T/withdrawal-paused"
export TIMELOCK_DEPLOYED_MARKER="$T/timelock-deployed" BRIDGE_DEPLOYED_MARKER="$T/bridge-deployed"
export BRIDGE_TIMELOCK_CANCELLER_ADDRESS=0x5555555555555555555555555555555555555555
export BRIDGE_ICP_IDENTITY=production
export BRIDGE_CANONICAL_CONFIRM_TIMEOUT_SECONDS=1 BRIDGE_CANONICAL_CONFIRM_POLL_SECONDS=1
export BRIDGE_DEPLOYMENT_BINDING_FILE="$T/deployment-binding.json"
export BRIDGE_DEPLOYMENT_RESERVATION_FILE="$BRIDGE_DEPLOYMENT_BINDING_FILE.reservation"
: >"$BRIDGE_DEPLOYMENT_RESERVATION_FILE"
export BRIDGE_DEPLOYER_KEYSTORE="$T/deployer-keystore.json"
export BRIDGE_DEPLOYER_PASSWORD_FILE="$T/deployer-password.txt"
export BASE_RPC_URL=https://rpc.example
export BRIDGE_CANISTER_INSTALL_RECEIPT="$T/production-canister-install-receipt.json"
printf '{}\n' >"$BRIDGE_CANISTER_INSTALL_RECEIPT"
printf '{}\n' >"$BRIDGE_DEPLOYER_KEYSTORE"
printf 'test-password\n' >"$BRIDGE_DEPLOYER_PASSWORD_FILE"
export BRIDGE_DEPLOY_GAS_LIMIT=10000000 BRIDGE_DEPLOY_MAX_FEE_PER_GAS=100 BRIDGE_DEPLOY_PRIORITY_FEE_PER_GAS=2
export RPC_DIGEST="$(python3 -c 'import hashlib;print(hashlib.sha256(b"[]").hexdigest())')"
export INDEPENDENT_RPC_DIGEST="$(python3 -c 'import hashlib,json;print(hashlib.sha256(json.dumps(["https://one.example","https://two.example","https://three.example"],separators=(",",":"),ensure_ascii=False).encode()).hexdigest())')"
cat >"$T/bundle/profile.json" <<'JSON'
{"chain_id":8453,"evm_rpc_canister_id":"aaaaa-aa","bridge_canister_id":"aaaaa-aa","ledger_canister_id":"aaaaa-aa","bridge_contract":"0x3333333333333333333333333333333333333333","bsns_contract":"0x7777777777777777777777777777777777777777","decimals":8,"expected_bridge_signer":"0x1111111111111111111111111111111111111111","governance_operator":"0x6666666666666666666666666666666666666666","runtime_administrator":"0x8888888888888888888888888888888888888888","independent_canceller":"0x9999999999999999999999999999999999999999","pause_principal":"7jkta-eyaaa-aaaaq-aaarq-cai","timelock":{"address":"0x2222222222222222222222222222222222222222","runtime_code_hash":"0xcccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc","minimum_delay_seconds":86400,"proposer":"0x6666666666666666666666666666666666666666","executor":"0x6666666666666666666666666666666666666666","canceller":"0x9999999999999999999999999999999999999999"},"root_canister_id":"aaaaa-aa","bridge_runtime_bytecode_sha256":"6e340b9cffb37a989ca544e6bb780a2c78901d3fb33738768511a30617afa01d","bsns_runtime_bytecode_sha256":"6e340b9cffb37a989ca544e6bb780a2c78901d3fb33738768511a30617afa01d","bsns_runtime_template_sha256":"6e340b9cffb37a989ca544e6bb780a2c78901d3fb33738768511a30617afa01d","bridge_canister_wasm_sha256":"6e340b9cffb37a989ca544e6bb780a2c78901d3fb33738768511a30617afa01d","ic_host":"https://icp-api.io","base_rpc_url":null,"deployment_block":0,"parameters":{"ledger_fee":100000,"service_fee":50000000},"rpc_providers":[]}
JSON
python3 - "$T/bundle/profile.json" <<'PY'
import json,sys
path=sys.argv[1]
value=json.load(open(path,encoding='utf-8'))
value['confirmation_relayer_principal']='aaaaa-aa'
value['initial_base_deployment']={'deployer_address':'0x4444444444444444444444444444444444444444','starting_nonce':0,'gas_limit':'10000000','max_fee_per_gas':'100','max_priority_fee_per_gas':'2'}
with open(path,'w',encoding='utf-8') as out: json.dump(value,out,separators=(',',':')); out.write('\n')
PY
printf '{"derived":{}}\n' >"$T/bundle/initial-operational-parameters.json"
cat >"$T/constructors.json" <<'JSON'
{"timelock":["86400","[0x6666666666666666666666666666666666666666]","[0x9999999999999999999999999999999999999999]","[0x6666666666666666666666666666666666666666]"],"bridge":["0x1111111111111111111111111111111111111111","0x8888888888888888888888888888888888888888","0x2222222222222222222222222222222222222222","0xcccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc","1","2","3600","2","1"]}
JSON
cat >"$T/init.json" <<'JSON'
{"settlement_rate_limit_global":1,"settlement_rate_limit_per_principal":1,"settlement_cycle_ceiling":"1","settlement_rate_limit_per_record":1,"settlement_retry_interval_seconds":60,"deposit_rate_limit_window_seconds":1,"notification_rate_limit_window_seconds":600,"notification_rate_limit_global":60,"notification_ingestion_rate_limit_global":30,"ecdsa_key_name":"key_1","base_chain_id":8453,"bridge_contract_hex":"3333333333333333333333333333333333333333","expected_bridge_runtime_sha256_hex":"4444444444444444444444444444444444444444444444444444444444444444","timelock_contract_hex":"2222222222222222222222222222222222222222","deployment_instance_id_hex":"1111111111111111111111111111111111111111111111111111111111111111","minimum_withdrawal_id_hex":"0000000000000000000000000000000000000000000000000000000000000001","governance_evm_fee":{"gas_limit_ceiling":"1","max_fee_per_gas_ceiling":"1","max_priority_fee_per_gas_ceiling":"1","l1_fee_per_transaction_ceiling_wei":"1","quote_validity_seconds":90,"gas_limit_multiplier_bps":13000,"base_fee_multiplier_bps":60000,"l1_fee_multiplier_bps":15000},"governance_replacement":{"max_replacements":3,"fee_bump_bps":1250},"fee_recipient":{"owner":"aaaaa-aa","subaccount_hex":""},"settlement_rate_limit_window_seconds":1,"ecdsa_derivation_path_utf8":["bridge-operator"],"governance_ecdsa_derivation_path_utf8":["governance-operator"],"evm_rpc_canister_id":"aaaaa-aa","deposit_rate_limit_per_principal":1,"pause_principal":"2vxsx-fae","custom_evm_rpc_urls":[],"deposit_rate_limit_global":1,"governance_principal":"aaaaa-aa","confirmation_relayer_principal":"rrkah-fqaaa-aaaaa-aaaaq-cai","index_canister_id":"aaaaa-aa","ledger_canister_id":"aaaaa-aa","cycles_floor":"1"}
JSON
mkdir -p "$T/rendered"
cp "$T/init.json" "$T/rendered/canister-init.json"
cp "$T/constructors.json" "$T/rendered/contract-constructor-args.json"
printf '{}\n' >"$T/rendered/ui-runtime-profile.json"
printf '{}\n' >"$T/rendered/release-inputs-manifest.json"
printf '{"bridge":["MALICIOUS"],"timelock":[]}\n' >"$T/malicious-constructors.json"
printf '{"malicious":true}\n' >"$T/malicious-init.json"
export RENDER_SOURCE="$T/rendered"
printf wasm >"$T/bundle/bridge-canister.wasm"
printf '\0' >"$T/bundle/bsns-runtime.bin"
printf '{"byte_length":1,"immutable_ranges":[{"length":1,"start":0}],"schema_version":1}\n' >"$T/bundle/bsns-runtime-layout.json"
SOURCE_REVISION="$(git -C "$DRIVER_ROOT" rev-parse HEAD)"; SOURCE_TREE="$(git -C "$DRIVER_ROOT" archive HEAD | shasum -a 256 | awk '{print $1}')"
printf '{"schema_version":3,"from_source_revision":"%s","from_source_tree_sha256":"%s","upgrade_source_revision":"%s","upgrade_source_tree_sha256":"%s","to_source_revision":"%s","to_source_tree_sha256":"%s"}\n' \
  "$SOURCE_REVISION" "$SOURCE_TREE" "$SOURCE_REVISION" "$SOURCE_TREE" "$SOURCE_REVISION" "$SOURCE_TREE" \
  >"$T/bundle/post-gate-a-policy-transition.json"
printf '{"release_id":"release-test","source_revision":"%s","source_tree_sha256":"%s"}\n' "$SOURCE_REVISION" "$SOURCE_TREE" >"$T/bundle/release-manifest.json"
printf '{"final_controllers":["aaaaa-aa"]}\n' >"$T/bundle/controller-handover.json"
printf '{"gate_a_manifest_sha256":"%s","canister_install":{"installer_principal":"aaaaa-aa"},"bridge_deployment_transaction_hash":"0x%s","bridge_deployment_block_number":1,"bridge_deployment_block_hash":"0x%s","timelock_deployment_transaction_hash":"0x%s","timelock_deployment_block_number":1,"timelock_deployment_block_hash":"0x%s"}\n' "$(printf 'a%.0s' {1..64})" "$(printf 'a%.0s' {1..64})" "$(printf 'b%.0s' {1..64})" "$(printf 'b%.0s' {1..64})" "$(printf 'c%.0s' {1..64})" >"$T/bundle/gate-a-receipt.json"
printf '{"base_chain_id":8453,"rpc_provider_urls_sha256":"%s","base_actions":[{"kind":"PauseDepositMints","transaction_hash":"deposit-action","block_number":100,"block_hash":"0x%s","target":"0x3333333333333333333333333333333333333333","calldata_hex":"0x1111"},{"kind":"PauseWithdrawals","transaction_hash":"withdrawal-action","block_number":100,"block_hash":"0x%s","target":"0x3333333333333333333333333333333333333333","calldata_hex":"0x2222"},{"kind":"CancelTimelock","transaction_hash":"cancel-action","block_number":100,"block_hash":"0x%s","target":"0x2222222222222222222222222222222222222222","calldata_hex":"0x3333"}]}\n' "$INDEPENDENT_RPC_DIGEST" "$(printf 'a%.0s' {1..64})" "$(printf 'a%.0s' {1..64})" "$(printf 'a%.0s' {1..64})" >"$T/bundle/monitor-drill.json"
printf '{"burn_transaction_hash":"0x%s","burn":{"block_number":100,"block_hash":"0x%s","withdrawal_committed_topic":"0x%s","withdrawal_id_topic":"0x%s"}}\n' "$(printf '88%.0s' {1..32})" "$(printf 'a%.0s' {1..64})" "$(printf '99%.0s' {1..32})" "$(printf '77%.0s' {1..32})" >"$T/bundle/monitoring-receipt.json"
python3 - "$T/bundle" "$SOURCE_REVISION" "$SOURCE_TREE" <<'PY'
import hashlib,json,os,sys
bundle,source_revision,source_tree=sys.argv[1:]
artifacts=[]
for name in sorted(os.listdir(bundle)):
    path=os.path.join(bundle,name)
    if name == 'release-manifest.json' or not os.path.isfile(path):
        continue
    with open(path,'rb') as source:
        digest=hashlib.sha256(source.read()).hexdigest()
    artifacts.append({'path':name,'sha256':digest})
manifest={
    'release_id':'release-test',
    'source_revision':source_revision,
    'source_tree_sha256':source_tree,
    'artifacts':artifacts,
}
with open(os.path.join(bundle,'release-manifest.json'),'w',encoding='utf-8') as output:
    json.dump(manifest,output,separators=(',',':'))
    output.write('\n')
PY
FREEZE_SOURCE="$T/freeze-source"
FREEZE_TARGET="$T/freeze-target"
mkdir -p "$FREEZE_SOURCE/artifacts" "$FREEZE_TARGET"
printf '{"raw":true}\n' >"$FREEZE_SOURCE/artifacts/preflight-base.json"
FREEZE_RAW_SHA="$(shasum -a 256 "$FREEZE_SOURCE/artifacts/preflight-base.json" | awk '{print $1}')"
python3 - "$FREEZE_SOURCE/rpc-e2e.json" "$FREEZE_RAW_SHA" <<'PY'
import json,sys
path,digest=sys.argv[1:]
value={'scenarios':{'preflight':{'artifacts':[{'path':'artifacts/preflight-base.json','sha256':digest}]}}}
with open(path,'w',encoding='utf-8') as output: json.dump(value,output,separators=(',',':')); output.write('\n')
PY
FREEZE_RPC_SHA="$(shasum -a 256 "$FREEZE_SOURCE/rpc-e2e.json" | awk '{print $1}')"
printf '{"artifacts":[{"path":"rpc-e2e.json","sha256":"%s"}]}\n' "$FREEZE_RPC_SHA" >"$FREEZE_SOURCE/release-manifest.json"
# shellcheck source=production-validation.sh
source "$DRIVER_ROOT/scripts/production-validation.sh"
production_freeze_bundle "$FREEZE_SOURCE" "$FREEZE_TARGET"
cmp -s "$FREEZE_SOURCE/artifacts/preflight-base.json" "$FREEZE_TARGET/artifacts/preflight-base.json"
chmod u+w "$FREEZE_TARGET" "$FREEZE_TARGET/artifacts"
printf '{"raw":false}\n' >"$FREEZE_SOURCE/artifacts/preflight-base.json"
mkdir "$T/freeze-rejected"
if production_freeze_bundle "$FREEZE_SOURCE" "$T/freeze-rejected" >/dev/null 2>&1; then
  echo "bundle freeze accepted a drifted RPC rehearsal raw artifact" >&2
  exit 1
fi
FREEZE_COUNT_SOURCE="$T/freeze-count-source"
mkdir -p "$FREEZE_COUNT_SOURCE/artifacts"
python3 - "$FREEZE_COUNT_SOURCE" <<'PY'
import hashlib,json,pathlib,sys
root=pathlib.Path(sys.argv[1]); references=[]
for index in range(129):
    relative=f'artifacts/raw-{index:03}.json'; payload=b'{}\n'
    (root/relative).write_bytes(payload)
    references.append({'path':relative,'sha256':hashlib.sha256(payload).hexdigest()})
rpc=json.dumps({'scenarios':{'preflight':{'artifacts':references}}},separators=(',',':')).encode()+b'\n'
(root/'rpc-e2e.json').write_bytes(rpc)
manifest={'artifacts':[{'path':'rpc-e2e.json','sha256':hashlib.sha256(rpc).hexdigest()}]}
(root/'release-manifest.json').write_text(json.dumps(manifest,separators=(',',':'))+'\n')
PY
mkdir "$T/freeze-count-rejected"
if production_freeze_bundle "$FREEZE_COUNT_SOURCE" "$T/freeze-count-rejected" >/dev/null 2>&1; then
  echo "bundle freeze accepted too many RPC rehearsal raw artifacts" >&2
  exit 1
fi
UPGRADE_LIMIT_SOURCE="$T/upgrade-limit-source"
mkdir "$UPGRADE_LIMIT_SOURCE"
python3 - "$UPGRADE_LIMIT_SOURCE" <<'PY'
import hashlib,json,pathlib,sys
root=pathlib.Path(sys.argv[1]); receipt=root/'production-canister-upgrade-receipt.json'
with receipt.open('wb') as output: output.truncate(17*1024*1024)
digest=hashlib.sha256(receipt.read_bytes()).hexdigest()
(root/'release-manifest.json').write_text(json.dumps({'artifacts':[{'path':receipt.name,'sha256':digest}]},separators=(',',':'))+'\n')
PY
mkdir "$T/upgrade-limit-accepted"
production_freeze_bundle "$UPGRADE_LIMIT_SOURCE" "$T/upgrade-limit-accepted"
cmp -s "$UPGRADE_LIMIT_SOURCE/production-canister-upgrade-receipt.json" "$T/upgrade-limit-accepted/production-canister-upgrade-receipt.json"
chmod -R u+w "$T/upgrade-limit-accepted"
UPGRADE_OVERSIZE_SOURCE="$T/upgrade-oversize-source"
mkdir "$UPGRADE_OVERSIZE_SOURCE"
python3 - "$UPGRADE_OVERSIZE_SOURCE" <<'PY'
import json,pathlib,sys
root=pathlib.Path(sys.argv[1]); receipt=root/'production-canister-upgrade-receipt.json'
with receipt.open('wb') as output: output.truncate(128*1024*1024+1)
(root/'release-manifest.json').write_text(json.dumps({'artifacts':[{'path':receipt.name,'sha256':'0'*64}]},separators=(',',':'))+'\n')
PY
mkdir "$T/upgrade-oversize-rejected"
if UPGRADE_OVERSIZE_ERROR="$(production_freeze_bundle "$UPGRADE_OVERSIZE_SOURCE" "$T/upgrade-oversize-rejected" 2>&1)"; then
  echo "bundle freeze accepted an oversized production upgrade receipt" >&2
  exit 1
fi
[[ "$UPGRADE_OVERSIZE_ERROR" == *"invalid release artifact: production-canister-upgrade-receipt.json"* ]]
RAW_LIMIT_SOURCE="$T/raw-limit-source"
mkdir -p "$RAW_LIMIT_SOURCE/artifacts"
python3 - "$RAW_LIMIT_SOURCE" exact <<'PY'
import hashlib,json,pathlib,sys
root=pathlib.Path(sys.argv[1]); mode=sys.argv[2]; refs=[]
for index in range(4):
    path=root/f'artifacts/raw-{index}.json'
    with path.open('wb') as output: output.truncate(16*1024*1024)
    refs.append({'path':str(path.relative_to(root)),'sha256':hashlib.sha256(path.read_bytes()).hexdigest()})
rpc=json.dumps({'scenarios':{'preflight':{'artifacts':refs}}},separators=(',',':')).encode()+b'\n'
(root/'rpc-e2e.json').write_bytes(rpc)
(root/'release-manifest.json').write_text(json.dumps({'artifacts':[{'path':'rpc-e2e.json','sha256':hashlib.sha256(rpc).hexdigest()}]},separators=(',',':'))+'\n')
PY
mkdir "$T/raw-limit-accepted"
production_freeze_bundle "$RAW_LIMIT_SOURCE" "$T/raw-limit-accepted"
chmod -R u+w "$T/raw-limit-accepted"
python3 - "$RAW_LIMIT_SOURCE" <<'PY'
import hashlib,json,pathlib,sys
root=pathlib.Path(sys.argv[1]); extra=root/'artifacts/raw-extra.json'; extra.write_bytes(b'x')
rpc_path=root/'rpc-e2e.json'; rpc=json.loads(rpc_path.read_text()); rpc['scenarios']['preflight']['artifacts'].append({'path':'artifacts/raw-extra.json','sha256':hashlib.sha256(b'x').hexdigest()})
payload=json.dumps(rpc,separators=(',',':')).encode()+b'\n'; rpc_path.write_bytes(payload)
manifest=json.loads((root/'release-manifest.json').read_text()); manifest['artifacts'][0]['sha256']=hashlib.sha256(payload).hexdigest(); (root/'release-manifest.json').write_text(json.dumps(manifest,separators=(',',':'))+'\n')
PY
mkdir "$T/raw-total-rejected"
if production_freeze_bundle "$RAW_LIMIT_SOURCE" "$T/raw-total-rejected" >/dev/null 2>&1; then
  echo "bundle freeze accepted RPC raw artifacts above the cumulative limit" >&2
  exit 1
fi
python3 - "$RAW_LIMIT_SOURCE" <<'PY'
import hashlib,json,pathlib,sys
root=pathlib.Path(sys.argv[1]); raw=root/'artifacts/raw-0.json'
with raw.open('wb') as output: output.truncate(16*1024*1024+1)
rpc={'scenarios':{'preflight':{'artifacts':[{'path':'artifacts/raw-0.json','sha256':'0'*64}]}}}; payload=json.dumps(rpc,separators=(',',':')).encode()+b'\n'; (root/'rpc-e2e.json').write_bytes(payload)
(root/'release-manifest.json').write_text(json.dumps({'artifacts':[{'path':'rpc-e2e.json','sha256':hashlib.sha256(payload).hexdigest()}]},separators=(',',':'))+'\n')
PY
mkdir "$T/raw-single-rejected"
if RAW_OVERSIZE_ERROR="$(production_freeze_bundle "$RAW_LIMIT_SOURCE" "$T/raw-single-rejected" 2>&1)"; then
  echo "bundle freeze accepted an oversized RPC raw artifact" >&2
  exit 1
fi
[[ "$RAW_OVERSIZE_ERROR" == *"invalid release artifact: artifacts/raw-0.json"* ]]
for unsafe_path in /tmp/escape.json ../escape.json; do
  UNSAFE_SOURCE="$T/unsafe-$(printf '%s' "$unsafe_path" | shasum -a 256 | cut -c1-8)"
  mkdir "$UNSAFE_SOURCE"
  python3 - "$UNSAFE_SOURCE" "$unsafe_path" <<'PY'
import hashlib,json,pathlib,sys
root=pathlib.Path(sys.argv[1]); unsafe=sys.argv[2]
rpc={'scenarios':{'preflight':{'artifacts':[{'path':unsafe,'sha256':'0'*64}]}}}; payload=json.dumps(rpc,separators=(',',':')).encode()+b'\n'; (root/'rpc-e2e.json').write_bytes(payload)
(root/'release-manifest.json').write_text(json.dumps({'artifacts':[{'path':'rpc-e2e.json','sha256':hashlib.sha256(payload).hexdigest()}]},separators=(',',':'))+'\n')
PY
  mkdir "$UNSAFE_SOURCE-target"
  if production_freeze_bundle "$UNSAFE_SOURCE" "$UNSAFE_SOURCE-target" >/dev/null 2>&1; then
    echo "bundle freeze accepted unsafe RPC artifact path $unsafe_path" >&2
    exit 1
  fi
done
python3 - "$T" <<'PY'
import hashlib,json,os,pathlib,sys
root=pathlib.Path(sys.argv[1])
def manifest(case, refs):
    payload=json.dumps({'scenarios':{'preflight':{'artifacts':refs}}},separators=(',',':')).encode()+b'\n'
    (case/'rpc-e2e.json').write_bytes(payload)
    (case/'release-manifest.json').write_text(json.dumps({'artifacts':[{'path':'rpc-e2e.json','sha256':hashlib.sha256(payload).hexdigest()}]},separators=(',',':'))+'\n')
payload=b'{}\n'; digest=hashlib.sha256(payload).hexdigest()
case=root/'freeze-duplicate-source'; (case/'artifacts').mkdir(parents=True); (case/'artifacts/raw.json').write_bytes(payload)
manifest(case,[{'path':'artifacts/raw.json','sha256':digest},{'path':'artifacts/raw.json','sha256':digest}])
outside=root/'freeze-symlink-outside.json'; outside.write_bytes(payload)
case=root/'freeze-leaf-symlink-source'; (case/'artifacts').mkdir(parents=True); os.symlink(outside,case/'artifacts/raw.json')
manifest(case,[{'path':'artifacts/raw.json','sha256':digest}])
outside_dir=root/'freeze-symlink-outside-dir'; outside_dir.mkdir(); (outside_dir/'raw.json').write_bytes(payload)
case=root/'freeze-directory-symlink-source'; case.mkdir(); os.symlink(outside_dir,case/'artifacts')
manifest(case,[{'path':'artifacts/raw.json','sha256':digest}])
case=root/'freeze-prefix-source'; (case/'artifacts/node').mkdir(parents=True)
manifest(case,[{'path':'artifacts/node','sha256':digest}])
case=root/'freeze-dot-source'; (case/'artifacts').mkdir(parents=True); (case/'artifacts/raw.json').write_bytes(payload)
manifest(case,[{'path':'artifacts/./raw.json','sha256':digest}])
PY
for freeze_case in duplicate leaf-symlink directory-symlink prefix dot; do
  mkdir "$T/freeze-$freeze_case-rejected"
  if production_freeze_bundle "$T/freeze-$freeze_case-source" "$T/freeze-$freeze_case-rejected" >/dev/null 2>&1; then
    echo "bundle freeze accepted unsafe $freeze_case RPC artifact input" >&2
    exit 1
  fi
done
: >"$TRACE"
BRIDGE_MONITOR_RPC_URL_1=https://one.example BRIDGE_MONITOR_RPC_URL_2=https://two.example BRIDGE_MONITOR_RPC_URL_3=https://three.example \
  "$DRIVER_ROOT/scripts/production-live-preflight.sh" verify-monitor-drill "$T/bundle" >/dev/null
[[ "$(grep -c '^cast block finalized' "$TRACE")" -eq 3 ]]
[[ "$(grep -c '^cast rpc ' "$TRACE")" -eq 9 ]]
! grep -Eq '^cast block [0-9]+' "$TRACE"
for chain_fault in failure malformed mismatch; do
  if [[ "$chain_fault" == failure ]]; then args=(PROVIDER_CHAIN_FAILURES=1); elif [[ "$chain_fault" == malformed ]]; then args=(PROVIDER_MALFORMED_CHAINS=1); else args=(PROVIDER_WRONG_CHAINS=1); fi
  if env "${args[@]}" BRIDGE_MONITOR_RPC_URL_1=https://one.example BRIDGE_MONITOR_RPC_URL_2=https://two.example BRIDGE_MONITOR_RPC_URL_3=https://three.example \
    "$DRIVER_ROOT/scripts/production-live-preflight.sh" verify-monitor-drill "$T/bundle" >/dev/null 2>&1; then
    echo "monitor drill accepted one provider chain ID $chain_fault" >&2; exit 1
  fi
done
if CANONICAL_PROBE_MALFORMED=true \
  BRIDGE_MONITOR_RPC_URL_1=https://one.example BRIDGE_MONITOR_RPC_URL_2=https://two.example BRIDGE_MONITOR_RPC_URL_3=https://three.example \
  "$DRIVER_ROOT/scripts/production-live-preflight.sh" verify-monitor-drill "$T/bundle" >/dev/null 2>&1; then
  echo "monitor drill accepted malformed canonical probes" >&2
  exit 1
fi
if BRIDGE_GATE_A_MANIFEST_SHA256="$(printf 'b%.0s' {1..64})" BRIDGE_RELEASE_BUNDLE="$T/bundle" BRIDGE_CANISTER_INIT_FILE="$T/init.json" BRIDGE_CONSTRUCTOR_ARGS_FILE="$T/constructors.json" BRIDGE_DEPLOYER_ADDRESS=0x4444444444444444444444444444444444444444 BRIDGE_ICP_IDENTITY=production "$DRIVER_ROOT/scripts/production-deploy-driver.sh" >/dev/null 2>&1; then
  echo "deploy driver accepted a forged Gate A hash" >&2; exit 1
fi
if PROOF_GATE_FAIL=true BRIDGE_GATE_A_MANIFEST_SHA256="$(printf 'a%.0s' {1..64})" BRIDGE_RELEASE_BUNDLE="$T/bundle" BRIDGE_CANISTER_INIT_FILE="$T/init.json" BRIDGE_CONSTRUCTOR_ARGS_FILE="$T/constructors.json" BRIDGE_DEPLOYER_ADDRESS=0x4444444444444444444444444444444444444444 BRIDGE_ICP_IDENTITY=production "$DRIVER_ROOT/scripts/production-deploy-driver.sh" >/dev/null 2>&1; then
  echo "deploy driver accepted a failed proof gate" >&2; exit 1
fi
[[ ! -e "$TIMELOCK_DEPLOYED_MARKER" && ! -e "$BRIDGE_DEPLOYED_MARKER" ]]
if REPRODUCIBLE_BUILD_FAIL=true BRIDGE_GATE_A_MANIFEST_SHA256="$(printf 'a%.0s' {1..64})" BRIDGE_RELEASE_BUNDLE="$T/bundle" BRIDGE_CANISTER_INIT_FILE="$T/init.json" BRIDGE_CONSTRUCTOR_ARGS_FILE="$T/constructors.json" BRIDGE_DEPLOYER_ADDRESS=0x4444444444444444444444444444444444444444 BRIDGE_ICP_IDENTITY=production "$DRIVER_ROOT/scripts/production-deploy-driver.sh" >/dev/null 2>&1; then
  echo "deploy driver accepted a failed reproducible artifact build" >&2; exit 1
fi
[[ ! -e "$TIMELOCK_DEPLOYED_MARKER" && ! -e "$BRIDGE_DEPLOYED_MARKER" ]]
if CANISTER_PREDEPLOY_FAIL=true BRIDGE_GATE_A_MANIFEST_SHA256="$(printf 'a%.0s' {1..64})" BRIDGE_RELEASE_BUNDLE="$T/bundle" BRIDGE_CANISTER_INIT_FILE="$T/init.json" BRIDGE_CONSTRUCTOR_ARGS_FILE="$T/constructors.json" BRIDGE_DEPLOYER_ADDRESS=0x4444444444444444444444444444444444444444 BRIDGE_ICP_IDENTITY=production "$DRIVER_ROOT/scripts/production-deploy-driver.sh" >/dev/null 2>&1; then
  echo "deploy driver accepted live Canister drift before Base submission" >&2; exit 1
fi
[[ ! -e "$TIMELOCK_DEPLOYED_MARKER" && ! -e "$BRIDGE_DEPLOYED_MARKER" ]]
if CANISTER_MODULE_DRIFT=true BRIDGE_GATE_A_MANIFEST_SHA256="$(printf 'a%.0s' {1..64})" BRIDGE_RELEASE_BUNDLE="$T/bundle" BRIDGE_CANISTER_INIT_FILE="$T/init.json" BRIDGE_CONSTRUCTOR_ARGS_FILE="$T/constructors.json" BRIDGE_DEPLOYER_ADDRESS=0x4444444444444444444444444444444444444444 BRIDGE_ICP_IDENTITY=production "$DRIVER_ROOT/scripts/production-deploy-driver.sh" >/dev/null 2>&1; then
  echo "deploy driver accepted certified Canister module drift" >&2; exit 1
fi
[[ ! -e "$TIMELOCK_DEPLOYED_MARKER" && ! -e "$BRIDGE_DEPLOYED_MARKER" ]]
if CANISTER_CONTROLLER_DRIFT=true BRIDGE_GATE_A_MANIFEST_SHA256="$(printf 'a%.0s' {1..64})" BRIDGE_RELEASE_BUNDLE="$T/bundle" BRIDGE_CANISTER_INIT_FILE="$T/init.json" BRIDGE_CONSTRUCTOR_ARGS_FILE="$T/constructors.json" BRIDGE_DEPLOYER_ADDRESS=0x4444444444444444444444444444444444444444 BRIDGE_ICP_IDENTITY=production "$DRIVER_ROOT/scripts/production-deploy-driver.sh" >/dev/null 2>&1; then
  echo "deploy driver accepted a certified extra Canister controller" >&2; exit 1
fi
[[ ! -e "$TIMELOCK_DEPLOYED_MARKER" && ! -e "$BRIDGE_DEPLOYED_MARKER" ]]
for fee_fault in base-ceiling priority-ceiling malformed-base unavailable-priority unavailable-base missing-base decimal-base leading-zero-base malformed-priority decimal-priority negative-priority; do
  : >"$TRACE"
  if [[ "$fee_fault" == base-ceiling ]]; then fee_env=(DEPLOY_BASE_FEE=99)
  elif [[ "$fee_fault" == priority-ceiling ]]; then fee_env=(DEPLOY_SUGGESTED_PRIORITY_FEE=3)
  elif [[ "$fee_fault" == malformed-base ]]; then fee_env=('DEPLOY_BASE_FEE_RAW={"baseFeePerGas":false}')
  elif [[ "$fee_fault" == unavailable-priority ]]; then fee_env=(DEPLOY_PRIORITY_FEE_RPC_FAIL=true)
  elif [[ "$fee_fault" == unavailable-base ]]; then fee_env=(DEPLOY_FEE_RPC_FAIL=true)
  elif [[ "$fee_fault" == missing-base ]]; then fee_env=('DEPLOY_BASE_FEE_RAW={}')
  elif [[ "$fee_fault" == decimal-base ]]; then fee_env=('DEPLOY_BASE_FEE_RAW={"baseFeePerGas":"98"}')
  elif [[ "$fee_fault" == leading-zero-base ]]; then fee_env=('DEPLOY_BASE_FEE_RAW={"baseFeePerGas":"0x062"}')
  elif [[ "$fee_fault" == malformed-priority ]]; then fee_env=('DEPLOY_PRIORITY_FEE_RAW=false')
  elif [[ "$fee_fault" == decimal-priority ]]; then fee_env=('DEPLOY_PRIORITY_FEE_RAW="2"')
  else fee_env=('DEPLOY_PRIORITY_FEE_RAW="-1"')
  fi
  if env "${fee_env[@]}" BRIDGE_GATE_A_MANIFEST_SHA256="$(printf 'a%.0s' {1..64})" BRIDGE_RELEASE_BUNDLE="$T/bundle" BRIDGE_CANISTER_INIT_FILE="$T/init.json" BRIDGE_CONSTRUCTOR_ARGS_FILE="$T/constructors.json" BRIDGE_DEPLOYER_ADDRESS=0x4444444444444444444444444444444444444444 BRIDGE_ICP_IDENTITY=production "$DRIVER_ROOT/scripts/production-deploy-driver.sh" >/dev/null 2>&1; then
    echo "deploy driver accepted Base fee fault: $fee_fault" >&2; exit 1
  fi
  if grep -q '^forge ' "$TRACE"; then echo "deploy driver broadcast after Base fee fault: $fee_fault" >&2; exit 1; fi
  [[ ! -e "$TIMELOCK_DEPLOYED_MARKER" && ! -e "$BRIDGE_DEPLOYED_MARKER" && ! -e "$BRIDGE_DEPLOYMENT_BINDING_FILE.checkpoint" ]]
done
if PROOF_GATE_MUTATE_SOURCE=true BRIDGE_GATE_A_MANIFEST_SHA256="$(printf 'a%.0s' {1..64})" BRIDGE_RELEASE_BUNDLE="$T/bundle" BRIDGE_CANISTER_INIT_FILE="$T/init.json" BRIDGE_CONSTRUCTOR_ARGS_FILE="$T/constructors.json" BRIDGE_DEPLOYER_ADDRESS=0x4444444444444444444444444444444444444444 BRIDGE_ICP_IDENTITY=production "$DRIVER_ROOT/scripts/production-deploy-driver.sh" >/dev/null 2>&1; then
  echo "deploy driver accepted source mutation during proofs" >&2; exit 1
fi
git -C "$DRIVER_ROOT" restore src/main.rs
[[ ! -e "$TIMELOCK_DEPLOYED_MARKER" && ! -e "$BRIDGE_DEPLOYED_MARKER" ]]
if DEPLOYMENT_RECEIPT_UNAVAILABLE=true BRIDGE_GATE_A_MANIFEST_SHA256="$(printf 'a%.0s' {1..64})" BRIDGE_RELEASE_BUNDLE="$T/bundle" "$DRIVER_ROOT/scripts/production-deploy-driver.sh" >/dev/null 2>&1; then
  echo "deploy driver accepted an unavailable Timelock receipt" >&2; exit 1
fi
python3 - "$BRIDGE_DEPLOYMENT_BINDING_FILE.checkpoint" <<'PY'
import json,sys
checkpoint=json.load(open(sys.argv[1],encoding='utf-8'))
assert checkpoint == {
    'phase':'timelock_submitted',
    'expected_address':'0x2222222222222222222222222222222222222222',
    'nonce':0,
    'transaction_hash':'0x'+'b'*64,
}
PY
[[ -e "$TIMELOCK_DEPLOYED_MARKER" && ! -e "$BRIDGE_DEPLOYED_MARKER" ]]
rm -f "$TIMELOCK_DEPLOYED_MARKER" "$BRIDGE_DEPLOYED_MARKER" "$BRIDGE_DEPLOYMENT_BINDING_FILE" "$BRIDGE_DEPLOYMENT_BINDING_FILE.checkpoint"
if DEPLOYMENT_BLOCK_HASH_INVALID=true BRIDGE_GATE_A_MANIFEST_SHA256="$(printf 'a%.0s' {1..64})" BRIDGE_RELEASE_BUNDLE="$T/bundle" "$DRIVER_ROOT/scripts/production-deploy-driver.sh" >/dev/null 2>&1; then
  echo "deploy driver accepted an invalid receipt block hash" >&2; exit 1
fi
rm -f "$TIMELOCK_DEPLOYED_MARKER" "$BRIDGE_DEPLOYED_MARKER" "$BRIDGE_DEPLOYMENT_BINDING_FILE" "$BRIDGE_DEPLOYMENT_BINDING_FILE.checkpoint"
BRIDGE_GATE_A_MANIFEST_SHA256="$(printf 'a%.0s' {1..64})" BRIDGE_RELEASE_BUNDLE="$T/bundle" BRIDGE_CANISTER_INIT_FILE="$T/malicious-init.json" BRIDGE_CONSTRUCTOR_ARGS_FILE="$T/malicious-constructors.json" BRIDGE_DEPLOYER_ADDRESS=0x4444444444444444444444444444444444444444 BRIDGE_ICP_IDENTITY=production "$DRIVER_ROOT/scripts/production-deploy-driver.sh"
python3 - "$BRIDGE_DEPLOYMENT_BINDING_FILE" <<'PY'
import json,sys
binding=json.load(open(sys.argv[1],encoding='utf-8'))
assert binding['timelock']['block_hash']=='0x'+'c'*64
assert binding['bridge']['block_hash']=='0x'+'b'*64
PY
python3 - "$TRACE" <<'PY'
import sys
s=open(sys.argv[1]).read(); required=['proofs proofs','rebuild ','cast chain-id','cast wallet address','cast nonce','cast block pending','eth_maxPriorityFeePerGas','BridgeTimelockController','src/Bridge.sol']; pos=-1
for x in required:
  pos=s.find(x,pos+1); assert pos>=0,(x,s)
assert '--keystore' in s and '--ledger' not in s and 'unpause' not in s
assert 'MALICIOUS' not in s
PY
[[ ! -e "$T/path-proof-override-used" ]]
: >"$TRACE"
CONFIRMATION_RELAYER_IDENTITY_FIXTURE=production
ACTIVATION_ARTIFACT_FIXTURE="$T/activation-artifact.json"
CONTROLLER_PEM_FIXTURE="$T/controller.pem"
printf 'fixture-controller-key\n' >"$CONTROLLER_PEM_FIXTURE"
cat >"$T/bin/node" <<'SH'
#!/usr/bin/env bash
set -euo pipefail
echo "node $*" >>"$TRACE"
echo "node_identity=${IC_IDENTITY_PEM-unset}" >>"$TRACE"
output=""
receipt=""
replacement_output=""
replacement_binding=""
for ((index=1; index<=$#; index++)); do
  if [[ "${!index}" == --artifact-file ]]; then
    next=$((index+1)); output="${!next}"
  fi
  if [[ "${!index}" == --receipt-file ]]; then
    next=$((index+1)); receipt="${!next}"
  fi
  if [[ "${!index}" == --output-artifact-file ]]; then
    next=$((index+1)); replacement_output="${!next}"
  fi
  if [[ "${!index}" == --output-binding-file ]]; then
    next=$((index+1)); replacement_binding="${!next}"
  fi
done
if [[ "$*" == *prepare-schedule-activation* && -n "$output" ]]; then
  printf '{"operation_id":"0"}\n' >"$output"
fi
if [[ "$*" == *recover-activation* && -n "$output" ]]; then
  [[ "${RECOVERY_PENDING_MISSING:-false}" != true ]] || exit 1
  if [[ -e "$output" ]]; then
    [[ "$(<"$output")" == '{"operation_id":"0"}' ]] || exit 1
  else
    printf '{"operation_id":"0"}\n' >"$output"
  fi
fi
if [[ "$*" == *replace-activation* ]]; then
  printf '{"operation_id":"0","generation":1}\n' >"$replacement_output"
  printf '{"schema_version":1}\n' >"$replacement_binding"
fi
[[ -n "$receipt" ]] && printf '{"schema_version":1}\n' >"$receipt"
exit 0
SH
chmod +x "$T/bin/node"
production_validate_gate_b_source_chain "$DRIVER_ROOT" "$T/bundle"
for source_fault in missing tree; do
  SOURCE_CHAIN_CASE="$T/source-chain-$source_fault"
  mkdir "$SOURCE_CHAIN_CASE"
  cp "$T/bundle/post-gate-a-policy-transition.json" "$SOURCE_CHAIN_CASE/post-gate-a-policy-transition.json"
  python3 - "$SOURCE_CHAIN_CASE/post-gate-a-policy-transition.json" "$source_fault" <<'PY'
import json,sys
path,fault=sys.argv[1:]
value=json.load(open(path,encoding='utf-8'))
if fault == 'missing': value['upgrade_source_revision']='0'*40
else: value['upgrade_source_tree_sha256']='f'*64
with open(path,'w',encoding='utf-8') as output: json.dump(value,output,separators=(',',':')); output.write('\n')
PY
  if production_validate_gate_b_source_chain "$DRIVER_ROOT" "$SOURCE_CHAIN_CASE" >/dev/null 2>&1; then
    echo "Gate B source-chain validation accepted $source_fault upgrade source evidence" >&2
    exit 1
  fi
done

NONANCESTOR_REVISION="$(git -C "$DRIVER_ROOT" commit-tree "$(git -C "$DRIVER_ROOT" rev-parse 'HEAD^{tree}')" -m 'unrelated fixture commit')"
NONANCESTOR_TREE="$(git -C "$DRIVER_ROOT" --attr-source="$NONANCESTOR_REVISION" archive "$NONANCESTOR_REVISION" | shasum -a 256 | awk '{print $1}')"
NONANCESTOR_BUNDLE="$T/nonancestor-bundle"
cp -R "$T/bundle" "$NONANCESTOR_BUNDLE"
python3 - "$NONANCESTOR_BUNDLE/post-gate-a-policy-transition.json" "$NONANCESTOR_BUNDLE/release-manifest.json" "$NONANCESTOR_REVISION" "$NONANCESTOR_TREE" <<'PY'
import hashlib,json,sys
transition_path,manifest_path,revision,tree=sys.argv[1:]
transition=json.load(open(transition_path,encoding='utf-8'))
transition['upgrade_source_revision']=revision
transition['upgrade_source_tree_sha256']=tree
with open(transition_path,'w',encoding='utf-8') as output: json.dump(transition,output,separators=(',',':')); output.write('\n')
digest=hashlib.sha256(open(transition_path,'rb').read()).hexdigest()
manifest=json.load(open(manifest_path,encoding='utf-8'))
next(item for item in manifest['artifacts'] if item['path']=='post-gate-a-policy-transition.json')['sha256']=digest
with open(manifest_path,'w',encoding='utf-8') as output: json.dump(manifest,output,separators=(',',':')); output.write('\n')
PY
NONANCESTOR_SEAL_RECEIPT="$T/nonancestor-seal-receipt.json"
: >"$TRACE"
if BRIDGE_GATE_B_MANIFEST_SHA256="$(printf 'b%.0s' {1..64})" \
  BRIDGE_RELEASE_BUNDLE="$NONANCESTOR_BUNDLE" \
  BRIDGE_PRODUCTION_CONTROLLER_PEM="$CONTROLLER_PEM_FIXTURE" \
  BRIDGE_OPERATIONAL_CONFIG_SEAL_RECEIPT="$NONANCESTOR_SEAL_RECEIPT" \
  BRIDGE_CONFIRM_OPERATIONAL_CONFIG_SEAL=SEAL_PRODUCTION_OPERATIONAL_CONFIG \
  "$DRIVER_ROOT/scripts/production-seal-driver.sh" >/dev/null 2>&1; then
  echo "seal driver accepted a nonancestor production upgrade source" >&2
  exit 1
fi
! grep -q 'seal-operational-config' "$TRACE"
[[ ! -e "$NONANCESTOR_SEAL_RECEIPT.reservation.json" ]]

STALE_SEAL_RECEIPT="$T/stale-operational-config-seal-receipt.json"
printf '{"schema_version":1}\n' >"$STALE_SEAL_RECEIPT.attempt.json"
: >"$TRACE"
if BRIDGE_GATE_B_MANIFEST_SHA256="$(printf 'b%.0s' {1..64})" \
  BRIDGE_RELEASE_BUNDLE="$T/bundle" \
  BRIDGE_PRODUCTION_CONTROLLER_PEM="$CONTROLLER_PEM_FIXTURE" \
  BRIDGE_OPERATIONAL_CONFIG_SEAL_RECEIPT="$STALE_SEAL_RECEIPT" \
  BRIDGE_CONFIRM_OPERATIONAL_CONFIG_SEAL=SEAL_PRODUCTION_OPERATIONAL_CONFIG \
  "$DRIVER_ROOT/scripts/production-seal-driver.sh" >/dev/null 2>&1; then
  echo "seal driver accepted an attempt without its durable reservation" >&2
  exit 1
fi
! grep -q 'seal-operational-config' "$TRACE"
[[ ! -e "$STALE_SEAL_RECEIPT.reservation.json" ]]
SEAL_RECEIPT_FIXTURE="$T/operational-config-seal-receipt.json"
: >"$TRACE"
BRIDGE_GATE_B_MANIFEST_SHA256="$(printf 'b%.0s' {1..64})" \
  BRIDGE_RELEASE_BUNDLE="$T/bundle" \
  BRIDGE_PRODUCTION_CONTROLLER_PEM="$CONTROLLER_PEM_FIXTURE" \
  BRIDGE_OPERATIONAL_CONFIG_SEAL_RECEIPT="$SEAL_RECEIPT_FIXTURE" \
  BRIDGE_CONFIRM_OPERATIONAL_CONFIG_SEAL=SEAL_PRODUCTION_OPERATIONAL_CONFIG \
  "$DRIVER_ROOT/scripts/production-seal-driver.sh"
grep -q 'profile validate-bundle --offline --gate-b' "$TRACE"
grep -q 'proofs proofs' "$TRACE"
grep -q 'seal-operational-config' "$TRACE"
grep -q "node_identity=$CONTROLLER_PEM_FIXTURE" "$TRACE"
[[ -s "$SEAL_RECEIPT_FIXTURE" ]]
export SEAL_RECEIPT_HASH="$(shasum -a 256 "$SEAL_RECEIPT_FIXTURE" | awk '{print $1}')"
COMMON_ACTIVATION_ENV=(
  BRIDGE_GATE_B_MANIFEST_SHA256="$(printf 'b%.0s' {1..64})"
  BRIDGE_RELEASE_BUNDLE="$T/bundle"
  BRIDGE_ACTIVATION_PHASE=schedule
  BRIDGE_ACTIVATION_STEP=prepare
  BRIDGE_CONFIRM_ASSET_ACCEPTANCE=SCHEDULE_PRODUCTION_ASSET_ACTIVATION
  BRIDGE_ACTIVATION_ARTIFACT="$ACTIVATION_ARTIFACT_FIXTURE"
  BRIDGE_PRODUCTION_CONTROLLER_PEM="$CONTROLLER_PEM_FIXTURE"
  BRIDGE_CONFIRMATION_RELAYER_IDENTITY="$CONFIRMATION_RELAYER_IDENTITY_FIXTURE"
  BRIDGE_OPERATIONAL_CONFIG_SEAL_RECEIPT="$SEAL_RECEIPT_FIXTURE"
)
for invalid_confirmation in "" WRONG_CONFIRMATION; do
  : >"$TRACE"
  if env "${COMMON_ACTIVATION_ENV[@]}" \
    BRIDGE_CONFIRM_ASSET_ACCEPTANCE="$invalid_confirmation" \
    "$DRIVER_ROOT/scripts/production-activate-driver.sh" >/dev/null 2>&1; then
    echo "activation driver accepted a missing or incorrect direct confirmation token" >&2
    exit 1
  fi
  ! grep -q 'prepare-schedule-activation' "$TRACE"
done
: >"$TRACE"
if env CONFIRMATION_RELAYER_DRIFT=true "${COMMON_ACTIVATION_ENV[@]}" \
  "$DRIVER_ROOT/scripts/production-activate-driver.sh" >/dev/null 2>&1; then
  echo "activation driver accepted a confirmation relayer identity mismatch" >&2
  exit 1
fi
! grep -q 'prepare-schedule-activation' "$TRACE"
: >"$TRACE"
if env FINAL_LIVE_FAIL=true "${COMMON_ACTIVATION_ENV[@]}" \
  "$DRIVER_ROOT/scripts/production-activate-driver.sh" >/dev/null 2>&1; then
  echo "activation driver accepted a failed final live verification" >&2
  exit 1
fi
grep -q 'refresh_activation_attestation' "$TRACE"
! grep -q 'prepare-schedule-activation' "$TRACE"
: >"$TRACE"
rm -f "$ACTIVATION_ARTIFACT_FIXTURE"
env REFRESH_CALL_FAIL=true "${COMMON_ACTIVATION_ENV[@]}" \
  "$DRIVER_ROOT/scripts/production-activate-driver.sh"
grep -q '^icp identity principal --identity production$' "$TRACE"
python3 - "$TRACE" <<'PY'
import sys
trace=open(sys.argv[1],encoding='utf-8').read()
required=[
    'profile validate-bundle --offline --gate-b',
    'proofs proofs',
    'rebuild ',
    'icp identity principal --identity production',
    'icp canister call aaaaa-aa refresh_activation_attestation () -n ic --identity production --json',
    'profile verify-live schedule',
    'profile verify-controller-activation-authorization-fresh schedule',
    'node --no-warnings --experimental-strip-types',
    'prepare-schedule-activation',
]
position=-1
for item in required:
    position=trace.find(item,position+1)
    assert position >= 0, (item, trace)
PY
! grep -q 'list_nervous_system_functions' "$TRACE"
! grep -q 'manage_neuron' "$TRACE"
[[ -s "$ACTIVATION_ARTIFACT_FIXTURE" ]]
[[ -s "$ACTIVATION_ARTIFACT_FIXTURE.authorization.json" ]]
[[ -s "$ACTIVATION_ARTIFACT_FIXTURE.prepare-receipt.json" ]]

# A durable authorization written before the Canister call permits recovery
# without rerunning the pending-empty Gate B.
RECOVERY_ARTIFACT="$T/recovery-activation-artifact.json"
cp "$ACTIVATION_ARTIFACT_FIXTURE.authorization.json" "$RECOVERY_ARTIFACT.authorization.json"
: >"$TRACE"
env "${COMMON_ACTIVATION_ENV[@]}" BRIDGE_ACTIVATION_ARTIFACT="$RECOVERY_ARTIFACT" \
  "$DRIVER_ROOT/scripts/production-activate-driver.sh"
! grep -q 'proofs proofs' "$TRACE"
grep -q 'verify-controller-activation-authorization' "$TRACE"
[[ -s "$RECOVERY_ARTIFACT" && -s "$RECOVERY_ARTIFACT.prepare-receipt.json" ]]
! grep -q 'prepare-schedule-activation' "$TRACE"
MISSING_PENDING_ARTIFACT="$T/missing-pending-activation-artifact.json"
cp "$ACTIVATION_ARTIFACT_FIXTURE.authorization.json" "$MISSING_PENDING_ARTIFACT.authorization.json"
: >"$TRACE"
env RECOVERY_PENDING_MISSING=true "${COMMON_ACTIVATION_ENV[@]}" \
  BRIDGE_ACTIVATION_ARTIFACT="$MISSING_PENDING_ARTIFACT" \
  "$DRIVER_ROOT/scripts/production-activate-driver.sh"
grep -q 'recover-activation' "$TRACE"
grep -q 'proofs proofs' "$TRACE"
grep -q 'profile verify-live schedule' "$TRACE"
grep -q 'profile verify-controller-activation-authorization-fresh schedule' "$TRACE"
grep -q 'prepare-schedule-activation' "$TRACE"
grep -q "node_identity=$CONTROLLER_PEM_FIXTURE" "$TRACE"
[[ -s "$MISSING_PENDING_ARTIFACT" && -s "$MISSING_PENDING_ARTIFACT.prepare-receipt.json" ]]
STALE_RECOVERY_ARTIFACT="$T/stale-recovery-activation-artifact.json"
cp "$ACTIVATION_ARTIFACT_FIXTURE.authorization.json" "$STALE_RECOVERY_ARTIFACT.authorization.json"
: >"$TRACE"
if env RECOVERY_PENDING_MISSING=true STALE_ACTIVATION_AUTH=true \
  "${COMMON_ACTIVATION_ENV[@]}" BRIDGE_ACTIVATION_ARTIFACT="$STALE_RECOVERY_ARTIFACT" \
  "$DRIVER_ROOT/scripts/production-activate-driver.sh" >/dev/null 2>&1; then
  echo "activation recovery created a transaction from a stale authorization" >&2
  exit 1
fi
grep -q 'profile verify-controller-activation-authorization-fresh schedule' "$TRACE"
! grep -q 'prepare-schedule-activation' "$TRACE"
[[ ! -e "$STALE_RECOVERY_ARTIFACT" && ! -e "$STALE_RECOVERY_ARTIFACT.prepare-receipt.json" ]]
if env CANISTER_CONTROLLER_DRIFT=true "${COMMON_ACTIVATION_ENV[@]}" \
  "$DRIVER_ROOT/scripts/production-activate-driver.sh" >/dev/null 2>&1; then
  echo "activation resume accepted a changed certified controller set" >&2
  exit 1
fi
REPLACEMENT_ARTIFACT="$T/replacement-activation-artifact.json"
: >"$TRACE"
env "${COMMON_ACTIVATION_ENV[@]}" BRIDGE_ACTIVATION_STEP=replace \
  BRIDGE_ACTIVATION_REPLACEMENT_ARTIFACT="$REPLACEMENT_ARTIFACT" \
  BRIDGE_ACTIVATION_REPLACEMENT_MAX_FEE=200 \
  BRIDGE_ACTIVATION_REPLACEMENT_PRIORITY_FEE=3 \
  "$DRIVER_ROOT/scripts/production-activate-driver.sh"
grep -q 'profile verify-controller-activation-artifact schedule' "$TRACE"
grep -q 'replace-activation' "$TRACE"
[[ -s "$REPLACEMENT_ARTIFACT" && -s "$REPLACEMENT_ARTIFACT.authorization.json" && -s "$REPLACEMENT_ARTIFACT.prepare-receipt.json" ]]
: >"$TRACE"
if env ACTIVATION_BINDING_DRIFT=true "${COMMON_ACTIVATION_ENV[@]}" \
  BRIDGE_ACTIVATION_STEP=replace \
  BRIDGE_ACTIVATION_REPLACEMENT_ARTIFACT="$T/rejected-replacement.json" \
  BRIDGE_ACTIVATION_REPLACEMENT_MAX_FEE=200 \
  BRIDGE_ACTIVATION_REPLACEMENT_PRIORITY_FEE=3 \
  "$DRIVER_ROOT/scripts/production-activate-driver.sh" >/dev/null 2>&1; then
  echo "activation replacement accepted an artifact outside the exact Gate B binding" >&2
  exit 1
fi
! grep -q 'replace-activation' "$TRACE"
ARTIFACT_BEFORE="$(shasum -a 256 "$ACTIVATION_ARTIFACT_FIXTURE" | awk '{print $1}')"
: >"$TRACE"
env "${COMMON_ACTIVATION_ENV[@]}" BRIDGE_ACTIVATION_STEP=relay \
  BASE_RPC_URL=https://base.example \
  "$DRIVER_ROOT/scripts/production-activate-driver.sh"
grep -q 'node_identity=unset' "$TRACE"
grep -q 'profile verify-controller-activation-artifact schedule' "$TRACE"
grep -q ' relay --artifact-file ' "$TRACE"
[[ "$ARTIFACT_BEFORE" == "$(shasum -a 256 "$ACTIVATION_ARTIFACT_FIXTURE" | awk '{print $1}')" ]]
: >"$TRACE"
if env ACTIVATION_BINDING_DRIFT=true "${COMMON_ACTIVATION_ENV[@]}" \
  BRIDGE_ACTIVATION_STEP=relay BASE_RPC_URL=https://base.example \
  "$DRIVER_ROOT/scripts/production-activate-driver.sh" >/dev/null 2>&1; then
  echo "activation relay accepted an artifact outside the exact Gate B binding" >&2
  exit 1
fi
grep -q 'profile verify-controller-activation-artifact schedule' "$TRACE"
! grep -q ' relay --artifact-file ' "$TRACE"
cp "$ACTIVATION_ARTIFACT_FIXTURE.prepare-receipt.json" "$T/prepare-receipt.saved"
chmod u+w "$ACTIVATION_ARTIFACT_FIXTURE.prepare-receipt.json"
python3 - "$ACTIVATION_ARTIFACT_FIXTURE.prepare-receipt.json" <<'PY'
import json,sys
path=sys.argv[1]
value=json.load(open(path,encoding='utf-8'))
value['artifact_sha256']='ff'*32
with open(path,'w',encoding='utf-8') as output: json.dump(value,output,separators=(',',':')); output.write('\n')
PY
if env "${COMMON_ACTIVATION_ENV[@]}" BRIDGE_ACTIVATION_STEP=relay \
  BASE_RPC_URL=https://base.example "$DRIVER_ROOT/scripts/production-activate-driver.sh" >/dev/null 2>&1; then
  echo "activation relay accepted a Gate B binding with artifact hash drift" >&2
  exit 1
fi
mv "$T/prepare-receipt.saved" "$ACTIVATION_ARTIFACT_FIXTURE.prepare-receipt.json"

RELAYER_PEM_FIXTURE="$T/relayer.pem"
RAW_CONFIRMATION_FIXTURE="$T/activation-confirmation.json"
VERIFIED_ACTIVATION_FIXTURE="$T/controller-activation-receipt.json"
printf 'fixture-relayer-key\n' >"$RELAYER_PEM_FIXTURE"
: >"$TRACE"
env "${COMMON_ACTIVATION_ENV[@]}" BRIDGE_ACTIVATION_STEP=confirm \
  BRIDGE_CONFIRMATION_RELAYER_PEM="$RELAYER_PEM_FIXTURE" \
  BRIDGE_ACTIVATION_CONFIRMATION_RECEIPT="$RAW_CONFIRMATION_FIXTURE" \
  BRIDGE_CONTROLLER_ACTIVATION_RECEIPT="$VERIFIED_ACTIVATION_FIXTURE" \
  "$DRIVER_ROOT/scripts/production-activate-driver.sh"
grep -q 'profile verify-controller-activation-artifact schedule' "$TRACE"
grep -q "node_identity=$RELAYER_PEM_FIXTURE" "$TRACE"
grep -q ' confirm --artifact-file ' "$TRACE"
grep -q 'profile verify-controller-activation schedule' "$TRACE"
[[ -s "$RAW_CONFIRMATION_FIXTURE" ]]
: >"$TRACE"
if env ACTIVATION_BINDING_DRIFT=true "${COMMON_ACTIVATION_ENV[@]}" \
  BRIDGE_ACTIVATION_STEP=confirm \
  BRIDGE_CONFIRMATION_RELAYER_PEM="$RELAYER_PEM_FIXTURE" \
  BRIDGE_ACTIVATION_CONFIRMATION_RECEIPT="$T/rejected-confirmation.json" \
  BRIDGE_CONTROLLER_ACTIVATION_RECEIPT="$T/rejected-activation.json" \
  "$DRIVER_ROOT/scripts/production-activate-driver.sh" >/dev/null 2>&1; then
  echo "activation confirmation accepted an artifact outside the exact Gate B binding" >&2
  exit 1
fi
! grep -q ' confirm --artifact-file ' "$TRACE"
! grep -q '^cast send' "$TRACE"
! grep -q resume_new_deposits "$TRACE"
[[ -z "$(find "$TMPDIR" -maxdepth 1 -type d \( -name 'bridge-seal-plan.*' -o -name 'bridge-activation-plan.*' -o -name 'bridge-activation-inputs.*' \) -print -quit)" ]]
